/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SecurityInterface.framework/Versions/A/SecurityInterface
 */

@interface SFExpandableTextField : NSTextField {
    NSAttributedString * _fullString;
    BOOL  _isURLText;
    BOOL  _minimized;
}

- (id)_encodedURLString;
- (id)_expandableAttributedString:(id)arg1;
- (BOOL)_isURLString:(id)arg1;
- (void)awakeFromNib;
- (void)dealloc;
- (BOOL)isURLText;
- (BOOL)minimized;
- (void)mouseDown:(id)arg1;
- (void)resetCursorRects;
- (void)setAttributedStringValue:(id)arg1;
- (void)setMinimized:(BOOL)arg1;

@end
