/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SecurityInterface.framework/Versions/A/SecurityInterface
 */

@interface SFPasswordAsstController : NSObject {
    NSBox * _box;
    BOOL  _closingAssistant;
    SFEntropyBarView * _entropyBar;
    SFPasswordErrorSource * _errorSource;
    NSMatrix * _errorTable;
    NSTextField * _hint;
    SFPasswordAsstModel * _model;
    NSTextField * _newPassword;
    NSTextField * _originalPassword;
    NSTableView * _tableView;
    NSTextField * _verifyPassword;
    NSView * _view;
    NSPopUpButton * algorithmPopup;
    NSComboBox * choicesCombo;
    int  desiredAlgorithm;
    int  desiredLength;
    NSTextField * lengthDisplayField;
    NSSlider * lengthSlider;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  originalWindowFrame;
    int  previousAlgorithmIndex;
    int  previousDesiredLength;
    NSProgressIndicator * progressIndicator;
    NSButton * suggestButton;
    NSButton * suggestDiscloseButton;
}

- (void)addObserverTextField:(id)arg1;
- (void)algorithmPopupChanged:(id)arg1;
- (void)awakeFromNib;
- (void)choicesComboChanged:(id)arg1;
- (void)clear;
- (void)clearProgressBarToolTip;
- (void)clearVerifyField;
- (void)closing;
- (void)controlTextDidChange:(id)arg1;
- (void)controlTextDidEndEditing:(id)arg1;
- (void)dealloc;
- (double)entropy;
- (id)entryBar;
- (id)init;
- (id)initWithNib:(id)arg1;
- (id)model;
- (id)newPasswordField;
- (void)ourViewWasDisclosed:(id)arg1;
- (id)passphrase;
- (double)refresh:(id)arg1;
- (void)refreshSuggestions;
- (void)removeObserverTextField:(id)arg1;
- (void)setNewPasswordField:(id)arg1;
- (void)setOriginalPasswordField:(id)arg1;
- (void)setPassphraseInfoStrings:(int)arg1 :(int)arg2 :(double)arg3;
- (void)setPasswordFields:(id)arg1 verify:(id)arg2 original:(id)arg3;
- (void)setVerifyPasswordField:(id)arg1;
- (void)sliderChanged:(id)arg1;
- (void)suggestClicked:(id)arg1;
- (void)suggestDiscloseTextClicked:(id)arg1;
- (void)updatePasswordField:(id)arg1;
- (void)updateProgressBar:(double)arg1;
- (id)view;

@end
