/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreWiFi.framework/Versions/A/CoreWiFi
 */

@interface CoreWiFiAppleP2PIE : CoreWiFiIE

- (void)dealloc;
- (id)description;
- (void)generateIE;
- (id)initWithIE:(id)arg1;

@end
