/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaRemote.framework/Versions/A/MediaRemote
 */

@interface _MRSetStateMessageProtobuf : PBCodable <NSCopying> {
    NSString * _displayID;
    NSString * _displayName;
    struct { 
        unsigned int playbackState : 1; 
    }  _has;
    _MRNowPlayingInfoProtobuf * _nowPlayingInfo;
    _MRPlaybackQueueProtobuf * _playbackQueue;
    _MRPlaybackQueueCapabilitiesProtobuf * _playbackQueueCapabilities;
    unsigned int  _playbackState;
    _MRNowPlayingPlayerPathProtobuf * _playerPath;
    _MRPlaybackQueueRequestProtobuf * _request;
    _MRSupportedCommandsProtobuf * _supportedCommands;
}

@property (nonatomic, readwrite, retain) NSString *displayID;
@property (nonatomic, readwrite, retain) NSString *displayName;
@property (nonatomic, readonly) BOOL hasDisplayID;
@property (nonatomic, readonly) BOOL hasDisplayName;
@property (nonatomic, readonly) BOOL hasNowPlayingInfo;
@property (nonatomic, readonly) BOOL hasPlaybackQueue;
@property (nonatomic, readonly) BOOL hasPlaybackQueueCapabilities;
@property (nonatomic, readwrite) BOOL hasPlaybackState;
@property (nonatomic, readonly) BOOL hasPlayerPath;
@property (nonatomic, readonly) BOOL hasRequest;
@property (nonatomic, readonly) BOOL hasSupportedCommands;
@property (nonatomic, readwrite, retain) _MRNowPlayingInfoProtobuf *nowPlayingInfo;
@property (nonatomic, readwrite, retain) _MRPlaybackQueueProtobuf *playbackQueue;
@property (nonatomic, readwrite, retain) _MRPlaybackQueueCapabilitiesProtobuf *playbackQueueCapabilities;
@property (nonatomic, readwrite) unsigned int playbackState;
@property (nonatomic, readwrite, retain) _MRNowPlayingPlayerPathProtobuf *playerPath;
@property (nonatomic, readwrite, retain) _MRPlaybackQueueRequestProtobuf *request;
@property (nonatomic, readwrite, retain) _MRSupportedCommandsProtobuf *supportedCommands;

- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)description;
- (id)dictionaryRepresentation;
- (id)displayID;
- (id)displayName;
- (BOOL)hasDisplayID;
- (BOOL)hasDisplayName;
- (BOOL)hasNowPlayingInfo;
- (BOOL)hasPlaybackQueue;
- (BOOL)hasPlaybackQueueCapabilities;
- (BOOL)hasPlaybackState;
- (BOOL)hasPlayerPath;
- (BOOL)hasRequest;
- (BOOL)hasSupportedCommands;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (id)nowPlayingInfo;
- (id)playbackQueue;
- (id)playbackQueueCapabilities;
- (unsigned int)playbackState;
- (id)playerPath;
- (BOOL)readFrom:(id)arg1;
- (id)request;
- (void)setDisplayID:(id)arg1;
- (void)setDisplayName:(id)arg1;
- (void)setHasPlaybackState:(BOOL)arg1;
- (void)setNowPlayingInfo:(id)arg1;
- (void)setPlaybackQueue:(id)arg1;
- (void)setPlaybackQueueCapabilities:(id)arg1;
- (void)setPlaybackState:(unsigned int)arg1;
- (void)setPlayerPath:(id)arg1;
- (void)setRequest:(id)arg1;
- (void)setSupportedCommands:(id)arg1;
- (id)supportedCommands;
- (void)writeTo:(id)arg1;

@end
