/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaRemote.framework/Versions/A/MediaRemote
 */

@interface MRSetReadyStateMessage : MRProtocolMessage

- (unsigned long long)type;

@end
