/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaRemote.framework/Versions/A/MediaRemote
 */

@interface MRSetNowPlayingClientMessage : MRProtocolMessage

@property (nonatomic, readonly) void*client;

- (void*)client;
- (id)initWithClient:(void*)arg1;
- (unsigned long long)type;

@end
