/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Contacts.framework/Versions/A/Contacts
 */

@interface CNAccount : NSObject <NSCopying, NSSecureCoding> {
    NSString * _externalIdentifierString;
    NSString * _identifier;
}

@property (atomic, readonly, copy) NSString *externalIdentifierString;
@property (atomic, readonly, copy) NSString *identifier;

+ (id)identifierProvider;
+ (id)localAccount;
+ (id)makeIdentifier;
+ (id)makeIdentifierString;
+ (BOOL)supportsSecureCoding;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)externalIdentifierString;
- (unsigned long long)hash;
- (id)identifier;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithExternalIdentifier:(id)arg1;
- (id)initWithIdentifier:(id)arg1 externalIdentifier:(id)arg2;
- (BOOL)isEqual:(id)arg1;

@end
