/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Contacts.framework/Versions/A/Contacts
 */

@interface CNCDGroupSaveExecutor : NSObject {
    CNCDSaveContext * _saveContext;
}

- (void).cxx_destruct;
- (void)addGroups;
- (id)allGroupIdentifiers;
- (void)deleteGroups;
- (void)enumerateAddedGroups:(id)arg1;
- (id)initWithSaveContext:(id)arg1;
- (void)saveGroups;
- (void)updateGroupSnapshots;
- (void)updateGroups;

@end
