/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Contacts.framework/Versions/A/Contacts
 */

@interface CNContainerOfContactPredicate : CNPredicate <CNCDContainerPredicate> {
    NSString * _identifier;
}

@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (atomic, readonly) unsigned long long hash;
@property (nonatomic, readonly, copy) NSString *identifier;
@property (atomic, readonly) Class superclass;

- (void).cxx_destruct;
- (id)cn_coreDataPredicate;
- (id)cn_persistenceFilterRequest;
- (id)cn_secondaryRecursePredicate;
- (id)cn_topLevelFilter;
- (id)identifier;
- (id)initWithIdentifier:(id)arg1;

@end
