/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Contacts.framework/Versions/A/Contacts
 */

@interface CNContactChangesObserverProxy : NSObject {
    CNContact * _contactSnapshot;
    NSArray * _keysToFetch;
    <CNContactChangesObserver> * _observer;
    BOOL  _unify;
}

@property (nonatomic, readwrite, retain) CNContact *contactSnapshot;
@property (nonatomic, readwrite, retain) NSArray *keysToFetch;
@property (nonatomic, readwrite) <CNContactChangesObserver> *observer;
@property (nonatomic, readwrite) BOOL unify;

- (void).cxx_destruct;
- (id)contactSnapshot;
- (id)keysToFetch;
- (id)observer;
- (void)setContactSnapshot:(id)arg1;
- (void)setKeysToFetch:(id)arg1;
- (void)setObserver:(id)arg1;
- (void)setUnify:(BOOL)arg1;
- (BOOL)unify;

@end
