/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Contacts.framework/Versions/A/Contacts
 */

@interface CNContactsLoggerProvider : NSObject <CNContactsLoggerProvider> {
    <CNContactsLogger> * _contactsLogger;
    <CNRegulatoryLogger> * _regulatoryLogger;
    <CNSpotlightIndexingLogger> * _spotlightIndexingLogger;
}

@property (nonatomic, readonly) <CNContactsLogger> *contactsLogger;
@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (atomic, readonly) unsigned long long hash;
@property (nonatomic, readonly) <CNRegulatoryLogger> *regulatoryLogger;
@property (nonatomic, readonly) <CNSpotlightIndexingLogger> *spotlightIndexingLogger;
@property (atomic, readonly) Class superclass;

+ (id)defaultProvider;

- (void).cxx_destruct;
- (id)contactsLogger;
- (id)regulatoryLogger;
- (id)spotlightIndexingLogger;

@end
