/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Contacts.framework/Versions/A/Contacts
 */

@interface CNEmailAddressContactPredicate : CNPredicate <CNCDContactPredicate, CNSuggestedContactPredicate> {
    NSString * _emailAddress;
    BOOL  _returnsMultipleResults;
}

@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (nonatomic, readonly, copy) NSString *emailAddress;
@property (atomic, readonly) unsigned long long hash;
@property (nonatomic, readonly) BOOL returnsMultipleResults;
@property (atomic, readonly) Class superclass;

+ (BOOL)supportsSecureCoding;

- (void).cxx_destruct;
- (id)description;
- (id)emailAddress;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (id)initWithEmailAddress:(id)arg1 returnMultipleResults:(BOOL)arg2;
- (BOOL)isEqual:(id)arg1;
- (BOOL)returnsMultipleResults;

// CNEmailAddressContactPredicate (CoreData)

- (id)cn_coreDataPredicate;

// CNEmailAddressContactPredicate (Suggested)

- (id)sgContactMatchesWithSortOrder:(long long)arg1 mutableObjects:(BOOL)arg2 service:(id)arg3 error:(id*)arg4;

@end
