/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/GeoServices
 */

@interface _GEOThrottleState : NSObject {
    double  _lastResetTime;
    unsigned long long  _requestCount;
}

@property (nonatomic, readwrite) double lastResetTime;
@property (nonatomic, readwrite) unsigned long long requestCount;

- (id)description;
- (double)lastResetTime;
- (unsigned long long)requestCount;
- (void)setLastResetTime:(double)arg1;
- (void)setRequestCount:(unsigned long long)arg1;

@end
