/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/GeoServices
 */

@interface _GEOCategorySuggestionsManagerRemoteProxy : NSObject <GEOCategorySuggestionsManagerServerProxy>

@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (atomic, readonly) unsigned long long hash;
@property (atomic, readonly) Class superclass;

- (void)updateCachedSpotlightCategorySuggestions:(id)arg1;

@end
