/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/GeoServices
 */

@interface GEOABClientConfig : PBCodable <NSCopying> {
    NSString * _assignedAbBranchId;
    NSMutableArray * _configKeyValues;
    NSMutableArray * _debugExperimentBranchs;
    PBUnknownFields * _unknownFields;
}

@property (nonatomic, readwrite, retain) NSString *assignedAbBranchId;
@property (nonatomic, readwrite, retain) NSMutableArray *configKeyValues;
@property (nonatomic, readwrite, retain) NSMutableArray *debugExperimentBranchs;
@property (nonatomic, readonly) BOOL hasAssignedAbBranchId;
@property (nonatomic, readonly) PBUnknownFields *unknownFields;

+ (Class)configKeyValueType;
+ (Class)debugExperimentBranchType;

- (void).cxx_destruct;
- (void)addConfigKeyValue:(id)arg1;
- (void)addDebugExperimentBranch:(id)arg1;
- (id)assignedAbBranchId;
- (void)clearConfigKeyValues;
- (void)clearDebugExperimentBranchs;
- (id)configKeyValueAtIndex:(unsigned long long)arg1;
- (id)configKeyValues;
- (unsigned long long)configKeyValuesCount;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)debugExperimentBranchAtIndex:(unsigned long long)arg1;
- (id)debugExperimentBranchs;
- (unsigned long long)debugExperimentBranchsCount;
- (id)description;
- (id)dictionaryRepresentation;
- (BOOL)hasAssignedAbBranchId;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)setAssignedAbBranchId:(id)arg1;
- (void)setConfigKeyValues:(id)arg1;
- (void)setDebugExperimentBranchs:(id)arg1;
- (id)unknownFields;
- (void)writeTo:(id)arg1;

@end
