/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/GeoServices
 */

@interface GEODataRequestState : GEOCapturedState {
    BOOL  _HTTPMethod;
    BOOL  _HTTPShouldHandleCookies;
    NSURL * _URL;
    NSDictionary * _additionalHTTPHeaders;
    BOOL  _allowsCellularAccess;
    GEOApplicationAuditToken * _auditToken;
    NSData * _bodyData;
    NSData * _cachedData;
    int  _kind;
    double  _timeoutInterval;
    NSDictionary * _xpcRequestDictionary;
}

+ (const char *)decoderType;
+ (BOOL)supportsSecureCoding;
+ (id)xpcRequestDictionaryWithXPCRequest:(id)arg1;

- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end
