/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/GeoServices
 */

@interface GEODataURLSessionTask : NSObject <GEODataSessionTask, GEOStateCapturing> {
    NSObject<OS_os_activity> * _activity;
    NSURLSessionDataTask * _backingTask;
    BOOL  _backingTaskNeedsResume;
    NSData * _cachedData;
    <GEODataSessionTaskDelegate> * _delegate;
    NSObject<OS_dispatch_queue> * _delegateQueue;
    double  _endTime;
    NSError * _error;
    BOOL  _finished;
    float  _priority;
    unsigned int  _qos;
    NSMutableData * _receivedData;
    GEODataRequest * _request;
    int  _requestKind;
    unsigned int  _sessionIdentifier;
    NSObject<OS_dispatch_queue> * _sessionIsolation;
    double  _startTime;
    unsigned long long  _stateCaptureHandle;
    unsigned int  _taskIdentifier;
    GEODataURLSessionTaskQueue * _taskQueue;
    NSURLSessionTaskMetrics * _urlTaskMetrics;
}

@property (nonatomic, readonly) long long HTTPStatusCode;
@property (nonatomic, readonly) float _priority;
@property (atomic, readonly) NSObject<OS_os_activity> *activity;
@property (nonatomic, readonly) NSURLSessionDataTask *backingTask;
@property (nonatomic, readwrite, copy) NSData *cachedData;
@property (nonatomic, readonly) GEOClientMetrics *clientMetrics;
@property (nonatomic, readonly) unsigned long long contentLength;
@property (nonatomic, readonly) NSString *contentLengthString;
@property (atomic, readonly, copy) NSString *debugDescription;
@property (nonatomic, readonly) <GEODataSessionTaskDelegate> *delegate;
@property (nonatomic, readonly) NSObject<OS_dispatch_queue> *delegateQueue;
@property (atomic, readonly, copy) NSString *description;
@property (atomic, readonly) double elapsedTime;
@property (nonatomic, readonly) NSString *entityTag;
@property (nonatomic, readonly) NSError *error;
@property (nonatomic, readonly) BOOL failedDueToCancel;
@property (atomic, readonly) BOOL failedDueToCancel;
@property (nonatomic, readonly) BOOL finished;
@property (atomic, readonly) unsigned long long hash;
@property (nonatomic, readonly) unsigned long long incomingPayloadSize;
@property (nonatomic, readonly) NSURL *originalRequestURL;
@property (nonatomic, readonly) NSURLRequest *originalURLRequest;
@property (nonatomic, readonly) unsigned long long outgoingPayloadSize;
@property (atomic, readwrite) float priority;
@property (nonatomic, readonly) BOOL protocolBufferHasPreamble;
@property (nonatomic, readonly) NSData *receivedData;
@property (nonatomic, readonly) NSString *remoteAddressAndPort;
@property (nonatomic, readonly) GEODataRequest *request;
@property (nonatomic, readonly) int requestKind;
@property (nonatomic, readonly) NSHTTPURLResponse *response;
@property (nonatomic, readwrite) unsigned int sessionIdentifier;
@property (nonatomic, readonly) double startTime;
@property (atomic, readonly) Class superclass;
@property (nonatomic, readonly) unsigned int taskIdentifier;
@property (nonatomic, readwrite, retain) GEODataURLSessionTaskQueue *taskQueue;
@property (getter=isTileRequest, nonatomic, readonly) BOOL tileRequest;
@property (nonatomic, readonly) NSURLSessionTaskMetrics *urlTaskMetrics;

- (void).cxx_destruct;
- (void)_prepareForRestart;
- (void)_start;
- (id)activity;
- (id)backingTask;
- (id)cachedData;
- (void)cancel;
- (id)clientMetrics;
- (void)dealloc;
- (id)delegate;
- (id)delegateQueue;
- (id)description;
- (id)error;
- (BOOL)failedDueToCancel;
- (BOOL)finished;
- (unsigned long long)incomingPayloadSize;
- (id)init;
- (id)initWithSession:(id)arg1 delegate:(id)arg2 delegateQueue:(id)arg3 requestKind:(int)arg4;
- (BOOL)isTileRequest;
- (void)notifyDelegateWithSession:(id)arg1;
- (id)originalURLRequest;
- (unsigned long long)outgoingPayloadSize;
- (float)priority;
- (BOOL)protocolBufferHasPreamble;
- (id)receivedData;
- (id)remoteAddressAndPort;
- (id)request;
- (int)requestKind;
- (id)response;
- (unsigned int)sessionIdentifier;
- (void)setCachedData:(id)arg1;
- (void)setPriority:(float)arg1;
- (void)setSessionIdentifier:(unsigned int)arg1;
- (void)setTaskQueue:(id)arg1;
- (void)start;
- (double)startTime;
- (unsigned int)taskIdentifier;
- (id)taskQueue;
- (id)urlTaskMetrics;

// GEODataURLSessionTask (Convenience)

- (long long)HTTPStatusCode;
- (unsigned long long)contentLength;
- (id)contentLengthString;
- (id)entityTag;
- (id)originalRequestURL;

// GEODataURLSessionTask (EntityTag)

- (BOOL)didValidateEntityTagForData:(id*)arg1 entityTag:(id*)arg2;

// GEODataURLSessionTask (GEOStateCapturing)

- (id)captureStateWithHints:(struct os_state_hints_s { unsigned int x1; char *x2; unsigned int x3; unsigned int x4; }*)arg1;

// GEODataURLSessionTask (Queue)

- (float)_priority;
- (void)startDequeuedFromQueue:(id)arg1;

// GEODataURLSessionTask (Statistics)

- (double)elapsedTime;

// GEODataURLSessionTask (Tiles)

- (BOOL)validateContentLengthWithError:(id*)arg1;
- (BOOL)validateNonEmptyResponseWithError:(id*)arg1;
- (BOOL)validateTileResponseWithError:(id*)arg1;

// GEODataURLSessionTask (URLSessionTask)

- (id)createURLRequest;
- (id)createURLSessionTaskWithSession:(id)arg1 request:(id)arg2;
- (void)dataSession:(id)arg1 taskDidCompleteWithError:(id)arg2;
- (void)dataSession:(id)arg1 willSendRequestForEstablishedConnection:(id)arg2 completionHandler:(id)arg3;
- (void)didCollectMetrics:(id)arg1;
- (void)didReceiveData:(id)arg1;
- (void)didReceiveResponse:(id)arg1 completionHandler:(id)arg2;
- (void)updateRequest:(id)arg1 completionHandler:(id)arg2;

@end
