/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/GeoServices
 */

@interface GEOMapItemAttribution : NSObject {
    NSArray * _attributionURLs;
    GEOSearchAttributionInfo * _info;
    NSString * _poiID;
    NSString * _yelpID;
}

@property (nonatomic, readonly) NSArray *attributionApps;
@property (nonatomic, readonly) NSArray *attributionURLs;
@property (nonatomic, readonly) NSString *providerID;
@property (nonatomic, readonly) NSString *providerName;
@property (nonatomic, readonly) BOOL requiresAttributionInCallout;
@property (nonatomic, readonly) BOOL shouldOpenInAppStore;
@property (nonatomic, readonly) NSString *webBaseActionURL;

- (void).cxx_destruct;
- (id)_yelpHTTPURLForRequirement:(int)arg1 withUID:(id)arg2 writeAReview:(BOOL)arg3;
- (id)attributionApps;
- (id)attributionURLs;
- (id)initWithSearchAttributionInfo:(id)arg1 attributionURLs:(id)arg2;
- (id)initWithSearchAttributionInfo:(id)arg1 attributionURLs:(id)arg2 poiID:(id)arg3;
- (id)initWithSearchAttributionInfo:(id)arg1 attributionURLs:(id)arg2 yelpID:(id)arg3;
- (id)providerID;
- (id)providerLogoPathForScale:(double)arg1;
- (id)providerName;
- (id)providerSnippetLogoPathForScale:(double)arg1;
- (BOOL)requiresAttributionInCallout;
- (BOOL)shouldOpenInAppStore;
- (id)webBaseActionURL;

@end
