/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/GeoServices
 */

@interface GEOMapFeatureTransitHall : GEOMapFeatureTransitPoint

- (id)hall;

@end
