/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/GeoServices
 */

@interface GEOPlace : PBCodable <GEOURLSerializable, NSCopying> {
    GEOAddress * _address;
    int  _addressGeocodeAccuracy;
    double  _area;
    NSMutableArray * _business;
    GEOLatLng * _center;
    GEOMapRegion * _displayMapRegion;
    NSMutableArray * _entryPoints;
    long long  _geoId;
    struct { 
        unsigned int area : 1; 
        unsigned int geoId : 1; 
        unsigned int uID : 1; 
        unsigned int addressGeocodeAccuracy : 1; 
        unsigned int localSearchProviderID : 1; 
        unsigned int referenceFrame : 1; 
        unsigned int type : 1; 
        unsigned int isDisputed : 1; 
    }  _has;
    BOOL  _isDisputed;
    int  _localSearchProviderID;
    GEOMapRegion * _mapRegion;
    NSString * _name;
    GEOAddress * _phoneticAddress;
    NSString * _phoneticLocaleIdentifier;
    NSString * _phoneticName;
    int  _referenceFrame;
    NSMutableArray * _roadAccessPoints;
    NSString * _spokenAddress;
    NSString * _spokenName;
    GEOStructuredAddress * _spokenStructuredAddress;
    GEOTimezone * _timezone;
    int  _type;
    long long  _uID;
    PBUnknownFields * _unknownFields;
}

@property (nonatomic, readwrite, retain) GEOAddress *address;
@property (nonatomic, readwrite) int addressGeocodeAccuracy;
@property (nonatomic, readwrite) double area;
@property (nonatomic, readwrite, retain) NSMutableArray *business;
@property (nonatomic, readwrite, retain) GEOLatLng *center;
@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (nonatomic, readwrite, retain) GEOMapRegion *displayMapRegion;
@property (nonatomic, readwrite, retain) NSMutableArray *entryPoints;
@property (nonatomic, readonly) GEOBusiness *firstBusiness;
@property (nonatomic, readwrite) long long geoId;
@property (nonatomic, readonly) BOOL hasAddress;
@property (nonatomic, readwrite) BOOL hasAddressGeocodeAccuracy;
@property (nonatomic, readwrite) BOOL hasArea;
@property (nonatomic, readonly) BOOL hasCenter;
@property (nonatomic, readonly) BOOL hasDisplayMapRegion;
@property (nonatomic, readwrite) BOOL hasGeoId;
@property (nonatomic, readwrite) BOOL hasIsDisputed;
@property (nonatomic, readwrite) BOOL hasLocalSearchProviderID;
@property (nonatomic, readonly) BOOL hasMapRegion;
@property (nonatomic, readonly) BOOL hasName;
@property (nonatomic, readonly) BOOL hasPhoneticAddress;
@property (nonatomic, readonly) BOOL hasPhoneticLocaleIdentifier;
@property (nonatomic, readonly) BOOL hasPhoneticName;
@property (nonatomic, readwrite) BOOL hasReferenceFrame;
@property (nonatomic, readonly) BOOL hasSpokenAddress;
@property (nonatomic, readonly) BOOL hasSpokenName;
@property (nonatomic, readonly) BOOL hasSpokenStructuredAddress;
@property (nonatomic, readonly) BOOL hasTimezone;
@property (nonatomic, readwrite) BOOL hasType;
@property (nonatomic, readwrite) BOOL hasUID;
@property (atomic, readonly) unsigned long long hash;
@property (nonatomic, readwrite) BOOL isDisputed;
@property (nonatomic, readwrite) int localSearchProviderID;
@property (nonatomic, readwrite, retain) GEOMapRegion *mapRegion;
@property (nonatomic, readwrite, retain) NSString *name;
@property (nonatomic, readwrite, retain) GEOAddress *phoneticAddress;
@property (nonatomic, readwrite, retain) NSString *phoneticLocaleIdentifier;
@property (nonatomic, readwrite, retain) NSString *phoneticName;
@property (nonatomic, readwrite) int referenceFrame;
@property (nonatomic, readwrite, retain) NSMutableArray *roadAccessPoints;
@property (nonatomic, readwrite, retain) NSString *spokenAddress;
@property (nonatomic, readwrite, retain) NSString *spokenName;
@property (nonatomic, readwrite, retain) GEOStructuredAddress *spokenStructuredAddress;
@property (atomic, readonly) Class superclass;
@property (nonatomic, readwrite, retain) GEOTimezone *timezone;
@property (nonatomic, readwrite) int type;
@property (nonatomic, readwrite) long long uID;
@property (nonatomic, readonly) PBUnknownFields *unknownFields;

// Image: /System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/GeoServices

+ (Class)businessType;
+ (Class)entryPointType;
+ (Class)roadAccessPointsType;

- (void).cxx_destruct;
- (int)StringAsAddressGeocodeAccuracy:(id)arg1;
- (int)StringAsType:(id)arg1;
- (void)addBusiness:(id)arg1;
- (void)addEntryPoint:(id)arg1;
- (void)addRoadAccessPoints:(id)arg1;
- (id)address;
- (int)addressGeocodeAccuracy;
- (id)addressGeocodeAccuracyAsString:(int)arg1;
- (double)area;
- (id)business;
- (id)businessAtIndex:(unsigned long long)arg1;
- (unsigned long long)businessCount;
- (id)center;
- (void)clearBusiness;
- (void)clearEntryPoints;
- (void)clearRoadAccessPoints;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (id)displayMapRegion;
- (id)entryPointAtIndex:(unsigned long long)arg1;
- (id)entryPoints;
- (unsigned long long)entryPointsCount;
- (long long)geoId;
- (BOOL)hasAddress;
- (BOOL)hasAddressGeocodeAccuracy;
- (BOOL)hasArea;
- (BOOL)hasCenter;
- (BOOL)hasDisplayMapRegion;
- (BOOL)hasGeoId;
- (BOOL)hasIsDisputed;
- (BOOL)hasLocalSearchProviderID;
- (BOOL)hasMapRegion;
- (BOOL)hasName;
- (BOOL)hasPhoneticAddress;
- (BOOL)hasPhoneticName;
- (BOOL)hasSpokenAddress;
- (BOOL)hasSpokenName;
- (BOOL)hasSpokenStructuredAddress;
- (BOOL)hasTimezone;
- (BOOL)hasType;
- (BOOL)hasUID;
- (unsigned long long)hash;
- (BOOL)isDisputed;
- (BOOL)isEqual:(id)arg1;
- (int)localSearchProviderID;
- (id)mapRegion;
- (void)mergeFrom:(id)arg1;
- (id)name;
- (id)phoneticAddress;
- (id)phoneticName;
- (BOOL)readFrom:(id)arg1;
- (id)roadAccessPoints;
- (id)roadAccessPointsAtIndex:(unsigned long long)arg1;
- (unsigned long long)roadAccessPointsCount;
- (void)setAddress:(id)arg1;
- (void)setAddressGeocodeAccuracy:(int)arg1;
- (void)setArea:(double)arg1;
- (void)setBusiness:(id)arg1;
- (void)setCenter:(id)arg1;
- (void)setDisplayMapRegion:(id)arg1;
- (void)setEntryPoints:(id)arg1;
- (void)setGeoId:(long long)arg1;
- (void)setHasAddressGeocodeAccuracy:(BOOL)arg1;
- (void)setHasArea:(BOOL)arg1;
- (void)setHasGeoId:(BOOL)arg1;
- (void)setHasIsDisputed:(BOOL)arg1;
- (void)setHasLocalSearchProviderID:(BOOL)arg1;
- (void)setHasType:(BOOL)arg1;
- (void)setHasUID:(BOOL)arg1;
- (void)setIsDisputed:(BOOL)arg1;
- (void)setLocalSearchProviderID:(int)arg1;
- (void)setMapRegion:(id)arg1;
- (void)setName:(id)arg1;
- (void)setPhoneticAddress:(id)arg1;
- (void)setPhoneticName:(id)arg1;
- (void)setRoadAccessPoints:(id)arg1;
- (void)setSpokenAddress:(id)arg1;
- (void)setSpokenName:(id)arg1;
- (void)setSpokenStructuredAddress:(id)arg1;
- (void)setTimezone:(id)arg1;
- (void)setType:(int)arg1;
- (void)setUID:(long long)arg1;
- (id)spokenAddress;
- (id)spokenName;
- (id)spokenStructuredAddress;
- (id)timezone;
- (int)type;
- (id)typeAsString:(int)arg1;
- (long long)uID;
- (id)unknownFields;
- (void)writeTo:(id)arg1;

// GEOPlace (AdditionalPlaceInfoExtras)

- (id)initWithName:(id)arg1 placeType:(int)arg2 areaInMeters:(double)arg3;

// GEOPlace (GEOClientGeo3Extension)

- (int)StringAsReferenceFrame:(id)arg1;
- (BOOL)hasPhoneticLocaleIdentifier;
- (BOOL)hasReferenceFrame;
- (id)phoneticLocaleIdentifier;
- (int)referenceFrame;
- (id)referenceFrameAsString:(int)arg1;
- (void)setHasReferenceFrame:(BOOL)arg1;
- (void)setPhoneticLocaleIdentifier:(id)arg1;
- (void)setReferenceFrame:(int)arg1;

// GEOPlace (GEOMapItemAssistantLegacy)

- (id)initWithLocation:(id)arg1 addressDictionary:(id)arg2 name:(id)arg3 businessURL:(id)arg4 phoneNumber:(id)arg5 muid:(unsigned long long)arg6 attributionID:(id)arg7 sampleSizeForUserRatingScore:(unsigned int)arg8 normalizedUserRatingScore:(float)arg9;

// GEOPlace (GEOMapItemExtras)

- (id)geoMapItem;

// GEOPlace (GEOProtoExtras)

- (id)addressDictionary;
- (id)arrivalMapRegion;
- (id)arrivalMapRegionForTransportType:(int)arg1;
- (id)bestName;
- (struct { double x1; double x2; })coordinate;
- (id)firstBusiness;
- (id)initWithLatitude:(double)arg1 longitude:(double)arg2;
- (id)initWithLatitude:(double)arg1 longitude:(double)arg2 addressDictionary:(id)arg3;
- (double)radialDistance;
- (void)setCenterCoordinate:(struct { double x1; double x2; })arg1;
- (void)setNSTimeZone:(id)arg1;

// GEOPlace (GEOURLExtras)

+ (id)_placesFromDirectionsAction:(id)arg1 hasCurrentLocation:(BOOL*)arg2 currentLocationIndex:(unsigned long long*)arg3 options:(id*)arg4;
+ (id)_placesFromPresentAction:(id)arg1 hasCurrentLocation:(BOOL*)arg2 currentLocationIndex:(unsigned long long*)arg3 options:(id*)arg4;
+ (id)_placesFromShowAction:(id)arg1 hasCurrentLocation:(BOOL*)arg2 currentLocationIndex:(unsigned long long*)arg3 options:(id*)arg4;
+ (id)_placesFromURL:(id)arg1 hasCurrentLocation:(BOOL*)arg2 currentLocationIndex:(unsigned long long*)arg3 options:(id*)arg4;
+ (id)_urlForAction:(id)arg1 rison:(id)arg2;
+ (id)_urlForDirectionsFromOrigin:(id)arg1 toDestination:(id)arg2 options:(id)arg3;
+ (id)_urlRepresentationForCurrentLocation;
+ (id)_urlToShowCurrentLocationAndPlaces:(id)arg1 currentLocationIndex:(unsigned long long)arg2 options:(id)arg3;
+ (id)_urlToShowCurrentLocationWithOptions:(id)arg1;
+ (id)_urlToShowPlaces:(id)arg1 options:(id)arg2;
+ (id)_urlToShowURLRepresentations:(id)arg1 options:(id)arg2;

- (BOOL)_isEquivalentURLRepresentationTo:(id)arg1;
- (id)_urlForDirectionsFromCurrentLocationWithOptions:(id)arg1;
- (id)_urlForDirectionsFromPlace:(id)arg1 options:(id)arg2;
- (id)_urlForDirectionsToCurrentLocationWithOptions:(id)arg1;
- (id)_urlForDirectionsToPlace:(id)arg1 options:(id)arg2;
- (id)_urlToShowWithOptions:(id)arg1;
- (id)initWithUrlRepresentation:(id)arg1;
- (id)urlRepresentation;

// GEOPlace (PlaceDataExtras)

+ (id)placeForPlaceData:(id)arg1;

- (id)initWithPlaceInfo:(id)arg1 entity:(id)arg2 addressObject:(id)arg3 bounds:(id)arg4 roadAccessInfo:(id)arg5;

// Image: /System/Library/Frameworks/MapKit.framework/Versions/A/MapKit

// GEOPlace (MKMapItemAdditions)

- (id)clLocation;
- (id)clRegion;
- (id)initWithCLLocation:(id)arg1;
- (id)initWithPlacemark:(id)arg1;

@end
