/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/GeoServices
 */

@interface GEOPDFilterElementInfo : PBCodable <NSCopying> {
    NSMutableArray * _filterIds;
    GEOPDVenueLabel * _label;
    PBUnknownFields * _unknownFields;
}

@property (nonatomic, readwrite, retain) NSMutableArray *filterIds;
@property (nonatomic, readonly) BOOL hasLabel;
@property (nonatomic, readwrite, retain) GEOPDVenueLabel *label;
@property (nonatomic, readonly) PBUnknownFields *unknownFields;

+ (Class)filterIdType;

- (void).cxx_destruct;
- (void)addFilterId:(id)arg1;
- (void)clearFilterIds;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (id)filterIdAtIndex:(unsigned long long)arg1;
- (id)filterIds;
- (unsigned long long)filterIdsCount;
- (BOOL)hasLabel;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)label;
- (void)mergeFrom:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)setFilterIds:(id)arg1;
- (void)setLabel:(id)arg1;
- (id)unknownFields;
- (void)writeTo:(id)arg1;

@end
