/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/GeoServices
 */

@interface GEORPProblemStatusRequest : PBRequest <NSCopying> {
    GEOABSecondPartyPlaceRequestClientMetaData * _abAssignmentMetadata;
    GEOPDAnalyticMetadata * _analyticMetadata;
    GEORPClientCapabilities * _clientCapabilities;
    NSMutableArray * _problemIds;
    GEOServicesState * _servicesState;
    NSString * _statusNotificationId;
    GEORPUserCredentials * _userCredentials;
}

@property (nonatomic, readwrite, retain) GEOABSecondPartyPlaceRequestClientMetaData *abAssignmentMetadata;
@property (nonatomic, readwrite, retain) GEOPDAnalyticMetadata *analyticMetadata;
@property (nonatomic, readwrite, retain) GEORPClientCapabilities *clientCapabilities;
@property (nonatomic, readonly) BOOL hasAbAssignmentMetadata;
@property (nonatomic, readonly) BOOL hasAnalyticMetadata;
@property (nonatomic, readonly) BOOL hasClientCapabilities;
@property (nonatomic, readonly) BOOL hasServicesState;
@property (nonatomic, readonly) BOOL hasStatusNotificationId;
@property (nonatomic, readonly) BOOL hasUserCredentials;
@property (nonatomic, readwrite, retain) NSMutableArray *problemIds;
@property (nonatomic, readwrite, retain) GEOServicesState *servicesState;
@property (nonatomic, readwrite, retain) NSString *statusNotificationId;
@property (nonatomic, readwrite, retain) GEORPUserCredentials *userCredentials;

+ (Class)problemIdType;

- (void).cxx_destruct;
- (id)abAssignmentMetadata;
- (void)addProblemId:(id)arg1;
- (id)analyticMetadata;
- (void)clearProblemIds;
- (id)clientCapabilities;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (BOOL)hasAbAssignmentMetadata;
- (BOOL)hasAnalyticMetadata;
- (BOOL)hasClientCapabilities;
- (BOOL)hasServicesState;
- (BOOL)hasStatusNotificationId;
- (BOOL)hasUserCredentials;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (id)problemIdAtIndex:(unsigned long long)arg1;
- (id)problemIds;
- (unsigned long long)problemIdsCount;
- (BOOL)readFrom:(id)arg1;
- (unsigned int)requestTypeCode;
- (Class)responseClass;
- (id)servicesState;
- (void)setAbAssignmentMetadata:(id)arg1;
- (void)setAnalyticMetadata:(id)arg1;
- (void)setClientCapabilities:(id)arg1;
- (void)setProblemIds:(id)arg1;
- (void)setServicesState:(id)arg1;
- (void)setStatusNotificationId:(id)arg1;
- (void)setUserCredentials:(id)arg1;
- (id)statusNotificationId;
- (id)userCredentials;
- (void)writeTo:(id)arg1;

// GEORPProblemStatusRequest (GEORPProtoExtras)

- (void)populateAnalyticsMetadata;

@end
