/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/GeoServices
 */

@interface GEOTransitSurchargeUnit : PBCodable <NSCopying> {
    GEOTransitPrice * _price;
}

@property (nonatomic, readonly) BOOL hasPrice;
@property (nonatomic, readwrite, retain) GEOTransitPrice *price;

- (void).cxx_destruct;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (BOOL)hasPrice;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (id)price;
- (BOOL)readFrom:(id)arg1;
- (void)setPrice:(id)arg1;
- (void)writeTo:(id)arg1;

@end
