/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/GeoServices
 */

@interface GEOToolLocalProxy : NSObject <GEOToolProxy>

- (id)getDefault:(id)arg1;
- (void)lockDBs;
- (void)resetMapDataExtension;
- (void)unlockDBs;

@end
