/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface _NSDisplayTiming : NSDisplayTiming {
    double  _displayOffset;
    double  _interval;
    double  _submissionLatency;
}

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (double)displayTimeStampAfterTimeStamp:(double)arg1;
- (double)displayTimeStampBeforeTimeStamp:(double)arg1;
- (double)displayTimeStampForSubmissionTimeStamp:(double)arg1;
- (unsigned long long)hash;
- (id)initWithDisplayOffset:(double)arg1 interval:(double)arg2 submissionLatency:(double)arg3;
- (id)initWithHostTime:(unsigned long long)arg1 interval:(unsigned long long)arg2;
- (BOOL)isEqual:(id)arg1;
- (double)submissionTimeStampAfterTimeStamp:(double)arg1;
- (double)submissionTimeStampBeforeTimeStamp:(double)arg1;
- (double)submissionTimeStampForDisplayTimeStamp:(double)arg1;

@end
