/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface _NSScrollingConcurrentConstantData : NSData {
    struct CGAffineTransform { 
        double a; 
        double b; 
        double c; 
        double d; 
        double tx; 
        double ty; 
    }  affineTransformToClipView;
    BOOL  allowsHorizontalStretching;
    BOOL  allowsVerticalStretching;
    CALayer * clipLayer;
    NSClipView * clipView;
    double  decelerationRate;
    CALayer * documentLayer;
    NSString * documentPerfCategory;
    NSView * documentView;
    BOOL  doesDelegateRespondToSynchLayers;
    BOOL  hasSwipeForwardingResponder;
    CALayer * headerClipLayer;
    NSClipView * headerClipView;
    struct CGPoint { 
        double x; 
        double y; 
    }  initialClipOrigin;
    struct CGSize { 
        double width; 
        double height; 
    }  initialClipSize;
    struct NSEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    }  initialContentInsets;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  initialDocumentFrame;
    struct CGPoint { 
        double x; 
        double y; 
    }  initialOriginConstraintLoc;
    struct CGSize { 
        double width; 
        double height; 
    }  initialStretchAmount;
    BOOL  isClipViewFlipped;
    BOOL  isDocumentLayerInclusive;
    NSArray * pageAlignmentsHorizontal;
    NSArray * pageAlignmentsVertical;
    struct CGSize { 
        double width; 
        double height; 
    }  pointsPerPixel;
    NSScrollView * scrollView;
    <NSScrollViewDelegate> * scrollViewDelegate;
    unsigned long long  scrollingModeHorizontal;
    unsigned long long  scrollingModeVertical;
    NSArray * synchronizedSiblingsHorizontal;
    NSArray * synchronizedSiblingsVertical;
    BOOL  usePredominantAxisScrolling;
    NSWindow * window;
}

@property (nonatomic, readwrite) struct CGAffineTransform { double x1; double x2; double x3; double x4; double x5; double x6; } affineTransformToClipView;
@property (nonatomic, readwrite) BOOL allowsHorizontalStretching;
@property (nonatomic, readwrite) BOOL allowsVerticalStretching;
@property (nonatomic, readwrite, retain) CALayer *clipLayer;
@property (nonatomic, readwrite, retain) NSClipView *clipView;
@property (nonatomic, readwrite) double decelerationRate;
@property (nonatomic, readwrite, retain) CALayer *documentLayer;
@property (nonatomic, readwrite, retain) NSString *documentPerfCategory;
@property (nonatomic, readwrite, retain) NSView *documentView;
@property (nonatomic, readwrite) BOOL doesDelegateRespondToSynchLayers;
@property (nonatomic, readwrite) BOOL hasSwipeForwardingResponder;
@property (nonatomic, readwrite, retain) CALayer *headerClipLayer;
@property (nonatomic, readwrite, retain) NSClipView *headerClipView;
@property (nonatomic, readwrite) struct CGPoint { double x1; double x2; } initialClipOrigin;
@property (nonatomic, readwrite) struct CGSize { double x1; double x2; } initialClipSize;
@property (nonatomic, readwrite) struct NSEdgeInsets { double x1; double x2; double x3; double x4; } initialContentInsets;
@property (nonatomic, readwrite) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } initialDocumentFrame;
@property (nonatomic, readwrite) struct CGPoint { double x1; double x2; } initialOriginConstraintLoc;
@property (nonatomic, readwrite) struct CGSize { double x1; double x2; } initialStretchAmount;
@property (nonatomic, readwrite) BOOL isClipViewFlipped;
@property (nonatomic, readwrite) BOOL isDocumentLayerInclusive;
@property (nonatomic, readwrite, retain) NSArray *pageAlignmentsHorizontal;
@property (nonatomic, readwrite, retain) NSArray *pageAlignmentsVertical;
@property (nonatomic, readwrite) struct CGSize { double x1; double x2; } pointsPerPixel;
@property (nonatomic, readwrite, retain) NSScrollView *scrollView;
@property (nonatomic, readwrite, retain) <NSScrollViewDelegate> *scrollViewDelegate;
@property (nonatomic, readwrite) unsigned long long scrollingModeHorizontal;
@property (nonatomic, readwrite) unsigned long long scrollingModeVertical;
@property (nonatomic, readwrite, retain) NSArray *synchronizedSiblingsHorizontal;
@property (nonatomic, readwrite, retain) NSArray *synchronizedSiblingsVertical;
@property (nonatomic, readwrite) BOOL usePredominantAxisScrolling;
@property (nonatomic, readwrite, retain) NSWindow *window;

+ (id)constantDataWithScrollView:(id)arg1 forwardingAxis:(long long)arg2;

- (struct CGAffineTransform { double x1; double x2; double x3; double x4; double x5; double x6; })affineTransformToClipView;
- (BOOL)allowsHorizontalStretching;
- (BOOL)allowsVerticalStretching;
- (id)clipLayer;
- (id)clipView;
- (void)dealloc;
- (double)decelerationRate;
- (id)documentLayer;
- (id)documentPerfCategory;
- (id)documentView;
- (BOOL)doesDelegateRespondToSynchLayers;
- (BOOL)hasSwipeForwardingResponder;
- (id)headerClipLayer;
- (id)headerClipView;
- (struct CGPoint { double x1; double x2; })initialClipOrigin;
- (struct CGSize { double x1; double x2; })initialClipSize;
- (struct NSEdgeInsets { double x1; double x2; double x3; double x4; })initialContentInsets;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })initialDocumentFrame;
- (struct CGPoint { double x1; double x2; })initialOriginConstraintLoc;
- (struct CGSize { double x1; double x2; })initialStretchAmount;
- (BOOL)isClipViewFlipped;
- (BOOL)isDocumentLayerInclusive;
- (id)pageAlignmentsHorizontal;
- (id)pageAlignmentsVertical;
- (struct CGSize { double x1; double x2; })pointsPerPixel;
- (id)scrollView;
- (id)scrollViewDelegate;
- (unsigned long long)scrollingModeHorizontal;
- (unsigned long long)scrollingModeVertical;
- (void)setAffineTransformToClipView:(struct CGAffineTransform { double x1; double x2; double x3; double x4; double x5; double x6; })arg1;
- (void)setAllowsHorizontalStretching:(BOOL)arg1;
- (void)setAllowsVerticalStretching:(BOOL)arg1;
- (void)setClipLayer:(id)arg1;
- (void)setClipView:(id)arg1;
- (void)setDecelerationRate:(double)arg1;
- (void)setDocumentLayer:(id)arg1;
- (void)setDocumentPerfCategory:(id)arg1;
- (void)setDocumentView:(id)arg1;
- (void)setDoesDelegateRespondToSynchLayers:(BOOL)arg1;
- (void)setHasSwipeForwardingResponder:(BOOL)arg1;
- (void)setHeaderClipLayer:(id)arg1;
- (void)setHeaderClipView:(id)arg1;
- (void)setInitialClipOrigin:(struct CGPoint { double x1; double x2; })arg1;
- (void)setInitialClipSize:(struct CGSize { double x1; double x2; })arg1;
- (void)setInitialContentInsets:(struct NSEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)setInitialDocumentFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setInitialOriginConstraintLoc:(struct CGPoint { double x1; double x2; })arg1;
- (void)setInitialStretchAmount:(struct CGSize { double x1; double x2; })arg1;
- (void)setIsClipViewFlipped:(BOOL)arg1;
- (void)setIsDocumentLayerInclusive:(BOOL)arg1;
- (void)setPageAlignmentsHorizontal:(id)arg1;
- (void)setPageAlignmentsVertical:(id)arg1;
- (void)setPointsPerPixel:(struct CGSize { double x1; double x2; })arg1;
- (void)setScrollView:(id)arg1;
- (void)setScrollViewDelegate:(id)arg1;
- (void)setScrollingModeHorizontal:(unsigned long long)arg1;
- (void)setScrollingModeVertical:(unsigned long long)arg1;
- (void)setSynchronizedSiblingsHorizontal:(id)arg1;
- (void)setSynchronizedSiblingsVertical:(id)arg1;
- (void)setUsePredominantAxisScrolling:(BOOL)arg1;
- (void)setWindow:(id)arg1;
- (id)synchronizedSiblingsHorizontal;
- (id)synchronizedSiblingsVertical;
- (BOOL)usePredominantAxisScrolling;
- (id)window;

@end
