/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface _NSTitleControlCrossFadeAnimation : NSAnimation {
    NSCrossfadeView * crossFadeView;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  endingFrame;
    NSBitmapImageRep * endingSnapshot;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  startingFrame;
    NSBitmapImageRep * startingSnapshot;
    NSView * view;
}

@property (atomic, readwrite) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } endingFrame;
@property (atomic, readwrite, retain) NSBitmapImageRep *endingSnapshot;
@property (atomic, readwrite) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } startingFrame;
@property (atomic, readwrite, retain) NSBitmapImageRep *startingSnapshot;
@property (atomic, readwrite, retain) NSView *view;

- (id)_screen;
- (void)_windowWillStartLiveResize:(id)arg1;
- (void)dealloc;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })endingFrame;
- (id)endingSnapshot;
- (void)invalidate;
- (void)setCurrentProgress:(float)arg1;
- (void)setEndingFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setEndingSnapshot:(id)arg1;
- (void)setStartingFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setStartingSnapshot:(id)arg1;
- (void)setView:(id)arg1;
- (void)startAnimation;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })startingFrame;
- (id)startingSnapshot;
- (id)view;

@end
