/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface _NSToolbarSegmentedViewSegmentProxy : NSAccessibilityReparentingProxy

+ (id)segmentProxyFor:(id)arg1 parent:(id)arg2;

- (id)accessibilityAttributeNames;
- (id)accessibilityDescriptionAttribute;
- (BOOL)accessibilityIsDescriptionAttributeSettable;
- (id)accessibilityPositionAttribute;
- (id)accessibilitySizeAttribute;
- (id)accessibilityTitleAttribute;
- (long long)index;

@end
