/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface NSAccessibilityNotifier : NSObject

+ (void)handleAppTermination:(id)arg1;

@end
