/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface NSArrayDetailBinder : NSObjectDetailBinder {
    struct __arrayDetailBinderFlags { 
        unsigned int _selectsAllWhenSettingContent : 1; 
        unsigned int _usedMultipleSelectionArray : 1; 
        unsigned int _reservedArrayDetailBinder : 30; 
    }  _arrayDetailBinderFlags;
}

+ (id)binderClassesSuperseded;
+ (id)bindingsForObject:(id)arg1;
+ (BOOL)isUsableWithObject:(id)arg1;

- (BOOL)_canGuaranteeOrderOfContentObjects;
- (void)_copyDetailsFromBinder:(id)arg1;
- (BOOL)_handlesSelectAll;
- (void)_init;
- (void)_observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 context:(void*)arg3;
- (id)_optionsForBinding:(id)arg1 specifyOnlyIfDifferentFromDefault:(BOOL)arg2;
- (BOOL)_performArrayBinderOperation:(long long)arg1 singleObject:(id)arg2 multipleObjects:(id)arg3 singleIndex:(unsigned long long)arg4 multipleIndexes:(id)arg5 selectionMode:(int*)arg6;
- (id)_referenceBinding;
- (void)_refreshDetailContentInBackground:(BOOL)arg1;
- (void)_selectAllContent:(id)arg1 inDetailController:(id)arg2;
- (void)_setParameter:(id)arg1 forOption:(id)arg2 withBindingInfo:(id)arg3;
- (BOOL)addObjectToMasterArrayRelationship:(id)arg1 selectionMode:(int*)arg2;
- (BOOL)addObjectsToMasterArrayRelationship:(id)arg1 selectionMode:(int*)arg2;
- (id)availableBindings;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (BOOL)insertObjectIntoMasterArrayRelationship:(id)arg1 atIndex:(unsigned long long)arg2 selectionMode:(int*)arg3;
- (BOOL)insertObjectsIntoMasterArrayRelationship:(id)arg1 atIndexes:(id)arg2 selectionMode:(int*)arg3;
- (BOOL)isBindingReadOnly:(id)arg1;
- (void)refreshDetailContent;
- (BOOL)removeObjectFromMasterArrayRelationshipAtIndex:(unsigned long long)arg1 selectionMode:(int*)arg2;
- (BOOL)removeObjectsFromMasterArrayRelationshipAtIndexes:(id)arg1 selectionMode:(int*)arg2;
- (BOOL)selectsAllWhenSettingContent;
- (void)setSelectsAllWhenSettingContent:(BOOL)arg1;

@end
