/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface NSClipView : NSView {
    BOOL  _automaticallyAdjustsContentInsets;
    NSColor * _backgroundColor;
    struct NSEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    }  _contentInsets;
    struct CGSize { 
        double width; 
        double height; 
    }  _contentSize;
    NSCursor * _cursor;
    struct __cvFlags { 
        unsigned int  : 1; 
        unsigned int onlyUncovered : 1; 
        unsigned int reflectScroll : 1; 
        unsigned int usedByCell : 1; 
        unsigned int scrollClipTo : 1; 
        unsigned int noCopyOnScroll : 1; 
        unsigned int drawsBackground : 1; 
        unsigned int scrollInProgress : 1; 
        unsigned int skipRemoveSuperviewCheck : 1; 
        unsigned int animateCurrentScroll : 1; 
        unsigned int canAnimateScrolls : 1; 
        unsigned int nextScrollRelativeToCurrentPosition : 1; 
        unsigned int viewBoundsChangedOverridden : 1; 
        unsigned int viewFrameChangedOverridden : 1; 
        unsigned int documentViewAlignment : 4; 
        unsigned int redrawnWhileScrolling : 1; 
        unsigned int dontConstrainScroll : 1; 
        unsigned int lastAtEdgesState : 4; 
        unsigned int showOverlayScrollersForScrollStep : 1; 
        unsigned int scrollerKnobFlashSpecifier : 2; 
        unsigned int drawsContentShadow : 1; 
        unsigned int dontConstrainBoundsChange : 1; 
        unsigned int isScrollDueToUserAction : 1; 
        unsigned int hasOverlappingViews : 1; 
        unsigned int automaticallyCalculateContentSize : 1; 
    }  _cvFlags;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _docRect;
    NSView * _docView;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _oldDocFrame;
    id  _scrollAnimationHelper;
    struct CGPoint { 
        double x; 
        double y; 
    }  _scrollVelocity;
}

@property (atomic, readwrite) BOOL automaticallyAdjustsContentInsets;
@property (atomic, readwrite, copy) NSColor *backgroundColor;
@property (atomic, readwrite) struct NSEdgeInsets { double x1; double x2; double x3; double x4; } contentInsets;
@property (atomic, readwrite) BOOL copiesOnScroll;
@property (atomic, readwrite, retain) NSCursor *documentCursor;
@property (atomic, readonly) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } documentRect;
@property (atomic, readwrite) NSView *documentView;
@property (atomic, readonly) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } documentVisibleRect;
@property (atomic, readwrite) BOOL drawsBackground;

+ (double)_autoscrollResponseMultiplier;
+ (id)_contentShadow;
+ (void)_setAutoscrollResponseMultiplier:(double)arg1;
+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
+ (id)defaultAnimationForKey:(id)arg1;
+ (void)initialize;
+ (BOOL)isCompatibleWithResponsiveScrolling;
+ (BOOL)requiresConstraintBasedLayout;

- (void)_addOverhangSubviewsIfNeeded;
- (void)_alignCoords;
- (BOOL)_alignOriginOfBoundsRectToBackingIfNeeded:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; }*)arg1;
- (BOOL)_animateCurrentScroll;
- (void)_animatedScrollToPoint:(struct CGPoint { double x1; double x2; })arg1;
- (struct CGPoint { double x1; double x2; })_animatingScrollTargetOrigin;
- (Class)_animatorClass;
- (void)_autoscrollForDraggingInfo:(id)arg1 timeDelta:(double)arg2;
- (unsigned long long)_backgroundFillOperation;
- (BOOL)_canAnimateScrolls;
- (BOOL)_canCopyOnScrollForDeltaX:(double)arg1 deltaY:(double)arg2;
- (BOOL)_canUseTiledBackingLayer;
- (void)_checkAlignmentOfOriginOfBoundsRectIfNeeded:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; }*)arg1;
- (BOOL)_clipViewShouldClipFocusRing;
- (id)_computeBounds;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_constrainBoundsRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_constrainBoundsRectAndAlignIfNeeded:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (struct NSEdgeInsets { double x1; double x2; double x3; double x4; })_convertedContentInsetsToProposedBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)_cuiSourceListBackgroundOptions;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_currentDocViewFrame;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_dirtyRectUncoveredFromOldDocFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 byNewDocFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2;
- (unsigned long long)_documentViewAlignment;
- (void)_drawOverhangShadowsInRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)_drawRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 clip:(BOOL)arg2;
- (void)_drawShadowAroundRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 clipRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2;
- (BOOL)_drawsNothing;
- (BOOL)_drawsOverhangRects;
- (unsigned long long)_effectiveAutoresizingMask;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_effectiveContentFrame;
- (void)_extendNextScrollRelativeToCurrentPosition;
- (BOOL)_forcePixelAlignedClipViewFrame;
- (void)_getOverhangFrames:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)_handleBoundsChangeForSubview:(id)arg1;
- (void)_handleFrameChangeForSubview:(id)arg1;
- (void)_immediateScrollToPoint:(struct CGPoint { double x1; double x2; })arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_insetBounds;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_insetVisibleRect;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_interactiveBounds;
- (void)_invalidateFocusRingIfItBleedsIntoOurBounds;
- (void)_invalidateIntersectionsWithSiblingViews;
- (BOOL)_isAnimatingScroll;
- (BOOL)_isScrollDueToUserAction;
- (BOOL)_isUsedByCell;
- (struct CGPoint { double x1; double x2; })_magnificationAnchorPointForCursorPoint:(struct CGPoint { double x1; double x2; })arg1;
- (id)_markUsedByCell;
- (struct CGSize { double x1; double x2; })_minimumFrameSize;
- (BOOL)_needsClipViewAncestorDidScroll;
- (id)_newShadowOfSize:(struct CGSize { double x1; double x2; })arg1 fromOffset:(struct CGPoint { double x1; double x2; })arg2 inImage:(id)arg3;
- (id)_overhangSubviews;
- (void)_pinDocRect;
- (struct CGPoint { double x1; double x2; })_pixelAlignProposedScrollPosition:(struct CGPoint { double x1; double x2; })arg1;
- (BOOL)_proposedScrollPositionIsPixelAligned:(struct CGPoint { double x1; double x2; })arg1;
- (void)_recursiveGainedLayerTreeHostAncestor;
- (void)_recursiveLostLayerTreeHostAncestor;
- (void)_reflectDocumentViewBoundsChange;
- (void)_reflectDocumentViewFrameChange;
- (void)_registerForDocViewFrameAndBoundsChangeNotifications;
- (void)_removeOverhangSubviewsIfNeeded;
- (double)_scrollAmountForLineScroll:(double)arg1 percentageTowardsMax:(double)arg2 limitingSize:(double)arg3 multiplier:(double)arg4;
- (BOOL)_scrollInProgress;
- (void)_scrollPoint:(const struct CGPoint { double x1; double x2; }*)arg1 fromView:(id)arg2;
- (BOOL)_scrollRectToVisible:(const struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; }*)arg1 fromView:(id)arg2;
- (BOOL)_scrollRectToVisible:(const struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; }*)arg1 fromView:(id)arg2 animateScroll:(long long)arg3 flashScrollerKnobs:(unsigned long long)arg4;
- (BOOL)_scrollTo:(const struct CGPoint { double x1; double x2; }*)arg1;
- (BOOL)_scrollTo:(const struct CGPoint { double x1; double x2; }*)arg1 animate:(BOOL)arg2;
- (BOOL)_scrollTo:(const struct CGPoint { double x1; double x2; }*)arg1 animateScroll:(long long)arg2 flashScrollerKnobs:(unsigned long long)arg3;
- (void)_selfBoundsChanged;
- (void)_setAnimateCurrentScroll:(BOOL)arg1;
- (void)_setAnimationCompletionHandler:(id)arg1;
- (void)_setCanAnimateScrolls:(BOOL)arg1;
- (void)_setDocViewFromRead:(id)arg1;
- (void)_setDocumentViewAlignment:(unsigned long long)arg1;
- (void)_setDontConstrainBoundsChange:(BOOL)arg1;
- (void)_setDontConstrainScroll:(BOOL)arg1;
- (void)_setHasOverlappingViews:(BOOL)arg1;
- (void)_setIsScrollDueToUserAction:(BOOL)arg1;
- (void)_setNeedsDisplayInOverhang:(BOOL)arg1;
- (void)_setOverhangSubviews:(id)arg1;
- (void)_setSuperview:(id)arg1;
- (BOOL)_shouldAdjustPatternPhase;
- (BOOL)_shouldAutoscrollForDraggingInfo:(id)arg1;
- (BOOL)_shouldDontConstrainScroll;
- (BOOL)_shouldRedisplayOnChanges;
- (BOOL)_shouldShowOverlayScrollersForScrollToPoint:(struct CGPoint { double x1; double x2; })arg1;
- (void)_unregisterForDocViewFrameAndBoundsChangeNotifications;
- (void)_updateOverhangSubviewsIfNeeded;
- (BOOL)acceptsFirstResponder;
- (BOOL)automaticallyAdjustsContentInsets;
- (BOOL)automaticallyCalculatesContentSize;
- (BOOL)autoscroll:(id)arg1;
- (id)backgroundColor;
- (BOOL)becomeFirstResponder;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })constrainBoundsRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (struct CGPoint { double x1; double x2; })constrainScrollPoint:(struct CGPoint { double x1; double x2; })arg1;
- (struct NSEdgeInsets { double x1; double x2; double x3; double x4; })contentInset;
- (struct NSEdgeInsets { double x1; double x2; double x3; double x4; })contentInsets;
- (struct CGSize { double x1; double x2; })contentSize;
- (BOOL)copiesOnScroll;
- (void)dealloc;
- (id)documentCursor;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })documentRect;
- (id)documentView;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })documentVisibleRect;
- (void)drawRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (BOOL)drawsBackground;
- (BOOL)drawsContentShadow;
- (void)encodeWithCoder:(id)arg1;
- (id)hitTest:(struct CGPoint { double x1; double x2; })arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (BOOL)isFlipped;
- (BOOL)isOpaque;
- (id)makeBackingLayer;
- (BOOL)needsPanelToBecomeKey;
- (BOOL)preservesContentDuringLiveResize;
- (void)resetCursorRects;
- (void)rotateByAngle:(double)arg1;
- (void)scaleUnitSquareToSize:(struct CGSize { double x1; double x2; })arg1;
- (void)scrollToPoint:(struct CGPoint { double x1; double x2; })arg1;
- (struct CGPoint { double x1; double x2; })scrollVelocity;
- (void)setAutomaticallyAdjustsContentInsets:(BOOL)arg1;
- (void)setAutomaticallyCalculatesContentSize:(BOOL)arg1;
- (void)setBackgroundColor:(id)arg1;
- (void)setBoundsOrigin:(struct CGPoint { double x1; double x2; })arg1;
- (void)setBoundsRotation:(double)arg1;
- (void)setBoundsSize:(struct CGSize { double x1; double x2; })arg1;
- (void)setContentInset:(struct NSEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)setContentInsets:(struct NSEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)setContentSize:(struct CGSize { double x1; double x2; })arg1;
- (void)setCopiesOnScroll:(BOOL)arg1;
- (void)setDocumentCursor:(id)arg1;
- (void)setDocumentView:(id)arg1;
- (void)setDrawsBackground:(BOOL)arg1;
- (void)setDrawsContentShadow:(BOOL)arg1;
- (void)setFrameOrigin:(struct CGPoint { double x1; double x2; })arg1;
- (void)setFrameRotation:(double)arg1;
- (void)setFrameSize:(struct CGSize { double x1; double x2; })arg1;
- (void)setLayer:(id)arg1;
- (void)setNextKeyView:(id)arg1;
- (void)setScrollVelocity:(struct CGPoint { double x1; double x2; })arg1;
- (void)setUpGState;
- (void)setValue:(id)arg1 forKeyPath:(id)arg2;
- (void)translateOriginToPoint:(struct CGPoint { double x1; double x2; })arg1;
- (void)updateConstraints;
- (void)updateLayer;
- (id)valueForKey:(id)arg1;
- (void)viewBoundsChanged:(id)arg1;
- (void)viewFrameChanged:(id)arg1;
- (BOOL)wantsUpdateLayer;
- (void)willRemoveSubview:(id)arg1;

// NSClipView (IBWorkaround14284306)

- (BOOL)ibHasResolved14284306;
- (id)ibShadowedSubviews;

@end
