/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface NSFilePromiseReceiver : NSObject <NSPasteboardReading> {
    NSArray * _fileNames;
    NSArray * _fileTypes;
    NSArray * _fileURLs;
    struct { 
        unsigned int usesFileCoordination : 1; 
        unsigned int registered : 1; 
        unsigned int reserved : 30; 
    }  _flags;
    NSOperationQueue * _operationQueue;
    NSPasteboard * _pasteboard;
    NSPasteboardItem * _pasteboardItem;
    id  _private;
    long long  _promiseType;
    id  _readerBlock;
    NSArray * _reservedA;
}

@property (atomic, readonly, copy) NSArray *alternateFileTypes;
@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (atomic, readonly, copy) NSArray *fileNames;
@property (atomic, readonly, copy) NSArray *fileTypes;
@property (atomic, readonly) unsigned long long hash;
@property (atomic, readonly) Class superclass;

+ (id)acceptableDragTypes;
+ (id)readableDraggedTypes;
+ (id)readableTypesForPasteboard:(id)arg1;
+ (unsigned long long)readingOptionsForType:(id)arg1 pasteboard:(id)arg2;

- (void)_setPasteboard:(id)arg1;
- (void)_setPasteboardItem:(id)arg1;
- (id)alternateFileTypes;
- (void)dealloc;
- (void)draggingCancelled:(id)arg1;
- (void)draggingEnded:(id)arg1;
- (id)fileNames;
- (id)fileTypes;
- (id)initWithPasteboardPropertyList:(id)arg1 ofType:(id)arg2;
- (BOOL)providerIsUsingFileCoordination;
- (void)receivePromisedFilesAtDestination:(id)arg1 options:(id)arg2 operationQueue:(id)arg3 reader:(id)arg4;
- (void)registerDesinationLocation:(id)arg1 options:(id)arg2 operationQueu:(id)arg3 reader:(id)arg4;
- (void)registerDestinationLocation:(id)arg1 options:(id)arg2 operationQueue:(id)arg3 reader:(id)arg4;

@end
