/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface NSNavFileListDelegate : NSObject {
    NSMutableArray * _currentBrowsingNodePath;
    NSNavDataSource * _dataSource;
    NSArray * _delayShowNodeInfo;
}

@property (nonatomic, readonly) NSNavDataSource *dataSource;

- (BOOL)_canGoIntoSelectedDirectoryAndTry:(BOOL)arg1;
- (void)_delayedShowNode:(id)arg1;
- (id)_doTypeSelectNodeInDirectory:(id)arg1 withSearchString:(id)arg2 visitedNodes:(id)arg3 expandedNodesToVisit:(id)arg4 recursively:(BOOL)arg5;
- (void)_releaseDelayShowNodeInfo;
- (id)_showNodeInDirectory:(id)arg1 withDisplayNamePrefix:(id)arg2 selectIfEnabled:(BOOL)arg3 caseSensitiveCompare:(BOOL)arg4;
- (BOOL)_tryUserMoveToParentNode;
- (id)alwaysShowNode:(id)arg1 inDirectory:(id)arg2 selectIfEnabled:(BOOL)arg3;
- (void)beginUpdates;
- (BOOL)canChooseNode:(id)arg1;
- (BOOL)canGoIntoSelectedDirectory;
- (BOOL)canHighlightNode:(id)arg1;
- (void)changeDirectoryForGoIntoNode:(id)arg1;
- (id)currentBrowsingNodePath;
- (id)currentTypeSelectSearchString;
- (id)dataSource;
- (void)dealloc;
- (void)endUpdates;
- (void)getSnapToWidthList:(const double**)arg1 snapRadiusList:(const double**)arg2 count:(long long*)arg3;
- (BOOL)handleGoIntoSelectedDirectory;
- (BOOL)handleKeyboardShortcutWithEvent:(id)arg1;
- (void)handleUserGoUpDirectory;
- (id)initWithDataSource:(id)arg1;
- (void)insertItemsAtIndexes:(id)arg1 inParent:(id)arg2;
- (double)minimumWidth;
- (void)moveItemAtIndex:(long long)arg1 inParent:(id)arg2 toIndex:(long long)arg3 inParent:(id)arg4;
- (BOOL)oldWrongCanChooseNode:(id)arg1;
- (void)reloadChildrenForNode:(id)arg1;
- (void)reloadDisplayState;
- (long long)rememberedSnapToIndex;
- (void)removeItemsAtIndexes:(id)arg1 inParent:(id)arg2;
- (void)setRememberedSnapToIndex:(long long)arg1;
- (void)showNodeInCurrentDirectoryWithDisplayNamePrefix:(id)arg1 selectIfEnabled:(BOOL)arg2;
- (void)showNodeInCurrentDirectoryWithFilename:(id)arg1 selectIfEnabled:(BOOL)arg2;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })sourceFrameOnScreenForNavNode:(id)arg1;
- (void)storeCurrentBrowsingNodePath:(id)arg1;
- (id)transitionImageForNavNode:(id)arg1;
- (void)updateCurrentBrowsingNodePathWithCurrentDirectoryNode:(id)arg1;
- (id)validSelectedNodesIncludingDirectory;
- (id)view;
- (void)windowOrderedOut;

// NSNavFileListDelegate (NSNavFileListDelegateOptionalOverrides)

- (void)concludeReloadChildrenForNode:(id)arg1;
- (void)configureForActiveState;
- (void)configureForAllowsExpandingMultipleDirectories:(BOOL)arg1;
- (void)configureForAllowsMultipleSelection:(BOOL)arg1;
- (void)configureForCalculatesAllSizes:(BOOL)arg1;
- (void)configureForCanChooseDirectories:(BOOL)arg1;
- (void)configureForCanChooseFiles:(BOOL)arg1;
- (void)configureForCanClickDisabledFiles:(BOOL)arg1;
- (void)configureForDisplayedFileProperties:(id)arg1;
- (void)configureForInactiveState;
- (void)configureForSortedByFileProperty:(id)arg1 ascending:(BOOL)arg2 caseSensitive:(BOOL)arg3;
- (void)configureForTreatsDirectoryAliasesAsDirectories:(BOOL)arg1;
- (void)configureForTreatsFilePackagesAsDirectories:(BOOL)arg1;
- (BOOL)lightweightHandleChildChanged:(id)arg1 parent:(id)arg2 property:(id)arg3;
- (void)prepareForReloadChildrenForNode:(id)arg1;
- (BOOL)supportsSortingByFileProperties;

@end
