/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface NSNavNodePreviewHelper : NSObject {
    NSImage * _cachedPreviewThumbnailImage;
    unsigned int  _computingThumbnailInDetatchedThread;
    id  _delegate;
    unsigned int  _lookedupPreviewThumbnailImage;
    NSNavNode * _node;
    unsigned int  _reserved;
}

+ (void)_computeThumbnailImageInSubthreadFor:(id)arg1;
+ (void)_subthreadComputePreviewThumbnailImages;

- (BOOL)_backgroundDataCancelled;
- (void)_mainthreadComputePreviewThumbnailFinished:(id)arg1;
- (void)dealloc;
- (id)delegate;
- (void)handlePreviewImageChanged;
- (id)initWithNode:(id)arg1 delegate:(id)arg2;
- (id)node;
- (BOOL)previewImageShouldHaveIconModeThumbnail;
- (struct CGSize { double x1; double x2; })previewSize;
- (id)previewThumbnailImage;
- (void)setDelegate:(id)arg1;

@end
