/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface NSScrollAnimationHelper : NSAnimationHelper {
    id  _completionHandler;
    id  _delegate;
    struct CGPoint { 
        double x; 
        double y; 
    }  _endPoint;
    struct __sahFlags { 
        unsigned int logPerformanceAnalysis : 1; 
        unsigned int logPerformanceAnalysisInProgress : 1; 
        unsigned int isScrollDueToUserAction : 1; 
        unsigned int delegateRespondsTo_setIsScrollDueToUserAction; 
        unsigned int RESERVED : 28; 
    }  _sahFlags;
    struct CGPoint { 
        double x; 
        double y; 
    }  _startPoint;
    struct CGPoint { 
        double x; 
        double y; 
    }  _totalDelta;
}

@property (atomic, readwrite, copy) id completionHandler;

- (struct CGPoint { double x1; double x2; })_currentPoint;
- (void)_doAnimationStep;
- (void)_doAnimationStepWithProgress:(double)arg1;
- (void)_doFinalAnimationStep;
- (void)changeDestinationToPoint:(struct CGPoint { double x1; double x2; })arg1;
- (id)completionHandler;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;
- (void)scrollToPoint:(struct CGPoint { double x1; double x2; })arg1;
- (void)setCompletionHandler:(id)arg1;
- (void)setIsScrollDueToUserAction:(BOOL)arg1;
- (void)setLogPerformanceAnalysis:(BOOL)arg1;
- (struct CGPoint { double x1; double x2; })targetOrigin;

@end
