/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface NSSegmentItemLabelCell : NSTextFieldCell {
    NSString * _widgetName;
}

@property (nonatomic, readwrite, retain) NSString *widgetName;

+ (id)_getParentSegmentedControlViewFromView:(id)arg1;

- (struct __CFString { }*)_coreUIWidgetName;
- (BOOL)_shouldUseStyledTextInView:(id)arg1;
- (void)dealloc;
- (long long)interiorBackgroundStyle;
- (void)setWidgetName:(id)arg1;
- (id)widgetName;

@end
