/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface NSTabAnimation : NSAnimation {
    id  _progressHandler;
}

- (void).cxx_destruct;
- (id)initWithDuration:(double)arg1 animationCurve:(unsigned long long)arg2 progressHandler:(id)arg3;
- (void)setCurrentProgress:(float)arg1;

@end
