/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface NSTextViewCompletionWindow : NSWindow

- (BOOL)accessibilityIsChildOfApp;
- (BOOL)accessibilityIsIgnored;
- (id)accessibilityParentAttribute;
- (BOOL)canBecomeVisibleWithoutLogin;

@end
