/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface NSTrackingInfoImpl : NSObject <NSMenuTrackingInfo> {
    NSMenu * _menu;
    NSMenuItem * _selectedItem;
    NSMenuItem * _targetedItem;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _targetedItemFrame;
}

@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (atomic, readonly) unsigned long long hash;
@property (atomic, readonly) NSMenu *menu;
@property (atomic, readonly) NSMenuItem *selectedItem;
@property (atomic, readonly) Class superclass;
@property (atomic, readonly) NSMenuItem *targetedItem;
@property (atomic, readonly) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } targetedItemFrame;

- (void)dealloc;
- (id)description;
- (id)menu;
- (id)selectedItem;
- (id)targetedItem;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })targetedItemFrame;

@end
