/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 */

@interface CFPDPurgeableBuffer : CFPDDataBuffer {
    unsigned long long  allocSize;
    struct __CFData { } * handle;
    BOOL  safe;
    BOOL  usedMalloc;
}

- (BOOL)beginAccessing;
- (void*)bytes;
- (void)dealloc;
- (void)endAccessing;
- (id)initWithFileDescriptor:(int)arg1 size:(unsigned long long)arg2;
- (id)initWithPropertyList:(void*)arg1;
- (unsigned long long)length;
- (BOOL)purgable;

@end
