/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VectorKit.framework/Versions/A/VectorKit
 */

@interface VKPShield : PBCodable <NSCopying> {
    VKPGenericShieldStyleInfo * _genericShieldStyleInfo;
    NSString * _identifier;
    NSMutableArray * _variants;
}

@property (nonatomic, readwrite, retain) VKPGenericShieldStyleInfo *genericShieldStyleInfo;
@property (nonatomic, readonly) BOOL hasGenericShieldStyleInfo;
@property (nonatomic, readwrite, retain) NSString *identifier;
@property (nonatomic, readwrite, retain) NSMutableArray *variants;

- (void)addVariants:(id)arg1;
- (void)clearVariants;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)description;
- (id)dictionaryRepresentation;
- (id)genericShieldStyleInfo;
- (BOOL)hasGenericShieldStyleInfo;
- (unsigned long long)hash;
- (id)identifier;
- (BOOL)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)setGenericShieldStyleInfo:(id)arg1;
- (void)setIdentifier:(id)arg1;
- (void)setVariants:(id)arg1;
- (id)variants;
- (id)variantsAtIndex:(unsigned long long)arg1;
- (unsigned long long)variantsCount;
- (void)writeTo:(id)arg1;

@end
