/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Metal.framework/Versions/A/Metal
 */

@interface MTLArgument : NSObject

@property (atomic, readonly) unsigned long long access;
@property (getter=isActive, atomic, readonly) BOOL active;
@property (atomic, readonly) unsigned long long bufferAlignment;
@property (atomic, readonly) unsigned long long bufferDataSize;
@property (atomic, readonly) unsigned long long bufferDataType;
@property (atomic, readonly) MTLStructType *bufferStructType;
@property (atomic, readonly) unsigned long long index;
@property (atomic, readonly) BOOL isDepthTexture;
@property (atomic, readonly) NSString *name;
@property (atomic, readonly) unsigned long long textureDataType;
@property (atomic, readonly) unsigned long long textureType;
@property (atomic, readonly) unsigned long long threadgroupMemoryAlignment;
@property (atomic, readonly) unsigned long long threadgroupMemoryDataSize;
@property (atomic, readonly) unsigned long long type;

+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone { }*)arg1;

@end
