/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
 */

@interface _PFEncodedString : _PFString

- (BOOL)_isDeallocating;
- (BOOL)_tryRetain;
- (Class)classForArchiver;
- (Class)classForCoder;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)init;
- (oneway void)release;
- (id)retain;
- (unsigned long long)retainCount;

@end
