/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuartzComposer.framework/Versions/A/QuartzComposer
 */

@interface GFNodeManagerView : NSView {
    NSCell * _defaultDataCell;
    NSString * _filterString;
    NSView * _insideView;
    NSString * _namespace;
    NSMutableArray * _nodeNames;
    NSTableView * _tableView;
    NSTextView * _textView;
    void * _unused;
}

- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)filterString;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)nodeNamespace;
- (void)setFilterString:(id)arg1;
- (void)setNodeNamespace:(id)arg1;

// GFNodeManagerView (Private)

- (void)_addColumnWithIdentifier:(id)arg1 title:(id)arg2 dataCell:(id)arg3 sortable:(BOOL)arg4;
- (id)_cellContentForNode:(id)arg1 columnIdentifier:(id)arg2;
- (id)_columns;
- (long long)_compareNode:(id)arg1 withNode:(id)arg2 usingColumnIdentifier:(id)arg3 ascending:(BOOL)arg4;
- (id)_descriptionForNode:(id)arg1;
- (id)_filterStringsForNode:(id)arg1;
- (void)_finishInitialization;
- (void)_refreshList:(id)arg1;
- (void)_removeAllColumns;
- (void)_removeColumnWithIdentifier:(id)arg1;
- (void)_selectRow:(unsigned long long)arg1;
- (void)_sortByIdentifiers:(id)arg1;
- (void)_tableViewDoubleClick;

// GFNodeManagerView (TableViewSource)

- (long long)numberOfRowsInTableView:(id)arg1;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (void)tableView:(id)arg1 sortDescriptorsDidChange:(id)arg2;
- (BOOL)tableView:(id)arg1 writeRows:(id)arg2 toPasteboard:(id)arg3;
- (void)tableViewSelectionDidChange:(id)arg1;

@end
