/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/ImageKit.framework/Versions/A/ImageKit
 */

@interface IKFilterPreviewView : NSOpenGLView {
    CIContext * _context;
    BOOL  _needsReshape;
    CIImage * checkerBoardImage;
    CIFilter * currentFilter;
    double  currentScale;
    CIImage * defaultImage;
}

+ (id)defaultPixelFormat;

- (id)ciContext;
- (id)currentFilter;
- (void)dealloc;
- (void)drawRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)prepareOpenGL;
- (void)reshape;
- (void)setFilterByName:(id)arg1;
- (void)setImage:(id)arg1;
- (void)setImageByPath:(id)arg1 forKey:(id)arg2;
- (void)updateMatrices;

@end
