/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/ImageKit.framework/Versions/A/ImageKit
 */

@interface IKGLTextSizeCache : NSObject {
    IKGLTextCacheFragHandler * _cacheFragHandler;
    int  _rectCount;
    double  _scaleFactor;
    struct CGSize { 
        double width; 
        double height; 
    }  _size;
    unsigned int  _textureID;
}

- (id)cacheFragHandler;
- (BOOL)canStoreTextWithSize:(struct CGSize { double x1; double x2; })arg1;
- (void)cleanup;
- (void)createTexture;
- (void)dealloc;
- (void)finalize;
- (id)initWithTextureSize:(struct CGSize { double x1; double x2; })arg1 textHeight:(int)arg2 scaleFactor:(double)arg3;
- (BOOL)isEmpty;
- (void)removeText:(id)arg1;
- (void)storeText:(id)arg1;

@end
