/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/ImageKit.framework/Versions/A/ImageKit
 */

@interface IKImageRenderInfo : NSObject {
    unsigned long long  _bitsPerComponent;
    CIContext * _ciContext;
    struct CGColorSpace { } * _contextColorSpace;
    BOOL  _usingSoftwareRenderer;
}

@property (atomic, readwrite) unsigned long long bitsPerComponent;
@property (atomic, readwrite, retain) CIContext *ciContext;
@property (atomic, readwrite) struct CGColorSpace { }*contextColorSpace;
@property (atomic, readwrite) BOOL usingSoftwareRenderer;

- (unsigned long long)bitsPerComponent;
- (id)ciContext;
- (struct CGColorSpace { }*)contextColorSpace;
- (void)dealloc;
- (void)setBitsPerComponent:(unsigned long long)arg1;
- (void)setCiContext:(id)arg1;
- (void)setContextColorSpace:(struct CGColorSpace { }*)arg1;
- (void)setUsingSoftwareRenderer:(BOOL)arg1;
- (BOOL)usingSoftwareRenderer;

@end
