/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/ImageKit.framework/Versions/A/ImageKit
 */

@interface IKMipmapItem : NSObject {
    IKImageWrapper * _image;
    unsigned int  _isReference;
    int  _mipmapSize;
    IKMipmapImage * _parent;
    unsigned int  _sizeIsVarying;
    unsigned int  _thumbnailQuality;
    unsigned int  _vmUsagePolicy;
}

- (id)__image;
- (void)__setDictionaryRepresentation:(id)arg1;
- (void)dealloc;
- (id)description;
- (id)image;
- (id)init;
- (void)integrateReferenceInstance:(id)arg1 replaceImage:(BOOL)arg2;
- (void)invalidate;
- (BOOL)isValid;
- (BOOL)loaded;
- (void)mapIntoVRAM;
- (int)mipmapSize;
- (id)parent;
- (void)referenceWillDie;
- (BOOL)setAsMipmapOfImage:(id)arg1 aspectRatio:(float)arg2 antialiased:(BOOL)arg3 quality:(int)arg4;
- (BOOL)setAsMipmapOfImage:(id)arg1 withSize:(struct CGSize { double x1; double x2; })arg2 antialiased:(BOOL)arg3 quality:(int)arg4;
- (void)setAsReferenceOf:(id)arg1;
- (void)setImage:(id)arg1;
- (void)setIsReference:(BOOL)arg1;
- (void)setMipmapSize:(int)arg1;
- (void)setParent:(id)arg1;
- (void)setSizeIsVarying:(BOOL)arg1;
- (void)setThumbnailQuality:(int)arg1;
- (void)setVmUsagePolicy:(int)arg1;
- (BOOL)sizeIsVarying;
- (int)thumbnailQuality;
- (BOOL)unload;
- (int)vmUsagePolicy;

@end
