/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/ImageKit.framework/Versions/A/ImageKit
 */

@interface IKMultipleSegmentedRawDataBuffer : NSObject {
    unsigned int  _blockSize;
    NSMutableArray * _buffers;
}

- (BOOL)containsAddress:(void*)arg1;
- (void)dealloc;
- (int)estimatedFragmentCount;
- (int)estimatedItemCount;
- (void)freeCache;
- (int)freeSpace;
- (id)initWithMemorySize:(unsigned int)arg1;
- (void*)newSegmentOfSize:(unsigned int)arg1;
- (void)releaseSegment:(void*)arg1 ofSize:(unsigned int)arg2;
- (id)segmentedBufferAtIndex:(int)arg1;
- (id)segmentedBuffers;
- (void)setTotalSpace:(unsigned int)arg1;
- (unsigned int)totalSpace;
- (unsigned int)usedSpace;

@end
