/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/ImageKit.framework/Versions/A/ImageKit
 */

@interface IKNStatusView2 : IKNStatusView

- (void)setStatusText:(id)arg1;

@end
