/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/ImageKit.framework/Versions/A/ImageKit
 */

@interface IKPlaceholderLayer : IKNCustomLayer {
    CALayer * clipLayer;
    CAGradientLayer * gradientLayer;
    CALayer * imageLayer;
    double  progress;
}

@property (atomic, readwrite) double progress;

- (id)init;
- (double)progress;
- (void)setBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setProgress:(double)arg1;
- (void)setup;

@end
