/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/ImageKit.framework/Versions/A/ImageKit
 */

@interface IKViewController : NSViewController {
    BOOL  _isLoaded;
}

@property (atomic, readwrite) BOOL isLoaded;

- (void)didBecomeVisible;
- (void)invalidateContents;
- (BOOL)isLoaded;
- (void)loadView;
- (void)setIsLoaded:(BOOL)arg1;

@end
