/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuartzComposer.framework/Versions/A/QuartzComposer
 */

@interface QCAnchorPosition : QCPatch {
    QCNumberPort * inputHeight;
    QCIndexPort * inputMode;
    QCNumberPort * inputWidth;
    QCNumberPort * inputX;
    QCNumberPort * inputY;
    QCNumberPort * outputX;
    QCNumberPort * outputY;
}

+ (BOOL)allowsSubpatchesWithIdentifier:(id)arg1;
+ (BOOL)isSafe;

- (BOOL)execute:(id)arg1 time:(double)arg2 arguments:(id)arg3;
- (id)initWithIdentifier:(id)arg1;
- (void)receiveMessage:(id)arg1 name:(id)arg2 attributes:(id)arg3;
- (BOOL)setup:(id)arg1;

@end
