/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuartzComposer.framework/Versions/A/QuartzComposer
 */

@interface QCCompositionPickerGridCellLayer : CALayer <CAAction> {
    QCCompositionCellLayer * _QCLayer;
    struct CGColor { } * _cellFocusRingColor;
    struct CGColor { } * _cellSelectedTextColor;
    struct CGColor { } * _cellTextColor;
    id  _controller;
    BOOL  _selected;
    QCPickerSelectionLayer * _selectionLayer;
    CATextLayer * _textLayer;
}

- (void)_finalize_QCCompositionPickerGridCellLayer;
- (void)animateCompositionsIfNeeded;
- (void)cellBackgroundColorDidChange;
- (id)composition;
- (id)compositionLayer;
- (void)dealloc;
- (void)finalize;
- (id)initWithComposition:(id)arg1 controller:(id)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (void)restoreExpandedLayout;
- (void)runActionForKey:(id)arg1 object:(id)arg2 arguments:(id)arg3;
- (BOOL)selected;
- (void)selectionDidChange;
- (void)selectionModeDidChange;
- (void)setCollapsedLayout;
- (void)setSelected:(BOOL)arg1;
- (void)sleep;
- (void)updateLayout;
- (void)wakeup;

@end
