/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuartzComposer.framework/Versions/A/QuartzComposer
 */

@interface QCImageManagerProfileView : QCProfileView {
    QCImageManager * _manager;
    BOOL  _purgeable;
    void * _unused2;
    unsigned long long  _virtualScreen;
}

- (void)_updateProfile;
- (void)addSample:(const double*)arg1;
- (void)dealloc;
- (id)imageManager;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setImageManager:(id)arg1;
- (void)setSampleSize:(unsigned long long)arg1;
- (void)setShowPurgeable:(BOOL)arg1;
- (void)setVirtualScreen:(unsigned long long)arg1;

@end
