/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuartzComposer.framework/Versions/A/QuartzComposer
 */

@interface QCInteractionPort : QCVirtualPort

+ (Class)baseClass;

- (void)_setConnectedPort:(id)arg1;
- (BOOL)acceptValuesOfClass:(Class)arg1;
- (BOOL)canConnectToPort:(id)arg1;
- (BOOL)setStateValue:(id)arg1;
- (id)stateValue;
- (Class)valueClass;

@end
