/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuartzComposer.framework/Versions/A/QuartzComposer
 */

@interface QCMiniPatchActor : QCPatchActor {
    void * _unused3;
}

- (void)_drawBackgroundGradientLayerForNode:(id)arg1 bounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2 reflectionHeight:(double)arg3 inContext:(struct CGContext { }*)arg4;
- (void)_drawNameForPort:(id)arg1 node:(id)arg2 atPoint:(struct CGPoint { double x1; double x2; })arg3 bounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg4 inContext:(struct CGContext { }*)arg5;
- (void)_drawTitleForNode:(id)arg1 bounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2 inContext:(struct CGContext { }*)arg3;
- (struct CGPoint { double x1; double x2; })pointForPort:(id)arg1 inNode:(id)arg2 bounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg3;
- (BOOL)pointInTitleRect:(struct CGPoint { double x1; double x2; })arg1 inNode:(id)arg2 bounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg3;
- (void)setTitle:(id)arg1 forNode:(id)arg2;
- (struct CGSize { double x1; double x2; })sizeForNode:(id)arg1;

@end
