/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuartzComposer.framework/Versions/A/QuartzComposer
 */

@interface QCMultiplexerImagePort : QCImagePort

- (BOOL)_execute:(double)arg1 arguments:(id)arg2;

@end
