/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuartzComposer.framework/Versions/A/QuartzComposer
 */

@interface QCNetworkReceiverUI : QCNetworkPatchUI

+ (id)viewNibName;

@end
