/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuartzComposer.framework/Versions/A/QuartzComposer
 */

@interface QCPickerSelectionLayer : CALayer {
    struct CGColor { } * _focusRingColor;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _selectionSelectionFrame;
}

- (void)__finalize_QCPickerSelectionLayer;
- (void)dealloc;
- (void)drawInContext:(struct CGContext { }*)arg1;
- (void)finalize;
- (void)setFocusRingColor:(struct CGColor { }*)arg1;
- (void)updateSelectionFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;

@end
