/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuartzComposer.framework/Versions/A/QuartzComposer
 */

@interface QCProxyPort : QCPort

+ (id)allocWithZone:(struct _NSZone { }*)arg1;
+ (Class)baseClass;

- (id)_argumentsFromAttributesKey:(id)arg1 originalArguments:(id)arg2;
- (unsigned long long)_timestamp;
- (BOOL)acceptValuesOfClass:(Class)arg1;
- (BOOL)canConnectToPort:(id)arg1;
- (id)initWithNode:(id)arg1 arguments:(id)arg2;
- (void)portWillDeleteFromNode;
- (BOOL)setStateValue:(id)arg1;
- (BOOL)setValue:(id)arg1;
- (id)stateValue;
- (BOOL)takeValue:(id)arg1 fromPort:(id)arg2;
- (id)value;
- (Class)valueClass;

// QCProxyPort (ParameterView)

- (void)resetParameterView:(id)arg1;
- (id)setupParameterView;

// QCProxyPort (QCColorPort)

- (void)getRed:(double*)arg1 green:(double*)arg2 blue:(double*)arg3 alpha:(double*)arg4;
- (void)setRed:(double)arg1 green:(double)arg2 blue:(double)arg3 alpha:(double)arg4;

// QCProxyPort (QCImagePort)

- (id)imageValue;
- (void)setImageValue:(id)arg1;

// QCProxyPort (QCInteractionPort)

- (void)_setConnectedPort:(id)arg1;

// QCProxyPort (QCMeshPort)

- (id)meshValue;
- (void)setMeshValue:(id)arg1;

// QCProxyPort (QCNumericPorts)

- (BOOL)booleanValue;
- (double)doubleValue;
- (unsigned long long)indexValue;
- (void)setBooleanValue:(BOOL)arg1;
- (void)setDoubleValue:(double)arg1;
- (void)setIndexValue:(unsigned long long)arg1;

// QCProxyPort (QCObjectPort)

- (id)object;
- (Class)objectClass;
- (BOOL)setObject:(id)arg1;

// QCProxyPort (QCProFX)

- (struct { unsigned char x1[16]; })md5WithTime:(double)arg1 arguments:(id)arg2;

// QCProxyPort (QCStringPort)

- (void)setStringValue:(id)arg1;
- (id)stringValue;

// QCProxyPort (QCStructurePort)

- (void)setStructureValue:(id)arg1;
- (id)structureValue;

// QCProxyPort (QCVirtualPort)

- (id)rawValue;
- (void)setRawValue:(id)arg1;

// QCProxyPort (ValueEditing)

- (void)editValueWithEvent:(id)arg1 inView:(id)arg2 atPoint:(struct CGPoint { double x1; double x2; })arg3;

@end
