/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuartzComposer.framework/Versions/A/QuartzComposer
 */

@interface QCSCN_LightReserved : NSObject {
    NSMutableDictionary * _animations;
    float  _attenuations;
    BOOL  _castsShadow;
    id  _color;
    struct _SCNVector3 { 
        double x; 
        double y; 
        double z; 
    }  _fresnelBias;
    struct _SCNVector3 { 
        double x; 
        double y; 
        double z; 
    }  _fresnelDirection;
    float  _fresnelExponent;
    NSString * _identifier;
    struct __C3DLight { struct __C3DEntity { struct __CFRuntimeBase { unsigned long long x_1_2_1; unsigned long long x_1_2_2; } x_1_1_1; struct __CFDictionary {} *x_1_1_2; } x1; struct __C3DSceneID {} *x2; struct C3DColor4 { union { float x_1_2_1[4]; struct { float x_2_3_1; float x_2_3_2; float x_2_3_3; float x_2_3_4; } x_1_2_2; } x_3_1_1; } x3; int x4; float x5[6]; struct C3DColor4 { union { float x_1_2_1[4]; struct { float x_2_3_1; float x_2_3_2; float x_2_3_3; float x_2_3_4; } x_1_2_2; } x_6_1_1; } x6; bool x7; bool x8; float x9; double x10; double x11; struct { /* ? */ } *x12; } * _light;
    NSString * _name;
    unsigned int  _presentationInstance;
    struct __C3DScene { struct __C3DEntity { struct __CFRuntimeBase { unsigned long long x_1_2_1; unsigned long long x_1_2_2; } x_1_1_1; struct __CFDictionary {} *x_1_1_2; } x1; struct __C3DSceneID {} *x2; struct __C3DNode {} *x3; struct __C3DAnimationManager {} *x4; double x5; double x6; double x7; double x8; struct __CFDictionary {} *x9; struct _SCNVector3 { double x_10_1_1; double x_10_1_2; double x_10_1_3; } x10; struct __C3DFXDeformerManager {} *x11; struct _opaque_pthread_mutex_t { long long x_12_1_1; BOOL x_12_1_2[56]; } x12; } * _sceneRef;
    id  _shadowColor;
    float  _softenFactor;
    NSString * _type;
    double  _zFar;
    double  _zNear;
}

- (void)dealloc;
- (void)finalize;

@end
