/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuartzComposer.framework/Versions/A/QuartzComposer
 */

@interface QCSmooth : QCPatch {
    QCArray * _iterationUpdate;
    QCArray * _lastTime;
    QCArray * _lastValue;
    BOOL  _needsRender;
    QCArray * _newValue;
    QCArray * _startTangent;
    QCArray * _startTime;
    QCArray * _startValue;
    QCArray * _tangent;
    BOOL  _useTangent;
    QCNumberPort * inputDecreasingDuration;
    QCInterpolationPort * inputDecreasingInterpolation;
    QCNumberPort * inputIncreasingDuration;
    QCInterpolationPort * inputIncreasingInterpolation;
    QCNumberPort * inputValue;
    QCNumberPort * outputValue;
}

+ (BOOL)allowsSubpatchesWithIdentifier:(id)arg1;
+ (BOOL)isSafe;
+ (id)stateArrays;
+ (id)stateKeysWithIdentifier:(id)arg1;
+ (unsigned long long)stateVersionWithIdentifier:(id)arg1;
+ (int)timeModeWithIdentifier:(id)arg1;

- (void)_computeValueForTime:(double)arg1 duration:(double)arg2 interpolation:(id)arg3 iteration:(unsigned long long)arg4;
- (void)dealloc;
- (BOOL)execute:(id)arg1 time:(double)arg2 arguments:(id)arg3;
- (id)initWithIdentifier:(id)arg1;
- (double)nextExecutionTime:(id)arg1 time:(double)arg2 arguments:(id)arg3;
- (BOOL)setup:(id)arg1;

// QCSmooth (QCInspector)

+ (id)inspectorNibNameWithIdentifier:(id)arg1;

@end
