/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuartzComposer.framework/Versions/A/QuartzComposer
 */

@interface QCStringPort : QCPort {
    int  _editorType;
    NSString * _string;
    void * _unused3;
}

- (int)editorType;
- (void)setEditorType:(int)arg1;
- (void)setStringValue:(id)arg1;
- (id)stringValue;

// QCStringPort (Override)

+ (Class)baseClass;

- (BOOL)acceptValuesOfClass:(Class)arg1;
- (void)dealloc;
- (id)initWithNode:(id)arg1 arguments:(id)arg2;
- (BOOL)setStateValue:(id)arg1;
- (BOOL)setValue:(id)arg1;
- (id)stateValue;
- (BOOL)takeValue:(id)arg1 fromPort:(id)arg2;
- (id)value;
- (Class)valueClass;

// QCStringPort (ParameterView)

- (void)resetParameterView:(id)arg1;
- (id)setupParameterView;

// QCStringPort (QCProFX)

- (struct { unsigned char x1[16]; })md5WithTime:(double)arg1 arguments:(id)arg2;

// QCStringPort (Tooltip)

- (id)tooltipString;

// QCStringPort (ValueEditing)

- (void)editValueWithEvent:(id)arg1 inView:(id)arg2 atPoint:(struct CGPoint { double x1; double x2; })arg3;

@end
