/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuickLookUI.framework/Versions/A/QuickLookUI
 */

@interface QLiPhotoExport : NSObject

+ (void)addDocumentWithURLToIPhoto:(id)arg1;
+ (BOOL)canExportToIPhoto;
+ (id)iPhotoBundleIdentifier;
+ (void)loadImageKitFrameworkIfNeeded;
+ (id)sharedSlideshow;

@end
