/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuickLookUI.framework/Versions/A/QuickLookUI
 */

@interface QLPreviewExtensionViewController : NSServiceViewController {
    QLPreviewExtensionContext * _extensionContext;
}

@property (nonatomic, readwrite) QLPreviewExtensionContext *extensionContext;

- (void).cxx_destruct;
- (void)dealloc;
- (id)exportedInterface;
- (id)extensionContext;
- (void)hookUpToExtensionContextWithUUID:(id)arg1 withCompletionHandler:(id)arg2;
- (void)loadView;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (void)setExtensionContext:(id)arg1;
- (void)setupWithController:(id)arg1;

@end
