/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuickLookUI.framework/Versions/A/QuickLookUI
 */

@interface QLPreviewWindowCloseButtonCell : QLPreviewWindowButtonCell

+ (id)buttonAlternateImage;
+ (id)buttonImage;
+ (SEL)buttonSelector;

- (id)accessibilitySubroleAttribute;

@end
