/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Backup.framework/Versions/A/Backup
 */

@interface BU_TMidnightTimer : NSObject {
    struct TNSRef<NSDateComponents *, void> { 
        NSDateComponents *fRef; 
    }  _dateComponents;
    struct TNSRef<NSDate *, void> { 
        NSDate *fRef; 
    }  _midnightFireDate;
    struct TNSRef<NSTimer *, void> { 
        NSTimer *fRef; 
    }  _midnightTimer;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)_checkTimerAndFireDate;
- (void)_midnightPassed;
- (void)_setUpMidnightTimer;
- (void)_systemTimeChanged:(id)arg1;
- (void)aboutToTearDown;
- (void)checkTimersAfterSleeping:(id)arg1;
- (id)init;
- (void)postNotificationIfDayChanged;

@end
