/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
 */

@interface _NSProgressFractionTuple : NSObject {
    _NSProgressFraction * _next;
    _NSProgressFraction * _previous;
}

@property (atomic, readwrite, copy) _NSProgressFraction *next;
@property (atomic, readwrite, copy) _NSProgressFraction *previous;

- (void)dealloc;
- (id)description;
- (id)next;
- (id)previous;
- (BOOL)previousIsEqualToNext;
- (void)setNext:(id)arg1;
- (void)setPrevious:(id)arg1;

@end
