/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
 */

@interface _NSSelectorSetBinding : NSKeySetBinding {
    int (* set;
    int (* setMethod;
    SEL  setSel;
}

- (id)initWithSetFunc:(int (*)arg1 forImp:(int (*)arg2 selector:(SEL)arg3;
- (BOOL)isScalarProperty;
- (void)setValue:(id)arg1 inObject:(id)arg2;

@end
