/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
 */

@interface NSConstantString : NSSimpleCString

- (const char *)_fastCStringContents:(BOOL)arg1;
- (BOOL)_isDeallocating;
- (BOOL)_tryRetain;
- (id)autorelease;
- (const char *)cString;
- (unsigned long long)cStringLength;
- (BOOL)canBeConvertedToEncoding:(unsigned long long)arg1;
- (unsigned short)characterAtIndex:(unsigned long long)arg1;
- (long long)compare:(id)arg1 options:(unsigned long long)arg2 range:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg3;
- (id)copy;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (unsigned long long)fastestEncoding;
- (void)getCharacters:(unsigned short*)arg1 range:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg2;
- (unsigned long long)hash;
- (id)initWithCharactersNoCopy:(unsigned short*)arg1 length:(unsigned long long)arg2;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isEqualToString:(id)arg1;
- (unsigned long long)length;
- (const char *)lossyCString;
- (oneway void)release;
- (id)retain;
- (unsigned long long)retainCount;
- (unsigned long long)smallestEncoding;

@end
