/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
 */

@interface NSUnit : NSObject <NSCopying, NSSecureCoding> {
    NSString * _symbol;
}

@property (atomic, readonly, copy) NSString *symbol;

+ (id)new;
+ (BOOL)supportsSecureCoding;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithSymbol:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)symbol;

@end
