/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MapKit.framework/Versions/A/MapKit
 */

@interface _MKCalloutDetailWrapperView : NSView {
    NSView * _view;
}

- (void).cxx_destruct;
- (double)firstBaselineOffsetFromTop;
- (id)initWithView:(id)arg1;
- (struct CGSize { double x1; double x2; })intrinsicContentSize;
- (double)lastBaselineOffsetFromBottom;

@end
