/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MapKit.framework/Versions/A/MapKit
 */

@interface _MKLabelMarkerItem : GEOBaseMapItem {
    VKLabelMarker * _labelMarker;
}

+ (id)labelMarkerItemWithLabelMarker:(id)arg1;

- (void).cxx_destruct;
- (BOOL)_hasMUID;
- (BOOL)_hasResolvablePartialInformation;
- (BOOL)_hasVenueFeatureType;
- (id)_identifier;
- (BOOL)_isTransitDisplayFeature;
- (id)_labelMarker;
- (unsigned long long)_muid;
- (id)_place;
- (id)_styleAttributes;
- (int)_venueFeatureType;
- (id)_venueInfo;
- (struct { double x1; double x2; })coordinate;
- (id)initWithLabelMarker:(id)arg1;
- (BOOL)isValid;
- (id)name;
- (int)referenceFrame;

@end
