/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MapKit.framework/Versions/A/MapKit
 */

@interface _MKTableViewControllerRootView : _MKUIViewControllerRootView {
    NSLayoutConstraint * _heightConstraint;
    BOOL  _performedInitialTableReload;
    NSTableView * _tableView;
}

@property (atomic, readonly) NSLayoutConstraint *heightConstraint;
@property (atomic, readwrite) NSTableView *tableView;

- (void).cxx_destruct;
- (id)heightConstraint;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)layout;
- (void)setTableView:(id)arg1;
- (id)tableView;
- (double)tableViewTotalHeight;
- (void)updateConstraints;
- (void)updateTableHeightConstraintAnimated:(BOOL)arg1;

@end
