/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MapKit.framework/Versions/A/MapKit
 */

@interface _NSImageRepAdaptiveToScale : NSCustomImageRep {
    id  _drawTarget;
}

@property (atomic, readwrite) id drawTarget;

- (void).cxx_destruct;
- (BOOL)draw;
- (id)drawTarget;
- (id)initWithDrawSelector:(SEL)arg1 delegate:(id)arg2;
- (void)setDrawTarget:(id)arg1;

@end
