/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MapKit.framework/Versions/A/MapKit
 */

@interface MKMapSnapshotFeatureAnnotation : NSObject <MKCustomFeatureAnnotation, NSSecureCoding> {
    struct { 
        double latitude; 
        double longitude; 
    }  _coordinate;
    VKCustomFeature * _customFeature;
    long long  _representation;
    NSString * _title;
}

@property (nonatomic, readwrite) struct { double x1; double x2; } coordinate;
@property (nonatomic, readwrite) double course;
@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (atomic, readonly) unsigned long long hash;
@property (nonatomic, readonly) long long representation;
@property (nonatomic, readonly) BOOL showsBalloonCallout;
@property (atomic, readonly) Class superclass;

+ (BOOL)supportsSecureCoding;

- (void).cxx_destruct;
- (struct { double x1; double x2; })coordinate;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)feature;
- (id)initWithCoder:(id)arg1;
- (id)initWithCoordinate:(struct CLLocationCoordinate2D { double x1; double x2; })arg1 title:(id)arg2 representation:(long long)arg3;
- (long long)representation;
- (void)setCoordinate:(struct { double x1; double x2; })arg1;
- (void)setShowsBalloonCallout:(BOOL)arg1;
- (BOOL)showsBalloonCallout;

@end
