/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MapKit.framework/Versions/A/MapKit
 */

@interface MKResizedArtworkDataSourceCache : MKArtworkDataSourceCache {
    NSCache * _resizedImageCache;
    id  _resizingBlock;
}

@property (nonatomic, readonly, copy) NSCache *resizedImageCache;
@property (nonatomic, readonly, copy) id resizingBlock;

- (void).cxx_destruct;
- (void)_cacheImage:(id)arg1 forKey:(id)arg2;
- (id)_cachedImageForKey:(id)arg1;
- (id)_resizedImage:(id)arg1 toSize:(struct CGSize { double x1; double x2; })arg2;
- (id)imageForArtwork:(id)arg1 size:(long long)arg2 featureType:(unsigned long long)arg3 scale:(double)arg4 widthPaddingMultiple:(double)arg5;
- (id)initWithArtworkManager:(id)arg1 imageResizingBlock:(id)arg2;
- (void)purge;
- (id)resizedImageCache;
- (id)resizingBlock;

@end
