/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ContactsFoundation.framework/Versions/A/ContactsFoundation
 */

@interface CNObservableEvent : NSObject

@property (nonatomic, readonly, copy) NSError *error;
@property (nonatomic, readonly) unsigned long long eventType;
@property (nonatomic, readonly) BOOL hasValue;
@property (nonatomic, readonly) id value;

+ (id)completionEvent;
+ (id)eventWithResult:(id)arg1;
+ (id)failureEventWithError:(id)arg1;

- (void)dematerializeWithObserver:(id)arg1;
- (id)error;
- (unsigned long long)eventType;
- (BOOL)hasValue;
- (id)value;

@end
