/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ContactsFoundation.framework/Versions/A/ContactsFoundation
 */

@interface CNObservable : NSObject <CNObservable> {
    NSString * _pipelineDescription;
}

@property (atomic, readonly, copy) NSString *debugDescription;
@property (nonatomic, readonly) NSString *debugPipelineDescription;
@property (atomic, readonly, copy) NSString *description;
@property (atomic, readonly) unsigned long long hash;
@property (atomic, readonly) Class superclass;

+ (id)combineLatest:(id)arg1;
+ (id)combineLatest:(id)arg1 schedulerProvider:(id)arg2;
+ (id)concatenate:(id)arg1;
+ (id)emptyObservable;
+ (id)forkJoin:(id)arg1 scheduler:(id)arg2;
+ (id)merge:(id)arg1;
+ (id)merge:(id)arg1 schedulerProvider:(id)arg2;
+ (id)neverObservable;
+ (id)observableWithBlock:(id)arg1;
+ (id)observableWithError:(id)arg1;
+ (id)observableWithFuture:(id)arg1;
+ (id)observableWithFutures:(id)arg1;
+ (id)observableWithFutures:(id)arg1 schedulerProvider:(id)arg2;
+ (id)observableWithRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg1;
+ (id)observableWithRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg1 interval:(double)arg2 scheduler:(id)arg3;
+ (id)observableWithRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg1 scheduler:(id)arg2;
+ (id)observableWithResult:(id)arg1;
+ (id)observableWithResults:(id)arg1;
+ (id)observableWithResults:(id)arg1 interval:(double)arg2 scheduler:(id)arg3;
+ (id)observableWithResults:(id)arg1 scheduler:(id)arg2;
+ (id)observableWithTimeInterval:(double)arg1 scheduler:(id)arg2;
+ (id)progressiveForkJoin:(id)arg1 scheduler:(id)arg2;
+ (id)timerWithDelay:(double)arg1;
+ (id)timerWithDelay:(double)arg1 scheduler:(id)arg2;

- (void).cxx_destruct;
- (id)allObjects:(id*)arg1;
- (id)any:(id)arg1;
- (id)buffer:(unsigned long long)arg1;
- (id)buffer:(unsigned long long)arg1 interval:(double)arg2;
- (id)buffer:(unsigned long long)arg1 interval:(double)arg2 scheduler:(id)arg3;
- (id)bufferWithInterval:(double)arg1;
- (id)bufferWithInterval:(double)arg1 scheduler:(id)arg2;
- (id)concatMap:(id)arg1;
- (id)concatMap:(id)arg1 schedulerProvider:(id)arg2;
- (id)delay:(double)arg1 scheduler:(id)arg2;
- (id)delaySubscription:(double)arg1 scheduler:(id)arg2;
- (id)dematerialize;
- (id)distinct;
- (id)distinctUntilChanged;
- (id)doOnCancel:(id)arg1;
- (id)doOnCompletion:(id)arg1;
- (id)doOnError:(id)arg1;
- (id)doOnNext:(id)arg1;
- (id)doOnSubscribe:(id)arg1;
- (id)doOnTerminate:(id)arg1;
- (void)enumerateObjectsUsingBlock:(id)arg1;
- (id)filter:(id)arg1;
- (id)flatMap:(id)arg1;
- (id)flatMap:(id)arg1 schedulerProvider:(id)arg2;
- (id)ignoreElements;
- (id)map:(id)arg1;
- (id)materialize;
- (id)observeOn:(id)arg1;
- (id)onEmpty:(id)arg1;
- (id)onError:(id)arg1;
- (id)onErrorHandler:(id)arg1;
- (id)publish;
- (id)sample:(double)arg1;
- (id)sample:(double)arg1 scheduler:(id)arg2;
- (id)sampleWithObservable:(id)arg1;
- (id)scan:(id)arg1;
- (id)scan:(id)arg1 seed:(id)arg2;
- (id)skip:(unsigned long long)arg1;
- (id)skipLast:(unsigned long long)arg1;
- (id)startWith:(id)arg1;
- (id)startWith:(id)arg1 scheduler:(id)arg2;
- (id)subscribe:(id)arg1;
- (id)subscribeOn:(id)arg1;
- (id)switch;
- (id)switchMap:(id)arg1;
- (id)switchMap:(id)arg1 schedulerProvider:(id)arg2;
- (id)switchWithSchedulerProvider:(id)arg1;
- (id)take:(unsigned long long)arg1;
- (id)takeLast:(unsigned long long)arg1;
- (id)throttle:(double)arg1 options:(unsigned long long)arg2 schedulerProvider:(id)arg3;
- (id)throttle:(double)arg1 schedulerProvider:(id)arg2;
- (id)throttleFirst:(double)arg1 scheduler:(id)arg2;
- (id)throttleFirstAndLast:(double)arg1 schedulerProvider:(id)arg2;
- (id)timeInterval;
- (id)timeIntervalWithScheduler:(id)arg1;
- (id)timeoutAfterDelay:(double)arg1 alternateObservable:(id)arg2 schedule:(id)arg3;
- (id)timestampWithScheduler:(id)arg1;
- (id)toArray;
- (id)using:(id)arg1;

// CNObservable (DarwinNotify)

+ (id)observableOnDarwinNotificationCenterWithName:(id)arg1;

// CNObservable (DataDetectors)

+ (id)binderTypeForResultType:(unsigned long long)arg1;
+ (id)observableWithEmailAddressesInString:(id)arg1;
+ (id)observableWithScannerResultsInString:(id)arg1;
+ (id)observableWithScannerResultsOfType:(unsigned long long)arg1 inString:(id)arg2;

// CNObservable (DebugDescription)

- (id)debugDescription;
- (id)debugPipelineDescription;
- (id)pipelineDescription:(id)arg1;
- (id)pipelineDescriptionWithOperation:(id)arg1 onObservable:(id)arg2;

// CNObservable (Generators)

+ (id)observableWithInitialState:(id)arg1 condition:(id)arg2 nextState:(id)arg3 resultSelector:(id)arg4;
+ (id)observableWithInitialState:(id)arg1 condition:(id)arg2 nextState:(id)arg3 resultSelector:(id)arg4 delay:(id)arg5 scheduler:(id)arg6;
+ (id)observableWithInitialState:(id)arg1 condition:(id)arg2 nextState:(id)arg3 resultSelector:(id)arg4 scheduler:(id)arg5;

// CNObservable (NSKeyValueObserving)

+ (id)observableForKeyPath:(id)arg1 ofObject:(id)arg2 withOptions:(unsigned long long)arg3;

// CNObservable (NSNotification)

+ (id)observableOnDefaultNotificationCenterWithName:(id)arg1 object:(id)arg2;
+ (id)observableOnNotificationCenter:(id)arg1 withName:(id)arg2 object:(id)arg3;

// CNObservable (TimestampReplay)

+ (id)observableWithAbsoluteTimestamps:(id)arg1 schedulerProvider:(id)arg2;
+ (id)observableWithRelativeTimestamps:(id)arg1 schedulerProvider:(id)arg2;
+ (void)sendNextTimestampFromQueue:(id)arg1 toObserver:(id)arg2 untilCanceled:(id)arg3 scheduler:(id)arg4;

@end
