/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSNeuralNetwork.framework/Versions/A/MPSNeuralNetwork
 */

@interface MPSCNNNeuronELU : MPSCNNNeuron

@property (nonatomic, readonly) float a;

// MPSCNNNeuronELU (null)

- (float)a;
- (id)initWithDevice:(id)arg1 a:(float)arg2;

@end
