/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSNeuralNetwork.framework/Versions/A/MPSNeuralNetwork
 */

@interface ResourceWrapper : NSObject <NodeWrapper> {
    struct ResourceGraphNode { id x1; inout out double x2; /* Warning: Unrecognized filer type: 'e' using 'void*' */ void*x3; unsigned long x4; int x5; short x6; void*x7; void*x8; void*x9; int x10; long x11; void*x12; void*x13; const void*x14; const void*x15; void*x16; void*x17; inout out double x18; void*x19; void*x20; char *x21; void*x22; void*x23; struct FilterGraphNode {} **x24; unsigned long long x25; unsigned long long x26; } * _node;
}

@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (atomic, readonly) unsigned long long hash;
@property (atomic, readonly) Class superclass;

// ResourceWrapper (null)

+ (BOOL)supportsSecureCoding;
+ (id)wrapperWithResource:(struct ResourceGraphNode { id x1; inout out double x2; /* Warning: Unrecognized filer type: 'e' using 'void*' */ void*x3; unsigned long x4; int x5; short x6; void*x7; void*x8; void*x9; int x10; long x11; void*x12; void*x13; const void*x14; const void*x15; void*x16; void*x17; inout out double x18; void*x19; void*x20; char *x21; void*x22; void*x23; struct FilterGraphNode {} **x24; unsigned long long x25; unsigned long long x26; }*)arg1;

- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithResource:(struct ResourceGraphNode { id x1; inout out double x2; /* Warning: Unrecognized filer type: 'e' using 'void*' */ void*x3; unsigned long x4; int x5; short x6; void*x7; void*x8; void*x9; int x10; long x11; void*x12; void*x13; const void*x14; const void*x15; void*x16; void*x17; inout out double x18; void*x19; void*x20; char *x21; void*x22; void*x23; struct FilterGraphNode {} **x24; unsigned long long x25; unsigned long long x26; }*)arg1;
- (void*)node;

@end
