/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
 */

@interface HIFilePresenter : NSObject <NSFilePresenter> {
    struct __CFURL { } * fURL;
    struct OpaqueWindowPtr { } * fWindow;
}

@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (atomic, readonly) unsigned long long hash;
@property (atomic, readonly, retain) NSOperationQueue *presentedItemOperationQueue;
@property (atomic, readonly, copy) NSURL *presentedItemURL;
@property (atomic, readonly, copy) NSURL *primaryPresentedItemURL;
@property (atomic, readonly) Class superclass;

- (void)dealloc;
- (id)initForWindow:(struct OpaqueWindowPtr { }*)arg1 withURL:(struct __CFURL { }*)arg2;
- (void)presentedItemDidMoveToURL:(id)arg1;
- (id)presentedItemOperationQueue;
- (id)presentedItemURL;
- (void)savePresentedItemChangesWithCompletionHandler:(id)arg1;

@end
