/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Backup.framework/Versions/A/Backup
 */

@interface BU_TDateFormatterController : NSObject {
    struct TNSRef<BU_TValidatingDateFormatter *, void> { 
        BU_TValidatingDateFormatter *fRef; 
    }  _fileNameDateTimeFormatter;
    struct TNSRef<BU_TValidatingDateFormatter *, void> { 
        BU_TValidatingDateFormatter *fRef; 
    }  _fileNameTimeFormatter;
    struct TNSRef<BU_TValidatingDateFormatter *, void> { 
        BU_TValidatingDateFormatter *fRef; 
    }  _fullDateOnlyFormatter;
    struct TNSRef<BU_TValidatingDateFormatter *, void> { 
        BU_TValidatingDateFormatter *fRef; 
    }  _fullDateOnlyFormatterRelative;
    struct TNSRef<BU_TValidatingDateFormatter *, void> { 
        BU_TValidatingDateFormatter *fRef; 
    }  _fullDateTimeFormatter;
    struct TNSRef<BU_TValidatingDateFormatter *, void> { 
        BU_TValidatingDateFormatter *fRef; 
    }  _fullDateTimeFormatterRelative;
    struct TNSRef<BU_TValidatingDateFormatter *, void> { 
        BU_TValidatingDateFormatter *fRef; 
    }  _longDateTimeFormatter;
    struct TNSRef<BU_TValidatingDateFormatter *, void> { 
        BU_TValidatingDateFormatter *fRef; 
    }  _longDateTimeFormatterRelative;
    struct TNSRef<BU_TValidatingDateFormatter *, void> { 
        BU_TValidatingDateFormatter *fRef; 
    }  _mediumDateOnlyFormatter;
    struct TNSRef<BU_TValidatingDateFormatter *, void> { 
        BU_TValidatingDateFormatter *fRef; 
    }  _mediumDateOnlyFormatterRelative;
    struct TNSRef<BU_TValidatingDateFormatter *, void> { 
        BU_TValidatingDateFormatter *fRef; 
    }  _mediumDateTimeFormatter;
    struct TNSRef<BU_TValidatingDateFormatter *, void> { 
        BU_TValidatingDateFormatter *fRef; 
    }  _mediumDateTimeFormatterRelative;
    struct vector<TNotificationCenterObserver, std::__1::allocator<TNotificationCenterObserver> > { 
        struct TNotificationCenterObserver {} *__begin_; 
        struct TNotificationCenterObserver {} *__end_; 
        struct __compressed_pair<TNotificationCenterObserver *, std::__1::allocator<TNotificationCenterObserver> > { 
            struct TNotificationCenterObserver {} *__first_; 
        } __end_cap_; 
    }  _observers;
    struct TNSRef<BU_TValidatingDateFormatter *, void> { 
        BU_TValidatingDateFormatter *fRef; 
    }  _shortDateOnlyFormatter;
    struct TNSRef<BU_TValidatingDateFormatter *, void> { 
        BU_TValidatingDateFormatter *fRef; 
    }  _shortDateOnlyFormatterRelative;
    struct TNSRef<BU_TValidatingDateFormatter *, void> { 
        BU_TValidatingDateFormatter *fRef; 
    }  _shortDateTimeFormatter;
    struct TNSRef<BU_TValidatingDateFormatter *, void> { 
        BU_TValidatingDateFormatter *fRef; 
    }  _shortDateTimeFormatterRelative;
    struct TNSRef<BU_TValidatingDateFormatter *, void> { 
        BU_TValidatingDateFormatter *fRef; 
    }  _timeOnlyFormatter;
}

+ (id)dateFormatterController;

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)fileNameDateTimeFormatter;
- (id)fileNameTimeFormatter;
- (id)fullDateOnlyFormatter:(bool)arg1;
- (id)fullDateTimeFormatter:(bool)arg1;
- (id)init;
- (id)longDateTimeFormatter:(bool)arg1;
- (id)mediumDateOnlyFormatter:(bool)arg1;
- (id)mediumDateTimeFormatter:(bool)arg1;
- (void)reset;
- (id)shortDateOnlyFormatter:(bool)arg1;
- (id)shortDateTimeFormatter:(bool)arg1;
- (id)timeOnlyFormatter;

@end
