/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUI.framework/Versions/A/CoreUI
 */

@interface CUICustomFontCacheKey : NSObject {
    NSString * _name;
    double  _pointSize;
}

@property (nonatomic, readwrite, copy) NSString *name;
@property (nonatomic, readwrite) double pointSize;

- (void)dealloc;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)name;
- (double)pointSize;
- (void)setName:(id)arg1;
- (void)setPointSize:(double)arg1;

@end
