/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MediaPlayer.framework/Versions/A/MediaPlayer
 */

@interface MPAdvanceShuffleModeCommand : MPRemoteCommand

- (id)newCommandEventWithPreservesShuffleMode:(BOOL)arg1;

@end
