/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ContactsPersistence.framework/Versions/A/ContactsPersistence
 */

@interface ABCDOwnedObject : NSManagedObject

@property (nonatomic, readwrite, retain) NSNumber *isPrimary;
@property (nonatomic, readwrite, retain) NSString *label;
@property (nonatomic, readwrite, retain) NSNumber *orderingIndex;
@property (nonatomic, readwrite, retain) ABCDRecord *owner;
@property (nonatomic, readwrite, retain) NSString *uniqueId;

// Image: /System/Library/PrivateFrameworks/ContactsPersistence.framework/Versions/A/ContactsPersistence

+ (id)insertOwnedObjectWithEntityName:(id)arg1 inManagedObjectContext:(id)arg2;

- (id)cacheKey;
- (void)didChangeValueForKey:(id)arg1;
- (void)prepareForDeletion;
- (void)setUniqueId:(id)arg1;
- (void)touch:(id)arg1;
- (void)willChangeValueForKey:(id)arg1;

// Image: /System/Library/Frameworks/AddressBook.framework/Versions/A/AddressBook

// ABCDOwnedObject (AddressBook)

+ (id)keyPathsForValuesAffectingPostalAddressValue;

- (id)XMLRepresentation;
- (id)barcodeXML;
- (id)postalAddressValue;

@end
