/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ContactsPersistence.framework/Versions/A/ContactsPersistence
 */

@interface ABCDPlatform : NSObject

+ (bool)isTimeMachineURL:(id)arg1;

@end
