/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ContactsPersistence.framework/Versions/A/ContactsPersistence
 */

@interface ABCDPostalAddress : ABCDOwnedObject

@property (nonatomic, readwrite, retain) NSString *city;
@property (nonatomic, readwrite, retain) NSString *countryCode;
@property (nonatomic, readwrite, retain) NSString *countryName;
@property (nonatomic, readwrite, retain) NSData *customValuesDictionary;
@property (nonatomic, readwrite, retain) NSString *region;
@property (nonatomic, readwrite, retain) NSString *sama;
@property (nonatomic, readwrite, retain) NSString *state;
@property (nonatomic, readwrite, retain) NSString *street;
@property (nonatomic, readwrite, retain) NSString *subAdministrativeArea;
@property (nonatomic, readwrite, retain) NSString *subLocality;
@property (nonatomic, readwrite, retain) NSString *zipCode;

- (void)setSubAdministrativeArea:(id)arg1;
- (id)subAdministrativeArea;

@end
