/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ContactsPersistence.framework/Versions/A/ContactsPersistence
 */

@interface CNCDOrphanPropertyMigrator : CNCDMigrator

- (void)migrate;
- (void)migrateOrphanProperties;
- (void)migrateOrphanPropertiesForEntityNamed:(id)arg1;

@end
