/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
 */

@interface CIColorPosterize : CIFilter {
    CIImage * inputImage;
    NSNumber * inputLevels;
}

@property (nonatomic, readwrite, retain) CIImage *inputImage;
@property (nonatomic, readwrite, retain) NSNumber *inputLevels;

+ (id)customAttributes;

- (BOOL)_isIdentity;
- (id)_kernel;
- (id)inputImage;
- (id)inputLevels;
- (id)outputImage;
- (void)setInputImage:(id)arg1;
- (void)setInputLevels:(id)arg1;

@end
