/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
 */

@interface CIDisplacementDistortion : CIFilter {
    CIImage * inputDisplacementImage;
    CIImage * inputImage;
    NSNumber * inputScale;
}

+ (id)customAttributes;

- (id)_CIDisplaceFromImage;
- (id)outputImage;

@end
