/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
 */

@interface CILinearLightBlendMode : CIBlendModeFilter

+ (id)_kernel;
+ (id)customAttributes;

@end
