/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
 */

@interface CIPlugInStandardFilter : CIFilter {
    NSMutableDictionary * _attributes;
    CIKernel * _filterKernel;
    NSMutableArray * _inputKeys;
    NSMutableDictionary * _inputs;
    NSURL * _kernelFileURL;
    NSMutableArray * _outputKeys;
    NSBundle * _plugInBundle;
    NSObject<OS_dispatch_source> * kernelChangeSource;
}

@property (nonatomic, readwrite, retain) NSBundle *bundle;
@property (nonatomic, readonly, retain) NSURL *kernelFileURL;
@property (nonatomic, readonly, retain) NSString *kernelFilename;

- (id)_provideFilterCopyWithZone:(struct _NSZone { }*)arg1;
- (id)attributes;
- (id)bundle;
- (void)dealloc;
- (void)finalize;
- (id)initWithDescription:(id)arg1 kernelFile:(id)arg2 filterBundle:(id)arg3;
- (id)inputKeys;
- (id)kernelFileURL;
- (id)kernelFilename;
- (id)outputImage;
- (id)outputKeys;
- (void)setBundle:(id)arg1;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (id)valueForUndefinedKey:(id)arg1;

// CIPlugInStandardFilter (Private)

+ (BOOL)isDebugging;

- (void)loadKernel;
- (BOOL)setupInputs;
- (void)setupWatchingForKernelChanges;

@end
