/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Navigation.framework/Versions/A/Navigation
 */

@interface MNSpokenInstructionContents : MNListInstructionContents <MNInstructionContents> {
    <GEOServerFormattedString> * _continueInstructionFormat;
    NSArray * _executionInstructionFormats;
    <GEOServerFormattedString> * _initialInstructionFormat;
    BOOL  _isSecondary;
    struct { 
        long long context; 
        double distance; 
        BOOL usePrimaryName; 
        BOOL useSecondaryName; 
        BOOL useDistanceForSecondary; 
        BOOL useContinueForSecondary; 
        int numPrimarySigns; 
        int numSecondarySigns; 
    }  _options;
    <GEOServerFormattedString> * _prepareInstructionFormat;
    <GEOServerFormattedString> * _proceedInstructionFormat;
}

@property (nonatomic, readwrite) long long context;
@property (nonatomic, readwrite, retain) <GEOServerFormattedString> *continueInstructionFormat;
@property (nonatomic, readwrite, retain) NSArray *executionInstructionFormats;
@property (nonatomic, readonly) BOOL hasServerContent;
@property (nonatomic, readwrite, retain) <GEOServerFormattedString> *initialInstructionFormat;
@property (nonatomic, readonly) int numSignsWanted;
@property (nonatomic, readwrite, retain) <GEOServerFormattedString> *prepareInstructionFormat;
@property (nonatomic, readwrite, retain) <GEOServerFormattedString> *proceedInstructionFormat;
@property (nonatomic, readwrite, retain) NSString *roadName;
@property (nonatomic, readwrite) BOOL suppressFallback;
@property (nonatomic, readwrite) BOOL suppressNames;

+ (id)contentsWithStep:(id)arg1 transportType:(int)arg2 destination:(id)arg3 options:(struct { long long x1; double x2; BOOL x3; BOOL x4; BOOL x5; BOOL x6; int x7; int x8; }*)arg4 isSecondary:(BOOL)arg5;

- (void).cxx_destruct;
- (id)_instructionsForFormats:(id)arg1 distance:(double)arg2;
- (void)_populateFromStep:(id)arg1;
- (long long)context;
- (id)continueInstructionFormat;
- (id)description;
- (id)executionInstructionFormats;
- (BOOL)hasServerContent;
- (id)init;
- (id)initialInstructionFormat;
- (id)instructionForStage:(unsigned long long)arg1 distance:(double)arg2;
- (id)instructionWithShorterAlternatives:(id*)arg1;
- (int)numSignsWanted;
- (id)prepareInstructionFormat;
- (id)proceedInstructionFormat;
- (void)setContext:(long long)arg1;
- (void)setContinueInstructionFormat:(id)arg1;
- (void)setExecutionInstructionFormats:(id)arg1;
- (void)setInitialInstructionFormat:(id)arg1;
- (void)setPrepareInstructionFormat:(id)arg1;
- (void)setProceedInstructionFormat:(id)arg1;

@end
