/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Navigation.framework/Versions/A/Navigation
 */

@interface MNTracePlaybackDetails : PBCodable <NSCopying> {
    NSMutableArray * _bookmarks;
    double  _currentPosition;
    int  _eventType;
    struct { 
        unsigned int currentPosition : 1; 
        unsigned int traceDuration : 1; 
        unsigned int eventType : 1; 
        unsigned int recordedBookmarkID : 1; 
    }  _has;
    unsigned int  _recordedBookmarkID;
    double  _traceDuration;
    NSString * _tracePath;
}

@property (nonatomic, readwrite, retain) NSMutableArray *bookmarks;
@property (nonatomic, readwrite) double currentPosition;
@property (nonatomic, readwrite) int eventType;
@property (nonatomic, readwrite) BOOL hasCurrentPosition;
@property (nonatomic, readwrite) BOOL hasEventType;
@property (nonatomic, readwrite) BOOL hasRecordedBookmarkID;
@property (nonatomic, readwrite) BOOL hasTraceDuration;
@property (nonatomic, readonly) BOOL hasTracePath;
@property (nonatomic, readwrite) unsigned int recordedBookmarkID;
@property (nonatomic, readwrite) double traceDuration;
@property (nonatomic, readwrite, retain) NSString *tracePath;

+ (Class)bookmarkType;

- (void).cxx_destruct;
- (int)StringAsEventType:(id)arg1;
- (void)addBookmark:(id)arg1;
- (id)bookmarkAtIndex:(unsigned long long)arg1;
- (id)bookmarks;
- (unsigned long long)bookmarksCount;
- (void)clearBookmarks;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (double)currentPosition;
- (id)description;
- (id)dictionaryRepresentation;
- (int)eventType;
- (id)eventTypeAsString:(int)arg1;
- (BOOL)hasCurrentPosition;
- (BOOL)hasEventType;
- (BOOL)hasRecordedBookmarkID;
- (BOOL)hasTraceDuration;
- (BOOL)hasTracePath;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (unsigned int)recordedBookmarkID;
- (void)setBookmarks:(id)arg1;
- (void)setCurrentPosition:(double)arg1;
- (void)setEventType:(int)arg1;
- (void)setHasCurrentPosition:(BOOL)arg1;
- (void)setHasEventType:(BOOL)arg1;
- (void)setHasRecordedBookmarkID:(BOOL)arg1;
- (void)setHasTraceDuration:(BOOL)arg1;
- (void)setRecordedBookmarkID:(unsigned int)arg1;
- (void)setTraceDuration:(double)arg1;
- (void)setTracePath:(id)arg1;
- (double)traceDuration;
- (id)tracePath;
- (void)writeTo:(id)arg1;

@end
