/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Navigation.framework/Versions/A/Navigation
 */

@interface MNTraceETAUpdateRow : NSObject <MNTracePlayerTimelineStreamObjectType> {
    NSError * _error;
    GEOETATrafficUpdateRequest * _request;
    double  _requestTimestamp;
    GEOETATrafficUpdateResponse * _response;
    double  _responseTimestamp;
}

@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (nonatomic, readwrite, retain) NSError *error;
@property (atomic, readonly) unsigned long long hash;
@property (nonatomic, readonly) double position;
@property (nonatomic, readwrite, retain) GEOETATrafficUpdateRequest *request;
@property (nonatomic, readwrite) double requestTimestamp;
@property (nonatomic, readwrite, retain) GEOETATrafficUpdateResponse *response;
@property (nonatomic, readwrite) double responseTimestamp;
@property (atomic, readonly) Class superclass;

- (void).cxx_destruct;
- (id)error;
- (id)request;
- (double)requestTimestamp;
- (id)response;
- (double)responseTimestamp;
- (void)setError:(id)arg1;
- (void)setRequest:(id)arg1;
- (void)setRequestTimestamp:(double)arg1;
- (void)setResponse:(id)arg1;
- (void)setResponseTimestamp:(double)arg1;

// MNTraceETAUpdateRow (MNTracePlayerAdapter)

- (double)position;

@end
