/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Navigation.framework/Versions/A/Navigation
 */

@interface MNTraceDirectionsRow : NSObject <MNTracePlayerTimelineStreamObjectType> {
    NSError * _error;
    GEODirectionsRequest * _request;
    double  _requestTimestamp;
    GEODirectionsResponse * _response;
    double  _responseTimestamp;
    NSArray * _waypoints;
}

@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (nonatomic, readwrite, retain) NSError *error;
@property (atomic, readonly) unsigned long long hash;
@property (nonatomic, readonly) double position;
@property (nonatomic, readwrite, retain) GEODirectionsRequest *request;
@property (nonatomic, readwrite) double requestTimestamp;
@property (nonatomic, readwrite, retain) GEODirectionsResponse *response;
@property (nonatomic, readwrite) double responseTimestamp;
@property (atomic, readonly) Class superclass;
@property (nonatomic, readwrite, retain) NSArray *waypoints;

- (void).cxx_destruct;
- (id)error;
- (id)request;
- (double)requestTimestamp;
- (id)response;
- (double)responseTimestamp;
- (void)setError:(id)arg1;
- (void)setRequest:(id)arg1;
- (void)setRequestTimestamp:(double)arg1;
- (void)setResponse:(id)arg1;
- (void)setResponseTimestamp:(double)arg1;
- (void)setWaypoints:(id)arg1;
- (id)waypoints;

// MNTraceDirectionsRow (MNTracePlayerAdapter)

- (double)position;

@end
