/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Navigation.framework/Versions/A/Navigation
 */

@interface MNTraceAnnotatedUserBehaviorRow : NSObject {
    long long  _event;
    double  _timestamp;
}

@property (nonatomic, readwrite) long long event;
@property (nonatomic, readwrite) double timestamp;

- (long long)event;
- (void)setEvent:(long long)arg1;
- (void)setTimestamp:(double)arg1;
- (double)timestamp;

@end
