/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
 */

@interface AVAssetAnalysisMessage : NSObject {
    void * _analysisMessageInternal;
}

+ (id)assetAnalysisMessageWithFigDictionary:(id)arg1;

@end
