/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
 */

@interface AVAssetReaderTrackOutputInternal : NSObject {
    BOOL  appliesPreferredTrackTransform;
    NSString * audioTimePitchAlgorithm;
    AVOutputSettings * outputSettings;
    AVAssetTrack * track;
    AVWeakReference * weakReferenceToAttachedAdaptor;
}

@end
