/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
 */

@interface AVCaptureAudioChannel : NSObject {
    AVCaptureAudioChannelInternal * _internal;
}

@property (nonatomic, readonly) float averagePowerLevel;
@property (getter=isEnabled, nonatomic, readwrite) BOOL enabled;
@property (nonatomic, readonly) float peakHoldLevel;
@property (nonatomic, readwrite) float volume;

- (void)_updateEnabled:(BOOL)arg1;
- (void)_updateVolume:(float)arg1;
- (float)averagePowerLevel;
- (void)dealloc;
- (id)initWithConnection:(id)arg1;
- (void)invalidate;
- (BOOL)isEnabled;
- (float)peakHoldLevel;
- (void)setEnabled:(BOOL)arg1;
- (void)setVolume:(float)arg1;
- (float)volume;

@end
