/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
 */

@interface AVFragmentedAssetMinderInternal : NSObject {
    NSObject<OS_dispatch_queue> * accessSerializer;
    NSMutableSet * assets;
    double  mindingInterval;
}

- (void).cxx_destruct;

@end
