/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
 */

@interface AVFragmentedMovieTrack : AVMovieTrack {
    AVFragmentedMovieTrackInternal * _fragmentedMovieTrack;
}

- (void).cxx_destruct;

@end
