/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
 */

@interface AVMutableCaptionRegion : AVCaptionRegion {
    AVMutableCaptionRegionInternal * _mutableInternal;
}

@property (nonatomic, readwrite, copy) AVCaptionLength *height;
@property (nonatomic, readwrite, copy) AVCaptionPosition *position;
@property (nonatomic, readwrite) long long scroll;

- (id)height;
- (id)init;
- (id)initWithFigMutableCaptionRegion:(struct OpaqueFigCaptionRegion { }*)arg1;
- (id)position;
- (long long)scroll;
- (void)setHeight:(id)arg1;
- (void)setPosition:(id)arg1;
- (void)setScroll:(long long)arg1;

@end
