/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
 */

@interface AVOutputContextCommunicationChannel : NSObject {
    AVOutputContextCommunicationChannelInternal * _ivars;
}

@property (nonatomic, readonly) const struct __CFString { }*commChannelUUID;
@property (nonatomic, readonly) <AVOutputContextCommunicationChannelImpl> *impl;
@property (nonatomic, readonly) struct OpaqueFigEndpointRemoteControlSession { }*remoteControlSession;

- (void)dealloc;
- (id)impl;
- (id)init;
- (id)initWithOutputContextCommunicationChannelImpl:(id)arg1;
- (void)sendData:(id)arg1 completionHandler:(id)arg2;

// AVOutputContextCommunicationChannel (FigCommChannelUUID)

- (const struct __CFString { }*)commChannelUUID;

// AVOutputContextCommunicationChannel (FigEndpointRemoteControlSession)

- (struct OpaqueFigEndpointRemoteControlSession { }*)remoteControlSession;

@end
