/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
 */

@interface AVSynchronizedLayerInternal : NSObject {
    BOOL  isVisible;
    AVPlayerItem * playerItem;
    NSObject<OS_dispatch_queue> * serialQueue;
}

@end
