/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MetalKit.framework/Versions/A/MetalKit
 */

@interface MTKTextureIOBufferMap : NSObject <TXRBufferMap> {
    void * _bytes;
}

@property (nonatomic, readonly) void*bytes;
@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (atomic, readonly) unsigned long long hash;
@property (atomic, readonly) Class superclass;

- (void*)bytes;
- (id)initWithContents:(void*)arg1;

@end
