/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
 */

@interface _NSKeyedUnarchiveFromDataTransformer : _NSSharedValueTransformer

- (id)description;
- (id)reverseTransformedValue:(id)arg1;
- (id)transformedValue:(id)arg1;

@end
