/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
 */

@interface NSConcretePortCoder : NSPortCoder {
    NSSet * whitelist;
}

- (BOOL)_classAllowed:(Class)arg1;
- (void)_setWhitelist:(id)arg1;
- (void)dealloc;

@end
