/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
 */

@interface NSUserAppleScriptTask : NSUserScriptTask {
    BOOL  _isParentDefaultTarget;
}

@property (setter=setParentDefaultTarget:, atomic, readwrite) BOOL isParentDefaultTarget;

+ (BOOL)isValidScriptFile:(id)arg1 error:(id*)arg2;

- (void)executeWithAppleEvent:(id)arg1 completionHandler:(id)arg2;
- (void)executeWithCompletionHandler:(id)arg1;
- (id)initWithURL:(id)arg1 error:(id*)arg2;
- (BOOL)isParentDefaultTarget;
- (void)setParentDefaultTarget:(BOOL)arg1;

@end
