/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
 */

@interface NSUTIPredicateOperator : NSPredicateOperator

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)initForVariant:(unsigned long long)arg1;
- (BOOL)performPrimitiveOperationUsingObject:(id)arg1 andObject:(id)arg2;
- (id)predicateFormat;
- (unsigned long long)variant;

@end
