/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/WebCore
 */

@interface WebAVOutputDeviceMenuControllerHelper : NSObject {
    struct MediaPlaybackTargetPickerMac { int (**x1)(); unsigned int x2; struct Client {} *x3; struct Timer<WebCore::MediaPlaybackTargetPicker> { int (**x_4_1_1)(); struct Ref<WTF::RunLoop> { struct RunLoop {} *x_2_2_1; } x_4_1_2; struct RetainPtr<__CFRunLoopTimer *> { void *x_3_2_1; } x_4_1_3; struct MediaPlaybackTargetPicker {} *x_4_1_4; } x4; struct RetainPtr<AVOutputDeviceMenuController> { void *x_5_1_1; } x5; struct RetainPtr<WebAVOutputDeviceMenuControllerHelper> { void *x_6_1_1; } x6; bool x7; } * m_callback;
}

- (void)clearCallback;
- (id)initWithCallback:(struct MediaPlaybackTargetPickerMac { int (**x1)(); unsigned int x2; struct Client {} *x3; struct Timer<WebCore::MediaPlaybackTargetPicker> { int (**x_4_1_1)(); struct Ref<WTF::RunLoop> { struct RunLoop {} *x_2_2_1; } x_4_1_2; struct RetainPtr<__CFRunLoopTimer *> { void *x_3_2_1; } x_4_1_3; struct MediaPlaybackTargetPicker {} *x_4_1_4; } x4; struct RetainPtr<AVOutputDeviceMenuController> { void *x_5_1_1; } x5; struct RetainPtr<WebAVOutputDeviceMenuControllerHelper> { void *x_6_1_1; } x6; bool x7; }*)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;

@end
