/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebKitLegacy.framework/Versions/A/WebKitLegacy
 */

@interface WebCache : NSObject

+ (void)clearCachedCredentials;
+ (void)empty;
+ (void)initialize;
+ (BOOL)isDisabled;
+ (void)setDisabled:(BOOL)arg1;
+ (id)statistics;

@end
