/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebKitLegacy.framework/Versions/A/WebKitLegacy
 */

@interface WebJavaScriptTextInputPanel : NSWindowController {
    NSTextField * prompt;
    NSTextField * textInput;
}

- (id)initWithPrompt:(id)arg1 text:(id)arg2;
- (void)pressedCancel:(id)arg1;
- (void)pressedOK:(id)arg1;
- (id)text;

@end
