/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebKitLegacy.framework/Versions/A/WebKitLegacy
 */

@interface WebScriptWorldPrivate : NSObject {
    struct RefPtr<WebCore::DOMWrapperWorld> { 
        struct DOMWrapperWorld {} *m_ptr; 
    }  world;
}

- (id).cxx_construct;
- (void).cxx_destruct;

@end
