/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebKitLegacy.framework/Versions/A/WebKitLegacy
 */

@interface WebTextInputPanel : NSPanel {
    NSTextView * _inputTextView;
}

- (id)_inputContext;
- (BOOL)_interpretKeyEvent:(id)arg1 string:(id*)arg2;
- (void)_keyboardInputSourceChanged:(id)arg1;
- (void)dealloc;
- (id)init;

@end
