/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 */

@interface _CFRemotePasteboardHandler : NSObject <NSXPCListenerDelegate, UAPasteboardClientProtocol>

@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (atomic, readonly) unsigned long long hash;
@property (atomic, readonly) Class superclass;

- (BOOL)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (void)pasteboardWillBeFetched:(id)arg1;
- (void)remotePasteboardAvailable:(BOOL)arg1;

@end
