/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 */

@interface NSInvocation : NSObject {
    id  _container;
    void * _frame;
    unsigned char  _reserved;
    unsigned char  _retainedArgs;
    void * _retdata;
    id  _signature;
}

@property (atomic, readonly) BOOL argumentsRetained;
@property (atomic, readonly, retain) NSMethodSignature *methodSignature;
@property (atomic, readwrite) SEL selector;
@property (atomic, readwrite) id target;

// Image: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation

+ (id)_invocationWithMethodSignature:(id)arg1 frame:(void*)arg2;
+ (id)invocationWithMethodSignature:(id)arg1;

- (void)_addAttachedObject:(id)arg1;
- (BOOL)argumentsRetained;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (void)getArgument:(void*)arg1 atIndex:(long long)arg2;
- (void)getReturnValue:(void*)arg1;
- (id)init;
- (void)invoke;
- (void)invokeSuper;
- (void)invokeUsingIMP:(int (*)arg1;
- (void)invokeWithTarget:(id)arg1;
- (id)methodSignature;
- (void)retainArguments;
- (SEL)selector;
- (void)setArgument:(void*)arg1 atIndex:(long long)arg2;
- (void)setReturnValue:(void*)arg1;
- (void)setSelector:(SEL)arg1;
- (void)setTarget:(id)arg1;
- (id)target;

// Image: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation

// NSInvocation (NSInvocationDebugDescription)

- (id)debugDescription;

// NSInvocation (NSXPCConnectionExtensions)

- (BOOL)_hasBlockArgument;
- (void)setUserInfo:(id)arg1;
- (id)userInfo;

@end
