/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreWiFi.framework/Versions/A/CoreWiFi
 */

@interface CoreWiFiWPSIE : CoreWiFiIE {
    CoreWiFiWPSTLVs * tlvs;
}

@property (nonatomic, readonly, retain) CoreWiFiWPSTLVs *tlvs;

- (void)dealloc;
- (id)description;
- (id)initWithIE:(id)arg1;
- (BOOL)parseIE:(id*)arg1;
- (id)tlvs;

@end
