/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PerformanceAnalysis.framework/Versions/A/PerformanceAnalysis
 */

@interface PAVideoCard : NSObject <NSCoding> {
    NSString * cardName;
    NSString * className;
    int  deviceId;
    unsigned long long  freeVRAM;
    NSDictionary * perfStats;
    unsigned long long  totalVRAM;
    unsigned long long  usedVRAM;
    int  vendorId;
}

@property (atomic, readwrite, retain) NSString *cardName;
@property (atomic, readwrite, retain) NSString *className;
@property (atomic, readwrite) int deviceId;
@property (atomic, readwrite) unsigned long long freeVRAM;
@property (atomic, readwrite, retain) NSDictionary *perfStats;
@property (atomic, readwrite) unsigned long long totalVRAM;
@property (atomic, readwrite) unsigned long long usedVRAM;
@property (atomic, readwrite) int vendorId;

- (id)cardName;
- (id)className;
- (void)dealloc;
- (int)deviceId;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)freeVRAM;
- (id)initWithCoder:(id)arg1;
- (id)initWithIOObject:(unsigned int)arg1;
- (id)perfStats;
- (void)printCardIds;
- (BOOL)printPerfStatForKey:(id)arg1;
- (void)printPerformanceStatistics;
- (void)printTotalVRAM;
- (void)setCardName:(id)arg1;
- (void)setClassName:(id)arg1;
- (void)setDeviceId:(int)arg1;
- (void)setFreeVRAM:(unsigned long long)arg1;
- (void)setPerfStats:(id)arg1;
- (void)setTotalVRAM:(unsigned long long)arg1;
- (void)setUsedVRAM:(unsigned long long)arg1;
- (void)setVendorId:(int)arg1;
- (unsigned long long)totalVRAM;
- (unsigned long long)usedVRAM;
- (BOOL)valueForPerfStatKey:(id)arg1 ValueOut:(unsigned int*)arg2;
- (int)vendorId;

@end
