/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation
 */

@interface SFIdentitySearchFilter : NSObject <NSCopying, NSSecureCoding> {
    id  _identitySearchFilterInternal;
}

@property (nonatomic, readwrite, copy) NSArray *certificateSerialNumbers;
@property (nonatomic, readwrite, copy) NSArray *certificateTypes;
@property (nonatomic, readwrite, copy) NSArray *keySpecifiers;

+ (BOOL)supportsSecureCoding;

- (void).cxx_destruct;
- (id)certificateSerialNumbers;
- (id)certificateTypes;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)keySpecifiers;
- (void)setCertificateSerialNumbers:(id)arg1;
- (void)setCertificateTypes:(id)arg1;
- (void)setKeySpecifiers:(id)arg1;

@end
