/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation
 */

@interface SFKeychainFetchResult_Ivars : NSObject {
    NSError * error;
    long long  resultType;
    id  value;
}

- (void).cxx_destruct;

@end
