/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation
 */

@interface SFRSASigningOperation_Ivars : NSObject {
    <SFDigestOperation> * digestOperation;
    _SFRSAKeySpecifier * keySpecifier;
}

- (void).cxx_destruct;

@end
