/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation
 */

@interface SFSignedData_Ivars : NSObject {
    NSData * data;
    NSData * signature;
}

- (void).cxx_destruct;

@end
