/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
 */

@interface NSScalarObjectID48 : _NSScalarObjectID {
    unsigned long long  _referenceData48_cd_rc16;
}

+ (char *)generatedNameSuffix;

- (unsigned long long)retainCount;

@end
