/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CalendarAgentLink.framework/Versions/A/CalendarAgentLink
 */

@interface CalAgentCache : NSObject {
    NSMutableDictionary * cachedValues;
    NSMutableSet * observers;
    NSObject<OS_dispatch_queue> * syncQueue;
}

+ (void)_agentSideSetup;
+ (void)_clientSideSetup;
+ (void)_clientSideSetupAddingObserver:(id)arg1;
+ (void)addCacheObserver:(id)arg1;
+ (id)agentCache;
+ (void)cacheUpdatedTo:(id)arg1;
+ (id)cachedValueForKey:(id)arg1;
+ (void)updateCachedDictionaryValue:(id)arg1 forKey:(id)arg2 dictionaryKey:(id)arg3;
+ (void)updateCachedValue:(id)arg1 forKey:(id)arg2;

- (void).cxx_destruct;
- (void)_addCacheObserver:(id)arg1;
- (void)_cacheUpdatedTo:(id)arg1;
- (id)_cachedValueForKey:(id)arg1;
- (void)_checkIn;
- (id)initWithInitialObserver:(id)arg1;

@end
