/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CalendarAgentLink.framework/Versions/A/CalendarAgentLink
 */

@interface CalStoreRemoteManagedAttendee : CalStoreRemoteManagedObject {
    NSURL * _address;
    NSString * _commonName;
    NSString * _status;
    int  _type;
}

@property (nonatomic, readwrite, retain) NSURL *address;
@property (nonatomic, readwrite, retain) NSString *commonName;
@property (nonatomic, readwrite, retain) NSString *status;
@property (nonatomic, readwrite) int type;

+ (BOOL)supportsSecureCoding;

- (void).cxx_destruct;
- (id)address;
- (id)commonName;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)setAddress:(id)arg1;
- (void)setCommonName:(id)arg1;
- (void)setStatus:(id)arg1;
- (void)setType:(int)arg1;
- (id)status;
- (int)type;

@end
