/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList
 */

@interface SFLListObserver : NSObject {
    int (* _callback;
    void * _context;
    SFLList * _list;
    NSObject<OS_dispatch_queue> * _queue;
    struct __CFRunLoop { } * _runloop;
    struct __CFString { } * _runloopMode;
}

@property (atomic, readwrite) int (*callback;
@property (atomic, readwrite) void*context;
@property (atomic, readwrite) SFLList *list;
@property (atomic, readonly) NSObject<OS_dispatch_queue> *queue;
@property (atomic, readonly) struct __CFRunLoop { }*runloop;
@property (atomic, readonly) struct __CFString { }*runloopMode;

+ (BOOL)addObserver:(id)arg1 forList:(id)arg2;
+ (id)observersByList;
+ (id)observersSerialQueue;
+ (BOOL)removeObserver:(id)arg1 forList:(id)arg2;

- (int (*)callback;
- (void*)context;
- (void)dealloc;
- (void)finalize;
- (unsigned long long)hash;
- (id)initWithTargetQueue:(id)arg1 callback:(int (*)arg2 context:(void*)arg3;
- (id)initWithTargetRunloop:(struct __CFRunLoop { }*)arg1 runloopMode:(struct __CFString { }*)arg2 callback:(int (*)arg3 context:(void*)arg4;
- (BOOL)isEqual:(id)arg1;
- (id)list;
- (void)notify;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (id)queue;
- (struct __CFRunLoop { }*)runloop;
- (struct __CFString { }*)runloopMode;
- (void)setCallback:(int (*)arg1;
- (void)setContext:(void*)arg1;
- (void)setList:(id)arg1;

@end
