/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SceneKit.framework/Versions/A/SceneKit
 */

@interface SCNExportOperation : NSOperation

- (BOOL)canceled;
- (id)error;
- (double)progress;
- (BOOL)succeded;

@end
