/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SceneKit.framework/Versions/A/SceneKit
 */

@interface SCNGeometryTessellator : NSObject <NSCopying, NSSecureCoding> {
    BOOL  _adaptive;
    NSMutableSet * _clients;
    float  _edgeTessellationFactor;
    float  _insideTessellationFactor;
    float  _maximumEdgeLength;
    unsigned long long  _partitionMode;
    BOOL  _screenSpace;
    long long  _smoothingMode;
    float  _tessellationFactorScale;
}

@property (getter=isAdaptive, nonatomic, readwrite) BOOL adaptive;
@property (nonatomic, readwrite) double edgeTessellationFactor;
@property (nonatomic, readwrite) double insideTessellationFactor;
@property (nonatomic, readwrite) double maximumEdgeLength;
@property (getter=isScreenSpace, nonatomic, readwrite) BOOL screenSpace;
@property (nonatomic, readwrite) long long smoothingMode;
@property (nonatomic, readwrite) double tessellationFactorScale;
@property (nonatomic, readwrite) unsigned long long tessellationPartitionMode;

+ (BOOL)supportsSecureCoding;

- (struct { unsigned char x1; float x2; unsigned int x3; unsigned char x4; union { struct { float x_1_2_1; float x_1_2_2; } x_5_1_1; struct { float x_2_2_1; } x_5_1_2; struct { float x_3_2_1; } x_5_1_3; struct { unsigned char x_4_2_1; unsigned int x_4_2_2 : 1; unsigned int x_4_2_3 : 1; } x_5_1_4; } x5; })_tessellatorValueForGeometry:(id)arg1;
- (BOOL)adaptive;
- (void)addClient:(id)arg1;
- (void)clientWillDie:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (double)edgeTessellationFactor;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (double)insideTessellationFactor;
- (BOOL)isAdaptive;
- (BOOL)isScreenSpace;
- (double)maximumEdgeLength;
- (void)removeClient:(id)arg1;
- (BOOL)screenSpace;
- (void)setAdaptive:(BOOL)arg1;
- (void)setEdgeTessellationFactor:(double)arg1;
- (void)setInsideTessellationFactor:(double)arg1;
- (void)setMaximumEdgeLength:(double)arg1;
- (void)setScreenSpace:(BOOL)arg1;
- (void)setSmoothingMode:(long long)arg1;
- (void)setTessellationFactorScale:(double)arg1;
- (void)setTessellationPartitionMode:(unsigned long long)arg1;
- (long long)smoothingMode;
- (double)tessellationFactorScale;
- (unsigned long long)tessellationPartitionMode;
- (void)tessellatorValueDidChange;
- (void)tessellatorValueDidChangeForClient:(id)arg1;

// SCNGeometryTessellator (SCNUIDynamicUI)

+ (id)SCNUID_creationOptions;
+ (id)SCNUID_instanciateWithOption:(id)arg1;

@end
