/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SceneKit.framework/Versions/A/SceneKit
 */

@interface SCNMetalWireframeResource : NSObject {
    void * material;
    void * program;
    void * programHashCode;
}

- (void)dealloc;

@end
