/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SceneKit.framework/Versions/A/SceneKit
 */

@interface SCNUIProperty : NSObject {
    NSString * name;
    Class  objectClass;
    BOOL  readonly;
    int  type;
}

@property (nonatomic, readwrite, retain) NSString *name;
@property (nonatomic, readwrite, retain) Class objectClass;
@property (nonatomic, readwrite) BOOL readonly;
@property (nonatomic, readwrite) int type;

- (void).cxx_destruct;
- (id)name;
- (Class)objectClass;
- (BOOL)readonly;
- (void)setName:(id)arg1;
- (void)setObjectClass:(Class)arg1;
- (void)setReadonly:(BOOL)arg1;
- (void)setType:(int)arg1;
- (int)type;

@end
