/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/QTKit.framework/Versions/A/QTKit
 */

@interface QTCaptureDeviceInput : QTCaptureInput {
    QTCaptureDeviceInputInternal * _internal;
    long long  _reserved4;
    long long  _reserved5;
    long long  _reserved6;
}

+ (id)deviceInputWithDevice:(id)arg1;

- (void)_setDevice:(id)arg1;
- (BOOL)addInputUnitsForConnection:(id)arg1 toGraph:(struct OpaqueCMIOGraph { }*)arg2 ofCaptureSession:(id)arg3 error:(id*)arg4;
- (BOOL)automaticallyConfiguresDevice;
- (int)clockProviderNodeForConnection:(id)arg1;
- (int)connectionGraphNodeForConnection:(id)arg1;
- (unsigned int)connectionUnitOutputNumberForConnection:(id)arg1;
- (id)connections;
- (void)dealloc;
- (id)device;
- (id)init;
- (id)initWithDevice:(id)arg1;
- (id)notReadyError;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (void)removeInputUnitsForConnection:(id)arg1 fromGraph:(struct OpaqueCMIOGraph { }*)arg2 ofCaptureSession:(id)arg3;
- (void)sessionWillUseOutputDecompressionOptions:(id)arg1 forConnection:(id)arg2;
- (void)setAutomaticallyConfiguresDevice:(BOOL)arg1;

@end
