/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/QTKit.framework/Versions/A/QTKit
 */

@interface QTCaptureSessionInternalState : NSObject {
    int  _audioMixerFanOutNode;
    int  _audioMixerNode;
    int  _candidateMasterSynchronizerNode;
    struct OpaqueCMIOGraph { } * _graph;
    BOOL  _hasAudioMixerFanOutNode;
    BOOL  _hasAudioMixerNode;
    BOOL  _masterSynchronizerSet;
    struct __CFDictionary { } * _supportUnitsForConnections;
}

- (void)dealloc;
- (void)finalize;
- (struct OpaqueCMIOGraph { }*)graph;
- (id)init;
- (void)invalidate;
- (struct __CFDictionary { }*)supportUnitsForConnections;

@end
