/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
 */

@interface CIAttributedTextImageGenerator : CIFilter {
    NSNumber * inputScaleFactor;
    NSAttributedString * inputText;
}

@property (nonatomic, readwrite, retain) NSNumber *inputScaleFactor;
@property (nonatomic, readwrite, retain) NSAttributedString *inputText;

+ (id)customAttributes;

- (id)inputScaleFactor;
- (id)inputText;
- (id)outputImage;
- (void)setInputScaleFactor:(id)arg1;
- (void)setInputText:(id)arg1;

@end
