/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
 */

@interface CIMorphologyMinimum : CIMorphology

+ (id)customAttributes;

- (id)outputImage;

@end
