/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AddressBook.framework/Versions/A/AddressBook
 */

@interface _ABGeocodingMapsLauncher : ABMapsLauncher {
    CLGeocoder * _geocoder;
}

@property (nonatomic, readonly) CLGeocoder *geocoder;

- (void).cxx_destruct;
- (id)geocoder;
- (id)initWithLaunchRequest:(id)arg1 nextLauncher:(id)arg2;
- (void)launchMaps;
- (void)launchMapsShowingPlacemarks:(id)arg1;
- (id)launchOptionsWithDirections:(BOOL)arg1;
- (void)showPlacemarks:(id)arg1;

@end
