/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AddressBook.framework/Versions/A/AddressBook
 */

@interface ABActionAddressCopyMailingLabel : NSObject

- (id)actionProperty;
- (void)performActionForPerson:(id)arg1 identifier:(id)arg2;
- (BOOL)shouldEnableActionForPerson:(id)arg1 identifier:(id)arg2;
- (id)titleForPerson:(id)arg1 identifier:(id)arg2;

@end
