/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AddressBook.framework/Versions/A/AddressBook
 */

@interface ABCNContactKeyValueUpdate : NSObject <ABCNContactUpdate> {
    ABCNPropertyDescription * _property;
    id  _value;
}

@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (atomic, readonly) unsigned long long hash;
@property (atomic, readonly) Class superclass;

- (void)applyToABCDContact:(id)arg1;
- (void)applyToABPerson:(id)arg1;
- (void)applyToMutableContact:(id)arg1 withIdentifierMap:(id)arg2;
- (void)dealloc;
- (id)description;
- (unsigned long long)hash;
- (id)initWithProperty:(id)arg1 value:(id)arg2;
- (BOOL)isEqual:(id)arg1;
- (id)property;

@end
