/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AddressBook.framework/Versions/A/AddressBook
 */

@interface ABCNSaveResponse : NSObject {
    NSMutableArray * _errors;
    NSMutableArray * _successBlocks;
    NSMutableDictionary * _updatedGroups;
}

- (void)dealloc;
- (id)errors;
- (void)executeSuccessBlocks;
- (id)init;
- (id)updatedGroups;
- (id)userInfoRepresentation;

@end
