/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AddressBook.framework/Versions/A/AddressBook
 */

@interface ABCNGroup : NSObject <NSCopying, NSMutableCopying> {
    ABCNGroupIdentifier * _identifier;
    NSString * _name;
    ABCNGroup * _snapshot;
}

@property (nonatomic, readonly, copy) ABCNGroupIdentifier *identifier;
@property (nonatomic, readonly, copy) NSString *name;
@property (nonatomic, readonly, copy) ABCNGroup *snapshot;

+ (id)identifierProvider;
+ (id)makeIdentifier;
+ (id)makeIdentifierString;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)description;
- (unsigned long long)hash;
- (id)identifier;
- (id)init;
- (id)initWithGroup:(id)arg1;
- (id)initWithIdentifier:(id)arg1 name:(id)arg2;
- (id)initWithName:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)mutableCopyWithZone:(struct _NSZone { }*)arg1;
- (id)name;
- (id)snapshot;

// ABCNGroup (PredicateCreation)

+ (id)predicateForIdentifiers:(id)arg1;

// ABCNGroup (PredicateCreationInternal)

+ (id)predicateForNamePrefix:(id)arg1;

@end
