/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AddressBook.framework/Versions/A/AddressBook
 */

@interface ABCNContact : NSObject <NSCopying, NSMutableCopying, NSSecureCoding> {
    NSString * _accountIdentifier;
    NSDictionary * _alertTones;
    NSDateComponents * _alternateBirthdayComponents;
    NSDateComponents * _birthdayComponents;
    NSArray * _calendarURIs;
    NSString * _cardDAVUID;
    NSString * _companyName;
    NSDate * _creationDate;
    NSString * _departmentName;
    long long  _displayStyle;
    NSArray * _emailAddresses;
    NSString * _firstName;
    ABCNContactIdentifier * _identifier;
    NSArray * _instantMessageAddresses;
    NSString * _jobTitle;
    NSString * _lastName;
    NSString * _linkIdentifier;
    NSArray * _linkedContacts;
    NSString * _maidenName;
    NSString * _middleName;
    long long  _nameOrder;
    NSString * _nameSuffix;
    NSString * _nameTitle;
    NSString * _nickname;
    NSString * _note;
    NSArray * _otherDateComponents;
    NSArray * _phoneNumbers;
    NSString * _phonemeData;
    NSString * _phoneticCompanyName;
    NSString * _phoneticFirstName;
    NSString * _phoneticLastName;
    NSString * _phoneticMiddleName;
    NSArray * _postalAddresses;
    NSString * _preferredApplePersonaIdentifier;
    BOOL  _preferredForName;
    BOOL  _preferredForPhoto;
    NSString * _preferredLikenessSource;
    NSArray * _relatedNames;
    ABCNContact * _snapshot;
    NSArray * _socialProfiles;
    NSString * _sortingFirstName;
    NSString * _sortingLastName;
    NSArray * _urlAddresses;
}

@property (nonatomic, readonly, copy) NSString *accountIdentifier;
@property (nonatomic, readonly, copy) NSDictionary *alertTones;
@property (nonatomic, readonly, copy) NSDateComponents *alternateBirthdayComponents;
@property (nonatomic, readonly, copy) NSDate *birthday;
@property (nonatomic, readonly, copy) NSDateComponents *birthdayComponents;
@property (nonatomic, readonly, copy) NSArray *calendarURIs;
@property (nonatomic, readonly, copy) NSString *cardDAVUID;
@property (nonatomic, readonly, copy) NSString *companyName;
@property (nonatomic, readonly, copy) NSDate *creationDate;
@property (nonatomic, readonly, copy) NSDate *creationDateForMailOnly;
@property (nonatomic, readonly, copy) NSString *departmentName;
@property (nonatomic, readonly, copy) NSString *displayName;
@property (nonatomic, readonly) long long displayStyle;
@property (nonatomic, readonly, copy) NSArray *emailAddresses;
@property (nonatomic, readonly, copy) NSString *firstName;
@property (nonatomic, readonly, copy) NSString *fullName;
@property (nonatomic, readonly, copy) ABCNContactIdentifier *identifier;
@property (nonatomic, readonly, copy) NSString *identifierString;
@property (nonatomic, readonly, copy) NSArray *instantMessageAddresses;
@property (nonatomic, readonly, copy) NSString *jobTitle;
@property (nonatomic, readonly, copy) NSString *lastName;
@property (nonatomic, readonly, copy) NSString *linkIdentifier;
@property (nonatomic, readonly, copy) NSArray *linkedContacts;
@property (nonatomic, readonly, copy) NSString *maidenName;
@property (nonatomic, readonly, copy) NSString *middleName;
@property (nonatomic, readonly) long long nameOrder;
@property (nonatomic, readonly, copy) NSString *nameSuffix;
@property (nonatomic, readonly, copy) NSString *nameTitle;
@property (nonatomic, readonly, copy) NSString *nickname;
@property (nonatomic, readonly, copy) NSString *note;
@property (nonatomic, readonly, copy) NSArray *otherDateComponents;
@property (nonatomic, readonly, copy) NSArray *otherDates;
@property (nonatomic, readonly, copy) NSArray *phoneNumbers;
@property (nonatomic, readonly, copy) NSString *phonemeData;
@property (nonatomic, readonly, copy) NSString *phoneticCompanyName;
@property (nonatomic, readonly, copy) NSString *phoneticFirstName;
@property (nonatomic, readonly, copy) NSString *phoneticFullName;
@property (nonatomic, readonly, copy) NSString *phoneticLastName;
@property (nonatomic, readonly, copy) NSString *phoneticMiddleName;
@property (nonatomic, readonly, copy) NSArray *postalAddresses;
@property (nonatomic, readonly, copy) NSString *preferredApplePersonaIdentifier;
@property (getter=isPreferredForName, nonatomic, readonly) BOOL preferredForName;
@property (getter=isPreferredForPhoto, nonatomic, readonly) BOOL preferredForPhoto;
@property (nonatomic, readonly, copy) NSString *preferredLikenessSource;
@property (nonatomic, readonly, copy) NSURL *quicklookURL;
@property (nonatomic, readonly, copy) NSArray *relatedNames;
@property (nonatomic, readonly, copy) NSDictionary *ringtone;
@property (nonatomic, readonly, copy) ABCNContact *snapshot;
@property (nonatomic, readonly, copy) NSArray *socialProfiles;
@property (nonatomic, readonly, copy) NSString *sortingFirstName;
@property (nonatomic, readonly, copy) NSString *sortingLastName;
@property (nonatomic, readonly, copy) NSDictionary *texttone;
@property (getter=isUnified, nonatomic, readonly) BOOL unified;
@property (nonatomic, readonly, copy) NSArray *urlAddresses;

+ (id)contact;
+ (id)contactWithIdentifier:(id)arg1;
+ (id)contactWithIdentifierString:(id)arg1;
+ (id)identifierProvider;
+ (id)makeIdentifier;
+ (id)makeIdentifierString;
+ (id)preferredPhotoComparator;
+ (BOOL)supportsSecureCoding;
+ (id)unifyContacts:(id)arg1;

- (id)accountIdentifier;
- (id)alertTones;
- (id)alternateBirthdayComponents;
- (BOOL)areAllPropertiesEqualToContact:(id)arg1;
- (BOOL)areAllPropertiesEqualToContactIgnoringIdentifiers:(id)arg1;
- (id)birthday;
- (id)birthdayComponents;
- (id)calendarURIs;
- (id)cardDAVUID;
- (id)companyName;
- (id)copyWithSelfAsSnapshot;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)creationDate;
- (void)dealloc;
- (id)departmentName;
- (id)description;
- (id)diffToSnapshot;
- (id)displayName;
- (long long)displayStyle;
- (id)emailAddresses;
- (void)encodeWithCoder:(id)arg1;
- (id)firstName;
- (id)fullName;
- (BOOL)hasChanges;
- (unsigned long long)hash;
- (id)identifier;
- (id)identifierString;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithContact:(id)arg1;
- (id)initWithIdentifier:(id)arg1;
- (id)instantMessageAddresses;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isEqualIgnoringIdentifiers:(id)arg1;
- (BOOL)isPreferredForName;
- (BOOL)isPreferredForPhoto;
- (BOOL)isProperty:(id)arg1 equalToOtherIgnoreIdentifiers:(id)arg2;
- (BOOL)isUnified;
- (id)jobTitle;
- (id)lastName;
- (id)linkIdentifier;
- (id)linkedContacts;
- (id)linkedIdentifierMap;
- (id)maidenName;
- (id)middleName;
- (id)mutableCopyWithZone:(struct _NSZone { }*)arg1;
- (long long)nameOrder;
- (id)nameSuffix;
- (id)nameTitle;
- (id)nickname;
- (id)note;
- (id)otherDateComponents;
- (id)otherDates;
- (id)phoneNumbers;
- (id)phonemeData;
- (id)phoneticCompanyName;
- (id)phoneticFirstName;
- (id)phoneticFullName;
- (id)phoneticLastName;
- (id)phoneticMiddleName;
- (id)postalAddresses;
- (id)preferredApplePersonaIdentifier;
- (id)preferredLikenessSource;
- (id)relatedNames;
- (id)ringtone;
- (id)snapshot;
- (id)socialProfiles;
- (id)sortingFirstName;
- (id)sortingLastName;
- (id)texttone;
- (id)urlAddresses;

// ABCNContact (Mail)

- (id)creationDateForMailOnly;

// ABCNContact (PredicateCreation)

+ (id)predicateForIdentifiers:(id)arg1;

// ABCNContact (PredicateCreationInternal)

+ (id)predicateForMembersOfGroupWithIdentifier:(id)arg1;

// ABCNContact (QuickLook)

- (id)quicklookURL;

@end
