/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AddressBook.framework/Versions/A/AddressBook
 */

@interface ABCNMutableSaveResponse : ABCNSaveResponse

- (void)addError:(id)arg1;
- (void)addSuccesBlocks:(id)arg1;
- (void)addSuccessBlock:(id)arg1;
- (void)addUpdatedGroup:(id)arg1;

@end
