/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AddressBook.framework/Versions/A/AddressBook
 */

@interface ABDataSourceExternalNotificationObserver : NSObject {
    NSDistributedNotificationCenter * _distributedNotificationCenter;
    NSNotificationCenter * _localNotificationCenter;
    <CNScheduler> * _preprocessingScheduler;
    ABAccountRepository * _repository;
}

@property (nonatomic, readonly) NSDistributedNotificationCenter *distributedNotificationCenter;
@property (nonatomic, readonly) NSNotificationCenter *localNotificationCenter;
@property (nonatomic, readonly) <CNScheduler> *preprocessingScheduler;
@property (nonatomic, readonly) ABAccountRepository *repository;

- (void)addSourceWithExternalNotification:(id)arg1;
- (void)dealloc;
- (void)distributedAccountConfigurationDidChange:(id)arg1;
- (id)distributedNotificationCenter;
- (void)distributedSourceAdded:(id)arg1;
- (void)distributedSourceChanged:(id)arg1;
- (void)distributedSourceRemoved:(id)arg1;
- (void)distributedSourcesInvalidated:(id)arg1;
- (void)extractUidFromNotification:(id)arg1 andRunBlock:(id)arg2;
- (id)initWithRepository:(id)arg1;
- (id)initWithRepository:(id)arg1 distributedNotificationCenter:(id)arg2 localNotificationCenter:(id)arg3 preprocessingScheduler:(id)arg4;
- (id)localNotificationCenter;
- (void)postAccountConfigurationDidChangeNotificationFromDistributedNotification:(id)arg1;
- (void)postAddedExternallyNotificationFromDistributedNotification:(id)arg1;
- (void)postChangedExternallyNotificationFromDistributedNotification:(id)arg1;
- (void)postInvalidatedExternallyNotificationFromDistributedNotification:(id)arg1;
- (void)postRemovedExternallyNotificationFromDistributedNotification:(id)arg1;
- (id)preprocessingScheduler;
- (void)removeSourceWithExternalNotification:(id)arg1;
- (id)repository;
- (void)startObservingNotifications;
- (void)stopObservingNotifications;

@end
