/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AddressBook.framework/Versions/A/AddressBook
 */

@interface ABDistributionKeyValueCell : ABPeoplePickerPropertyCell

+ (double)labelFontSize;

- (void)drawInteriorWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 inView:(id)arg2;
- (double)heightOfSubrowWithCountOfRows:(long long)arg1 inTableView:(id)arg2;
- (id)labelFont;
- (id)selectedLabelFont;
- (BOOL)shouldUseStrongLTRCharacters;

@end
