/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AddressBook.framework/Versions/A/AddressBook
 */

@interface ABFaceTimeCommunicationsBridge : NSObject {
    <ABFaceTimeCommunicationsBridgeDelegate> * _delegate;
    BOOL  _telephonySupported;
}

@property (nonatomic, readwrite) <ABFaceTimeCommunicationsBridgeDelegate> *delegate;
@property (getter=isTelephonySupported, nonatomic, readonly) BOOL telephonySupported;

+ (id)sharedInstance;

- (void).cxx_destruct;
- (id)delegate;
- (void)faceTimeAvailabilityChanged:(BOOL)arg1 forContactIdentifier:(id)arg2;
- (id)init;
- (BOOL)isTelephonySupported;
- (id)loggingNameForService:(id)arg1;
- (void)makeFaceTimeCallWithContactIdentifier:(id)arg1 isAudio:(BOOL)arg2;
- (void)makeFaceTimeCallWithEndpoint:(id)arg1 isAudio:(BOOL)arg2;
- (void)messagingAvailabilityChanged:(BOOL)arg1 forEndpoint:(id)arg2;
- (void)notifyClientOfResult:(id)arg1 fromEndpoints:(id)arg2 service:(id)arg3 forIdentifier:(id)arg4;
- (id)originalEndpointsByNormalizing:(id)arg1;
- (id)searchAvailabilityCacheForEndpoints:(id)arg1 service:(id)arg2;
- (void)setDelegate:(id)arg1;
- (void)startAvailabilityCheckForContactIdentifier:(id)arg1 service:(id)arg2 endpoints:(id)arg3;
- (void)startFaceTimeAvailabilityLookupForIdentifier:(id)arg1 endpoints:(id)arg2;
- (void)startMessagingAvailabilityLookupForEndpoint:(id)arg1;
- (void)startTelephonySupportLookup;
- (id)supplementalDialTelephonyCallString;
- (void)telephonyAvailaibilityChanged:(BOOL)arg1;
- (void)telophonySupportChanged:(id)arg1;
- (id)validEndpointFromResults:(id)arg1 forService:(id)arg2 contactIdentifier:(id)arg3;

@end
