/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AddressBook.framework/Versions/A/AddressBook
 */

@interface ABKeyedUnarchiver : NSKeyedUnarchiver {
    ABAddressBook * _addressBook;
}

@property (nonatomic, readonly) ABAddressBook *addressBook;

+ (id)unarchiveObjectWithData:(id)arg1 addressBook:(id)arg2;

- (id)addressBook;
- (void)dealloc;
- (id)initForReadingWithData:(id)arg1 addressBook:(id)arg2;

@end
