/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AddressBook.framework/Versions/A/AddressBook
 */

@interface ABManagedObjectContext : NSManagedObjectContext {
    <ABAccountCollection> * _ab_accountCollection;
    int  _aggregateMultiValueMode;
    <ABAddressBookReference> * _owningAddressBook;
    BOOL  _sendsChangeNotifications;
    BOOL  _unlockOnDealloc;
    BOOL  _writeChangesToServer;
}

@property (atomic, readwrite, retain) <ABAccountCollection> *ab_accountCollection;
@property (atomic, readwrite) int aggregateMultiValueMode;
@property (atomic, readwrite) ABAddressBook *owningAddressBook;
@property (atomic, readwrite) BOOL sendsChangeNotifications;
@property (atomic, readwrite) BOOL unlockOnDealloc;
@property (atomic, readwrite) BOOL writeChangesToServer;

+ (id)abUniqueIDsPredicate:(id)arg1;

- (void).cxx_destruct;
- (id)_ab_deletedRecords;
- (void)_ab_markRecordsForDeletion:(id)arg1;
- (BOOL)_ab_meCardHasBeenUpdated;
- (BOOL)_ab_meCardHasChanged;
- (BOOL)_ab_meCardHasChangedToAnotherCard;
- (void)_ab_sendAssistantChangeNotificationsForInsertedIdentifiers:(id)arg1 updatedIdentifiers:(id)arg2 deletedIdentifiers:(id)arg3;
- (void)_ab_sendMeCardHasChangedNotification;
- (void)_ab_sendMeCardHasChangedNotificationIfNecessary;
- (void)_ab_touchRecords;
- (id)_arrayOfContactsFromSet:(id)arg1;
- (void)_refreshObjectsRelatedToObject:(id)arg1;
- (void)_setContact:(id)arg1 preferredForLinkProperty:(id)arg2;
- (void)_setContact:(id)arg1 preferredForLinkProperty:(id)arg2 linkedContacts:(id)arg3;
- (void)_updateLinkingInformation;
- (id)abContactsForPredicate:(id)arg1;
- (id)abContactsForPredicate:(id)arg1 affectedStores:(id)arg2;
- (id)abContactsForUniqueIDs:(id)arg1;
- (id)abContactsForUniqueIDs:(id)arg1 affectedStores:(id)arg2;
- (id)abGroupsForPredicate:(id)arg1;
- (id)abGroupsForUniqueIDs:(id)arg1;
- (BOOL)abMeCardHasChanged;
- (id)abObjectsForPredicate:(id)arg1 entityName:(id)arg2;
- (id)abObjectsForPredicate:(id)arg1 entityName:(id)arg2 affectedStores:(id)arg3;
- (id)abObjectsForPredicate:(id)arg1 entityName:(id)arg2 affectedStores:(id)arg3 asFaults:(BOOL)arg4;
- (id)ab_accountCollection;
- (void)ab_tryRefreshRelationshipWithName:(id)arg1 description:(id)arg2 forObject:(id)arg3;
- (int)aggregateMultiValueMode;
- (id)contactsWithLinkIdentifier:(id)arg1;
- (void)dealloc;
- (void)deleteObject:(id)arg1;
- (id)deletedContacts;
- (id)initWithConcurrencyType:(unsigned long long)arg1;
- (id)insertedContacts;
- (BOOL)isMemoryBacked;
- (void)linkContact:(id)arg1 toContact:(id)arg2;
- (void)logCallStack:(id)arg1;
- (id)myContact;
- (id)owningAddressBook;
- (void)preheatContacts:(id)arg1;
- (void)preheatContacts:(id)arg1 keyPaths:(id)arg2;
- (void)preheatGroups:(id)arg1;
- (void)preheatGroups:(id)arg1 keyPaths:(id)arg2;
- (void)refreshRecords:(id)arg1;
- (BOOL)save:(id*)arg1;
- (BOOL)sendsChangeNotifications;
- (void)setAb_accountCollection:(id)arg1;
- (void)setAggregateMultiValueMode:(int)arg1;
- (void)setContactPreferredForLinkedName:(id)arg1;
- (void)setContactPreferredForLinkedName:(id)arg1 forLinkedContacts:(id)arg2;
- (void)setContactPreferredForLinkedPhoto:(id)arg1;
- (void)setContactPreferredForLinkedPhoto:(id)arg1 forLinkedContacts:(id)arg2;
- (void)setOwningAddressBook:(id)arg1;
- (void)setSendsChangeNotifications:(BOOL)arg1;
- (void)setUnlockOnDealloc:(BOOL)arg1;
- (void)setWriteChangesToServer:(BOOL)arg1;
- (void)unlinkContact:(id)arg1;
- (BOOL)unlockOnDealloc;
- (id)unscopedVersionOrSelf;
- (id)updatedContacts;
- (BOOL)writeChangesToServer;

@end
