/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AddressBook.framework/Versions/A/AddressBook
 */

@interface ABMergeAndLinkPeopleActionPlanner : NSObject {
    NSArray * _people;
}

@property (atomic, readonly) int plannedActions;

- (BOOL)anyAccountHasMoreThanOneWritablePerson:(id)arg1;
- (BOOL)anyPersonIsReadOnly;
- (void)dealloc;
- (id)initWithPeople:(id)arg1;
- (id)menuTitleForPlannedActions:(int)arg1;
- (id)peopleByStoreURL;
- (int)plannedActions;
- (BOOL)thereArePeopleInMoreThanOneAccount:(id)arg1;

@end
