/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AddressBook.framework/Versions/A/AddressBook
 */

@interface ABMutablePackedImage : ABPackedImage

- (void)addImage:(id)arg1 withName:(id)arg2;
- (void)setPath:(id)arg1;

@end
