/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AddressBook.framework/Versions/A/AddressBook
 */

@interface ABNewPersonCommand : ABCommand {
    ABPerson * _newPerson;
    NSDictionary * _personProperties;
    ABGroup * _selectedGroup;
}

- (void)dealloc;
- (BOOL)doIt;
- (void)finalize;
- (id)initWithNewPerson:(id)arg1 selectedGroup:(id)arg2 addressBook:(id)arg3;
- (void)redoIt;
- (void)undoIt;

@end
