/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AddressBook.framework/Versions/A/AddressBook
 */

@interface ABPeoplePickerLocalNotificationWatcher : NSObject {
    ABAddressBook * _addressBook;
    ABGroupEntriesList * _groupEntriesList;
    ABPersonListController * _personListController;
}

- (void)accountRepositoryDidChange:(id)arg1;
- (void)addressBookChanged:(id)arg1;
- (void)addressBookDidReset:(id)arg1;
- (void)addressBookWillReset:(id)arg1;
- (BOOL)anyGroupChanged:(id)arg1;
- (void)dealloc;
- (id)identifiersForRecords:(id)arg1;
- (id)initWithAddressBook:(id)arg1 groupEntriesList:(id)arg2 personListController:(id)arg3;
- (void)invalidate;
- (void)managedObjectContextDidSave:(id)arg1;
- (void)registerForNotifications;
- (void)unregisterForNotifications;
- (void)updateUserInterfaceWithContextDidUpdateNotification:(id)arg1;

@end
