/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AddressBook.framework/Versions/A/AddressBook
 */

@interface ABPeoplePickerNameCell : NSTextFieldCell {
    BOOL  _disableHighlight;
    unsigned long long  _iconType;
    int  _roundedEdges;
}

@property (nonatomic, readwrite) BOOL disableHighlight;
@property (nonatomic, readwrite) unsigned long long iconType;
@property (nonatomic, readwrite) int roundedEdges;

+ (unsigned long long)defaultFocusRingType;
+ (void)initialize;

- (void)_drawHighlightWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 inView:(id)arg2;
- (id)cellFont;
- (id)cellLabel;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (BOOL)disableHighlight;
- (void)drawHighlightWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 inView:(id)arg2;
- (void)drawInteriorWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 inView:(id)arg2;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })expansionFrameWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 inView:(id)arg2;
- (unsigned long long)focusRingType;
- (unsigned long long)iconType;
- (id)init;
- (int)roundedEdges;
- (void)selectWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 inView:(id)arg2 editor:(id)arg3 delegate:(id)arg4 start:(long long)arg5 length:(long long)arg6;
- (void)setDisableHighlight:(BOOL)arg1;
- (void)setIconType:(unsigned long long)arg1;
- (void)setRoundedEdges:(int)arg1;

// ABPeoplePickerNameCell (Accessibility)

- (id)accessibilityValueAttribute;
- (id)attributedStringValue;
- (id)stringValue;

@end
