/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AddressBook.framework/Versions/A/AddressBook
 */

@interface ABSearchingGroupEntry : ABGroupEntry <ABContactSearching> {
    ABAccount * _account;
    ABAddressBook * _addressBookForCreatingGroups;
    <ABSearchOperationsFactory> * _operationsFactory;
}

@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (atomic, readonly) NSString *displayName;
@property (atomic, readonly) unsigned long long hash;
@property (atomic, readonly) Class superclass;

- (void).cxx_destruct;
- (id)actionScope;
- (id)addressBookForCreatingGroups;
- (BOOL)canCreateGroup;
- (BOOL)canSelect;
- (id)createHelperWithFactory:(id)arg1;
- (id)description;
- (id)displayName;
- (id)iconWithStyleProvider:(id)arg1;
- (id)initWithName:(id)arg1 identifier:(id)arg2 operationsFactory:(id)arg3 addressBookForCreatingGroups:(id)arg4;
- (BOOL)isAvailableInTimeMachine;
- (id)searchOperationsForString:(id)arg1 delegate:(id)arg2;
- (id)selectHelperWithFactory:(id)arg1;

@end
