/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AddressBook.framework/Versions/A/AddressBook
 */

@interface ABUserActivityRestoration : NSObject

+ (id)companiesMatchingOrganizationName:(id)arg1 addressBook:(id)arg2;
+ (id)peopleMatchingFirstName:(id)arg1 lastName:(id)arg2 addressBook:(id)arg3;
+ (id)recordIdentifierBestMatchingPayload:(id)arg1 addressBook:(id)arg2;
+ (id)recordIdentifiersForServerUUIDs:(id)arg1 addressBook:(id)arg2;
+ (id)recordIdentifiersGivenPayload:(id)arg1 addressBook:(id)arg2;
+ (id)recordsMatchingEmailAddresses:(id)arg1 phoneNumbers:(id)arg2 addressBook:(id)arg3;
+ (id)scoreMatches:(id)arg1 usingPayload:(id)arg2;

@end
