/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AddressBook.framework/Versions/A/AddressBook
 */

@interface CNUIRejectSugggestedValueCommand : CNUIUndoableCommand {
    CNContactStore * _contactStore;
    CNLabeledValue * _valueToReject;
}

@property (nonatomic, readwrite, retain) CNContactStore *contactStore;
@property (nonatomic, readwrite, retain) CNLabeledValue *valueToReject;

- (void).cxx_destruct;
- (id)contactStore;
- (void)executeWithCNSaveRequest:(id)arg1;
- (id)initWithContactStore:(id)arg1;
- (id)initWithContactStore:(id)arg1 suggestedValueToReject:(id)arg2;
- (void)setContactStore:(id)arg1;
- (void)setValueToReject:(id)arg1;
- (id)valueToReject;

@end
