/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface __NSCustomSharingService : NSSharingService {
    long long  _type;
}

@property (atomic, readwrite) long long type;

- (void)setType:(long long)arg1;
- (long long)type;

@end
