/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface __NSTemporaryFileURL : NSObject {
    NSData * _data;
    NSString * _filename;
    NSURL * _url;
}

@property (atomic, readonly) NSURL *url;

- (void)dealloc;
- (id)initWithData:(id)arg1 filename:(id)arg2;
- (id)url;

@end
