/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface _NSBindingAdaptor : NSObject {
    NSMutableArray * _binders;
    id  _contentBinder;
    id  _editableBinder;
    id  _referenceBinder;
}

+ (void)copyBindingsFromObject:(id)arg1 toObject:(id)arg2;
+ (void)reconnectBindings:(id)arg1;
+ (id)returnDisconnectedBindingsOfObject:(id)arg1;

- (void)_discardEditingForAllBinders;
- (void)_editor:(id)arg1 didChangeEditingState:(BOOL)arg2 bindingAdaptor:(id)arg3;
- (BOOL)_handleValidationError:(id)arg1 description:(id)arg2 inEditor:(id)arg3 errorUserInterfaceHandled:(BOOL*)arg4 bindingAdaptor:(id)arg5;
- (void)_objectDidTriggerAction:(id)arg1 bindingAdaptor:(id)arg2;
- (BOOL)_validateAndCommitValueInEditor:(id)arg1 editingIsEnding:(BOOL)arg2 errorUserInterfaceHandled:(BOOL*)arg3 bindingAdaptor:(id)arg4;
- (void)addBinder:(id)arg1;
- (id)binders;
- (long long)boundOutlineView:(id)arg1 isItemExpandable:(id)arg2;
- (void)browser:(id)arg1 createRowsForColumn:(long long)arg2 inMatrix:(id)arg3;
- (BOOL)browser:(id)arg1 selectRow:(long long)arg2 inColumn:(long long)arg3;
- (void)browser:(id)arg1 willDisplayCell:(id)arg2 atRow:(long long)arg3 column:(long long)arg4;
- (void)collectionView:(id)arg1 didChangeToSelectionIndexes:(id)arg2;
- (id)contentBinder;
- (void)controller:(id)arg1 didChangeToFilterPredicate:(id)arg2;
- (void)controller:(id)arg1 didChangeToSelectionIndexPaths:(id)arg2;
- (void)controller:(id)arg1 didChangeToSelectionIndexes:(id)arg2;
- (void)controller:(id)arg1 didChangeToSortDescriptors:(id)arg2;
- (void)dealloc;
- (id)defaultSortDescriptorPrototypeForTableColumn:(id)arg1;
- (void)drawer:(id)arg1 didChangeToState:(BOOL)arg2;
- (id)editableBinder;
- (void)editorDidBeginEditing:(id)arg1;
- (void)editorDidEndEditing:(id)arg1;
- (BOOL)enabledStateForMenuItem:(id)arg1;
- (BOOL)handleValidationError:(id)arg1 description:(id)arg2 inEditor:(id)arg3 errorUserInterfaceHandled:(BOOL*)arg4;
- (id)init;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)objectDidTriggerAction:(id)arg1;
- (void)objectDidTriggerDoubleClickAction:(id)arg1;
- (void)outlineColumn:(id)arg1 willDisplayCell:(id)arg2 row:(long long)arg3;
- (void)outlineColumn:(id)arg1 willDisplayOutlineCell:(id)arg2 row:(long long)arg3;
- (id)outlineView:(id)arg1 child:(long long)arg2 ofItem:(id)arg3;
- (void)outlineView:(id)arg1 didExpandItem:(id)arg2;
- (long long)outlineView:(id)arg1 numberOfChildrenOfItem:(id)arg2;
- (void)outlineView:(id)arg1 willCollapseItem:(id)arg2;
- (void)outlineView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (void)outlineView:(id)arg1 willDisplayOutlineCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (id)referenceBinder;
- (void)removeBinder:(id)arg1;
- (void)resumeBinderObserving;
- (void)searchFieldCellOrControlDidClearRecents:(id)arg1;
- (id)searchMenuTemplate;
- (void)selectionMechanismWasDismissed:(id)arg1;
- (BOOL)setEnabledStateForToolbarItem:(id)arg1;
- (void)suspendBinderObserving;
- (void)tabView:(id)arg1 didSelectTabViewItem:(id)arg2;
- (void)tableColumn:(id)arg1 didChangeToWidth:(double)arg2;
- (void)tableColumn:(id)arg1 willDisplayCell:(id)arg2 row:(long long)arg3;
- (void)tableView:(id)arg1 didChangeToSelectedRowIndexes:(id)arg2;
- (void)tableView:(id)arg1 didChangeToSortDescriptors:(id)arg2;
- (id)tableView:(id)arg1 objectValueForRow:(long long)arg2;
- (BOOL)tableView:(id)arg1 shouldEditTableColumn:(id)arg2 row:(long long)arg3;
- (void)tableView:(id)arg1 updateVisibleRowInformation:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (id)updateInvalidatedFont:(id)arg1 forObject:(id)arg2;
- (id)updateInvalidatedObjectValue:(id)arg1 forObject:(id)arg2;
- (id)updateInvalidatedTextColor:(id)arg1 forObject:(id)arg2;
- (BOOL)validateAndCommitValueInEditor:(id)arg1 editingIsEnding:(BOOL)arg2 errorUserInterfaceHandled:(BOOL*)arg3;
- (void)window:(id)arg1 didChangeToVisibleState:(BOOL)arg2;
- (void)window:(id)arg1 didSetTitle:(id)arg2;
- (void)windowDidResize:(id)arg1;

@end
