/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface _NSEmptyColorGamut : NSColorGamut

+ (id)emptyGamut;
+ (void)initialize;

- (BOOL)containsCGColor:(struct CGColor { }*)arg1;
- (BOOL)containsGamut:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (unsigned long long)hash;
- (id)intersectionWithGamut:(id)arg1;
- (BOOL)intersectsGamut:(id)arg1;
- (BOOL)isEmpty;
- (BOOL)isEqualToGamut:(id)arg1;
- (BOOL)isInfinite;
- (id)unionWithGamut:(id)arg1;
- (double)volume;

@end
