/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface _NSFullScreenModalStackController : NSObject <_NSFullScreenModalDimmingWindowDelegate> {
    NSString * _beforeStackedSavedWindowFrameString;
    _NSFullScreenModalCollapsedTabWindow * _collapsedTabWindow;
    NSTimer * _deferredDragStartTimer;
    _NSFullScreenModalDimmingWindow * _dimmingWindow;
    BOOL  _disableBeginPresentation;
    BOOL  _dragShouldSnapBack;
    BOOL  _dragShouldSnapBackForDropTarget;
    BOOL  _dragShouldSnapBackForMinimize;
    struct CGPoint { 
        double x; 
        double y; 
    }  _dragSnapBackForMinimizeProhibitChangePosition;
    NSWindow * _frontWindow;
    BOOL  _hasDragProhibitChangePoint;
    BOOL  _invalid;
    BOOL  _isDragActive;
    BOOL  _isFrontWindowDragging;
    BOOL  _isFrontWindowOrderedIn;
    BOOL  _isPresentedModally;
    BOOL  _isRegisteredForNotifications;
    id  _showDragEffectEventMonitor;
    _NSFullScreenSpace * _space;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _windowDragStartFrame;
    NSWindowStackController * _windowStackController;
}

@property (nonatomic, readonly) _NSFullScreenModalCollapsedTabWindow *collapsedTabWindow;
@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (nonatomic, readwrite) BOOL disableBeginPresentation;
@property (atomic, readonly) unsigned long long hash;
@property (nonatomic, readonly) BOOL isDragActive;
@property (nonatomic, readonly) BOOL isPresentedModally;
@property (nonatomic, readwrite) _NSFullScreenSpace *space;
@property (atomic, readonly) Class superclass;
@property (nonatomic, readonly) NSWindowStackController *windowStackController;

- (void)_actuallyBeginDraggingFrontWindow;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_adjustedSnapshotWindowFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 basedOnImage:(struct CGImage { }*)arg2;
- (void)_dragMoved;
- (void)_showModalWindowDragEffect;
- (id)backgroundWindowIDs;
- (id)beforeStackedSavedWindowFrameString;
- (void)beginModalPresentationWithCompletionHandler:(id)arg1 forCloseSpace:(BOOL)arg2;
- (void)beginModalPresentationWithCompletionHandler:(id)arg1 forCloseSpace:(BOOL)arg2 waitUntilDone:(BOOL)arg3;
- (id)collapsedTabWindow;
- (BOOL)createModalStackForWindow:(id)arg1;
- (void)dealloc;
- (BOOL)disableBeginPresentation;
- (void)displayChanged;
- (BOOL)dragShouldSnapBackForMinimize;
- (void)draggedWindowMovedToSpace:(unsigned long long)arg1 repositionUnderMouseIfDetached:(BOOL)arg2;
- (void)endModalPresentationWithCompletionHandler:(id)arg1;
- (void)endTilePresentation;
- (id)init;
- (BOOL)isDragActive;
- (BOOL)isPresentedModally;
- (double)modalWindowWidth;
- (void)nonAnimatedBeginModalPresentationForTileJoin;
- (void)registerForNotifications:(BOOL)arg1;
- (void)reshapeContents;
- (void)reshapeFrontWindow;
- (id)selectedWindow;
- (void)setDisableBeginPresentation:(BOOL)arg1;
- (void)setSpace:(id)arg1;
- (id)space;
- (void)tearDownAnyModalState;
- (void)tearDownAnyModalStateAnimating:(BOOL)arg1;
- (void)updateDraggingDimWindow;
- (void)windowDidBecomeKeyNotification:(id)arg1;
- (void)windowDidEndDraggingNotification:(id)arg1;
- (id)windowStackController;
- (void)windowWillStartDraggingNotification:(id)arg1;

// _NSFullScreenModalStackController (NSWindow)

- (void)applyWindowStateForModalStackGroupToWindow:(id)arg1;
- (void)clearWindowStateForModalStackGroupToWindow:(id)arg1;
- (void)didDoTabbedOrderAboveForWindow:(id)arg1;
- (void)didDoTabbedOrderOutForWindow:(id)arg1;
- (void)tabBarWillSelectTab;
- (void)windowStackTabGroupDidChangeForWindow:(id)arg1;

@end
