/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface _NSFullScreenTileOverlayWindowContentView : NSView

- (unsigned int)_CAViewFlags;
- (void)mouseDown:(id)arg1;
- (BOOL)shouldDelayWindowOrderingForEvent:(id)arg1;

@end
