/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface _NSFunctionRowRootView : NSFunctionRowBackgroundColorView {
    NSFunctionRow * _functionRow;
}

@property (atomic, readonly) NSFunctionRow *functionRow;

+ (id)keyPathsForValuesAffectingFunctionRow;

- (id)accessibilityParentAttribute;
- (void)dealloc;
- (id)functionRow;
- (id)init;
- (id)initWithFunctionRow:(id)arg1;

@end
