/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface _NSHMDDisplayLink : NSHMDDisplayLink {
    id  _displayTimingBlock;
    unsigned long long  _suspensions;
    NSObject<OS_dispatch_source> * _timer;
}

- (void)dealloc;
- (id)init;
- (id)initWithDisplayTiming:(id)arg1 handler:(id)arg2;
- (void)invalidate;
- (BOOL)isValid;
- (void)resume;
- (void)suspend;

@end
