/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface _NSTouchBarSpacePreviewView : NSView {
    NSView * _backgroundView;
    CALayer * _dotsLayer;
}

- (BOOL)_shouldDoLayerPerformanceUpdates;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)layout;
- (void)updateLayer;
- (BOOL)wantsUpdateLayer;

@end
