/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface _NSTouchBarColorPickerDoubleTapButton : NSView {
    id  _actionHandler;
    NSImageView * _armedImageView;
    BOOL  _prearmed;
    long long  _state;
    NSImageView * _successImageView;
    _NSTouchBarColorPickerSwatch * _swatchView;
}

@property (atomic, readwrite, copy) id actionHandler;
@property (atomic, readwrite, copy) NSColor *color;
@property (atomic, readwrite) BOOL prearmed;

- (long long)_defaultState;
- (id)actionHandler;
- (id)color;
- (void)dealloc;
- (id)declaredLayoutConstraints;
- (void)engage;
- (void)fallback;
- (void)handlePress:(id)arg1;
- (void)highlight:(BOOL)arg1;
- (id)initWithArmedImage:(id)arg1 successImage:(id)arg2;
- (BOOL)prearmed;
- (void)setActionHandler:(id)arg1;
- (void)setColor:(id)arg1;
- (void)setFallbackTimer;
- (void)setPrearmed:(BOOL)arg1;
- (void)setState:(long long)arg1;
- (long long)state;
- (void)unsetFallbackTimer;
- (void)updateSubviewsForState;

@end
