/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface _NSUnbufferedLayerTreeWindowContentView : NSView

- (unsigned int)_CAViewFlags;

@end
