/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface _NSViewAnimator_NSButton : _NSViewAnimator

- (void)setAlternateImage:(id)arg1;
- (void)setAlternateTitle:(id)arg1;
- (void)setAttributedAlternateTitle:(id)arg1;
- (void)setAttributedTitle:(id)arg1;
- (void)setBezelColor:(id)arg1;
- (void)setImage:(id)arg1;
- (void)setImagePosition:(unsigned long long)arg1;
- (void)setTitle:(id)arg1;

@end
