/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface NSBinder : NSObject <NSCoding> {
    struct __binderFlags { 
        unsigned int _isConnected : 1; 
        unsigned int _hasPerformedObservationRegistration : 1; 
        unsigned int _isObserving : 1; 
        unsigned int _suspendObservationProcessing : 1; 
        unsigned int _needsRefreshWhenObserverationProcessingResumes : 1; 
        unsigned int _reservedBinder : 27; 
    }  _binderFlags;
    NSMutableArray * _bindingInfos;
    unsigned long long  _bindingsBoundMask;
    id  _expectedObservingInfo;
    id  _object;
    id  _plugin;
}

+ (struct __CFArray { }*)_allBinderClasses;
+ (BOOL)_autoCreateBinderForObject:(id)arg1 withController:(id)arg2;
+ (id)_deprecatedBindings;
+ (void)_didPresentModalAlert:(BOOL)arg1 contextInfo:(struct { id x1; }*)arg2;
+ (id)_enumeratedBindings:(id)arg1 storage:(id*)arg2 number:(unsigned long long)arg3 numberFirstBinding:(BOOL)arg4 maxNumber:(unsigned long long)arg5;
+ (Class)_pluginClassWithObject:(id)arg1;
+ (id)_pluginProtocol;
+ (id)_prepareAlertError:(id)arg1 responder:(id*)arg2 responderCandidate:(id)arg3 window:(id*)arg4 recoveryAttempter:(id)arg5;
+ (void)_presentAlertPanelForError:(id)arg1 responder:(id)arg2 responderCandidate:(id)arg3;
+ (void)_presentSheetForError:(id)arg1 responder:(id)arg2 responderCandidate:(id)arg3 delegate:(id)arg4 callback:(SEL)arg5 callbackContextInfo:(void*)arg6;
+ (id)binderClassesForObject:(id)arg1;
+ (id)binderClassesSuperseded;
+ (id)bindingCategory;
+ (id)bindingsForObject:(id)arg1;
+ (BOOL)isUsableWithObject:(id)arg1;
+ (void)load;
+ (id)objectMechanismsRequiredForObject:(id)arg1;

- (void)_addBinding:(id)arg1 toController:(id)arg2 withKeyPath:(id)arg3 valueTransformerName:(id)arg4 options:(id)arg5;
- (id)_applyValueTransformerToValue:(id)arg1 forBindingInfo:(id)arg2 reverse:(BOOL)arg3;
- (unsigned long long)_bindingAdaptorMethodsNeededMask;
- (id)_bindingInfoForBinding:(id)arg1;
- (unsigned long long)_bindingInfoIndexForBinding:(id)arg1;
- (id)_bindingInfos;
- (void)_cleanUpConnectionWithSynchronizePeerBinders:(BOOL)arg1;
- (void)_clearDependenciesWithAllPeerBinders;
- (void)_connectionWasBroken;
- (void)_connectionWasEstablished;
- (void)_copyDetailsFromBinder:(id)arg1;
- (void)_dealloc;
- (BOOL)_handleObservingRefresh;
- (void)_init;
- (id)_initWithObjectNoExceptions:(id)arg1;
- (void)_invokeSelector:(SEL)arg1 withArguments:(id)arg2 onKeyPath:(id)arg3 ofObject:(id)arg4 mode:(/* Warning: unhandled struct encoding: '{__NSKeyValueCodingControllerModeType=qQ@}' */ struct __NSKeyValueCodingControllerModeType { long long x1; unsigned long long x2; id x3; })arg5 raisesForNotApplicableKeys:(BOOL)arg6;
- (BOOL)_isAnyBindingInMaskBound:(unsigned long long)arg1;
- (BOOL)_isAutoCreated;
- (BOOL)_isBindingEstablished:(id)arg1;
- (BOOL)_isBooleanBinding:(id)arg1;
- (BOOL)_isKeyPathBound:(id)arg1;
- (void)_logError:(id)arg1 fallbackMessage:(id)arg2 relatedToBinding:(id)arg3;
- (void)_markAutoCreated:(BOOL)arg1;
- (id)_mutableArrayValueForKeyPath:(id)arg1 ofObject:(id)arg2 atIndex:(unsigned long long)arg3 raisesForNotApplicableKeys:(BOOL)arg4;
- (id)_mutableSetValueForKeyPath:(id)arg1 ofObject:(id)arg2 atIndex:(unsigned long long)arg3 raisesForNotApplicableKeys:(BOOL)arg4;
- (BOOL)_observationProcessingEnabled;
- (BOOL)_observeKeyPathForBindingInfo:(id)arg1 registerOrUnregister:(BOOL)arg2;
- (BOOL)_observeKeyPathForRelatedBinder:(id)arg1 registerOrUnregister:(BOOL)arg2;
- (void)_observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 context:(void*)arg3;
- (id)_optionsForBinding:(id)arg1 specifyOnlyIfDifferentFromDefault:(BOOL)arg2;
- (void)_performConnectionEstablishedRefresh;
- (id)_plugin;
- (void)_prepareIndirectKeyValueCodingCallWithPartialControllerKey:(id)arg1 controller:(id)arg2;
- (void)_presentModalAlertWithError:(id)arg1 responder:(id)arg2 relatedToBinding:(id)arg3;
- (id)_referenceBinderController;
- (id)_referenceBinding;
- (void)_removeBinding:(id)arg1;
- (void)_removeBinding:(id)arg1 byReplacingWithRemainingBindingsInArray:(id)arg2;
- (id)_resolveMarkerToPlaceholder:(id)arg1 forBindingInfo:(id)arg2 allowPluginOverride:(BOOL)arg3;
- (void)_resumeObservationNotificationProcessing;
- (void)_setController:(id)arg1 forBinding:(id)arg2;
- (void)_setObject:(id)arg1;
- (void)_setOptions:(id)arg1 forBinding:(id)arg2;
- (void)_setOptions:(id)arg1 withBindingInfo:(id)arg2;
- (void)_setParameter:(id)arg1 forOption:(id)arg2 withBindingInfo:(id)arg3;
- (BOOL)_setValue:(id*)arg1 forKeyPath:(id)arg2 ofObject:(id)arg3 mode:(/* Warning: unhandled struct encoding: '{__NSKeyValueCodingControllerModeType=qQ@}' */ struct __NSKeyValueCodingControllerModeType { long long x1; unsigned long long x2; id x3; })arg4 validateImmediately:(BOOL)arg5 raisesForNotApplicableKeys:(BOOL)arg6 error:(id*)arg7;
- (void)_suspendObservationNotificationProcessing;
- (void)_synchronizeWithPeerBindersInArray:(id)arg1;
- (BOOL)_testBinderConfiguration:(id)arg1 repairBindings:(BOOL)arg2;
- (void)_updateDependenciesWithPeerBinders:(id)arg1;
- (void)_updateObservingRegistration:(BOOL)arg1;
- (void)_updatePlaceholdersForBindingInfo:(id)arg1;
- (id)_valueForKeyPath:(id)arg1 ofObject:(id)arg2 mode:(/* Warning: unhandled struct encoding: '{__NSKeyValueCodingControllerModeType=qQ@}' */ struct __NSKeyValueCodingControllerModeType { long long x1; unsigned long long x2; id x3; })arg3 raisesForNotApplicableKeys:(BOOL)arg4;
- (id)_valueTransformerNameForBinding:(id)arg1;
- (void)addBinding:(id)arg1 toController:(id)arg2 withKeyPath:(id)arg3 valueTransformer:(id)arg4 options:(id)arg5;
- (BOOL)alwaysPresentsApplicationModalAlertsWithBinding:(id)arg1;
- (id)applyValueTransformerToValue:(id)arg1 forBinding:(id)arg2 reverse:(BOOL)arg3;
- (id)availableBindings;
- (BOOL)bindingRunsAlerts:(id)arg1;
- (void)breakConnection;
- (BOOL)canAddBinding:(id)arg1 toController:(id)arg2;
- (BOOL)canApplyValueTransformer:(id)arg1 toBinding:(id)arg2;
- (BOOL)commitEditing;
- (BOOL)commitEditingAndReturnError:(id*)arg1;
- (void)commitEditingWithDelegate:(id)arg1 didCommitSelector:(SEL)arg2 contextInfo:(void*)arg3;
- (id)controllerForBinding:(id)arg1;
- (id)copyToObject:(id)arg1;
- (void)dealloc;
- (id)deprecatedBindings;
- (id)description;
- (void)discardEditing;
- (void)encodeWithCoder:(id)arg1;
- (void)establishConnection;
- (id)initWithCoder:(id)arg1;
- (id)initWithObject:(id)arg1;
- (BOOL)invokeSelector:(SEL)arg1 withArguments:(id)arg2 forBinding:(id)arg3 atIndex:(unsigned long long)arg4 error:(id*)arg5;
- (BOOL)invokeSelector:(SEL)arg1 withArguments:(id)arg2 forBinding:(id)arg3 atIndexPath:(id)arg4 error:(id*)arg5;
- (BOOL)invokeSelector:(SEL)arg1 withArguments:(id)arg2 forBinding:(id)arg3 error:(id*)arg4;
- (BOOL)isBindingKeyOptional:(id)arg1;
- (BOOL)isBindingKeyless:(id)arg1;
- (BOOL)isBindingReadOnly:(id)arg1;
- (BOOL)isConnected;
- (BOOL)isEditing;
- (id)keyPathForBinding:(id)arg1;
- (id)mutableArrayValueForBinding:(id)arg1 atIndex:(unsigned long long)arg2 resolveMarkersToPlaceholders:(BOOL)arg3;
- (id)mutableArrayValueForBinding:(id)arg1 resolveMarkersToPlaceholders:(BOOL)arg2;
- (id)mutableSetValueForBinding:(id)arg1 atIndex:(unsigned long long)arg2 resolveMarkersToPlaceholders:(BOOL)arg3;
- (id)mutableSetValueForBinding:(id)arg1 resolveMarkersToPlaceholders:(BOOL)arg2;
- (id)object;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (id)placeholderForMarker:(id)arg1 withBinding:(id)arg2;
- (BOOL)raisesForNotApplicableKeysWithBinding:(id)arg1;
- (oneway void)releaseConnectionWithSynchronizePeerBinders:(BOOL)arg1;
- (void)removeBinding:(id)arg1;
- (id)resolveMarkerToPlaceholder:(id)arg1 binding:(id)arg2;
- (void)setAlwaysPresentsApplicationModalAlerts:(BOOL)arg1 withBinding:(id)arg2;
- (void)setPlaceholder:(id)arg1 forMarker:(id)arg2 withBinding:(id)arg3;
- (void)setRaisesForNotApplicableKeys:(BOOL)arg1 withBinding:(id)arg2;
- (void)setValidatesImmediately:(BOOL)arg1 withBinding:(id)arg2;
- (BOOL)setValue:(id*)arg1 forBinding:(id)arg2 atIndex:(unsigned long long)arg3 error:(id*)arg4;
- (BOOL)setValue:(id*)arg1 forBinding:(id)arg2 atIndexPath:(id)arg3 error:(id*)arg4;
- (BOOL)setValue:(id*)arg1 forBinding:(id)arg2 error:(id*)arg3;
- (BOOL)shouldProcessObservations;
- (BOOL)validatesImmediatelyWithBinding:(id)arg1;
- (Class)valueClassForBinding:(id)arg1;
- (id)valueForBinding:(id)arg1 atIndex:(unsigned long long)arg2 resolveMarkersToPlaceholders:(BOOL)arg3;
- (id)valueForBinding:(id)arg1 atIndexPath:(id)arg2 resolveMarkersToPlaceholders:(BOOL)arg3;
- (id)valueForBinding:(id)arg1 resolveMarkersToPlaceholders:(BOOL)arg2;
- (id)valueTransformerForBinding:(id)arg1;

// NSBinder (NSOutlineViewColumnBinder)

- (void)updateOutlineColumnDataCell:(id)arg1 forDisplayAtIndexPath:(id)arg2;
- (void)updateOutlineColumnOutlineCell:(id)arg1 forDisplayAtIndexPath:(id)arg2;

// NSBinder (NSTableColumnBinder)

- (BOOL)supportsTableEditing;
- (void)updateTableColumnDataCell:(id)arg1 forDisplayAtIndex:(unsigned long long)arg2;

// NSBinder (_NSEditableBinderHandshaking)

- (void)_noticeEditablePeerBinder:(id)arg1;

// NSBinder (_NSTextColorBinderHandshaking)

- (void)_noticeTextColorPeerBinder:(id)arg1;

@end
