/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface NSColorPickerUser : NSColorPicker <NSColorPickingCustom> {
    BOOL  bScaleOrNot;
    NSString * currImageName;
    id  defaultTiffImage;
    NSMutableDictionary * imageDictionary;
    id  optionsPopUp;
    NSPopUpButton * palettePopUpButton;
    id  paste;
    id  removeField;
    id  renameField;
    id  renamePanelController;
    id  reserved1;
    id  reserved2;
    NSMenuItem * spectrumMenuItem;
    id  tiffView;
    id  userPickerView;
}

- (void)_addImage:(id)arg1 named:(id)arg2;
- (id)_imageFromItemTitle:(id)arg1;
- (double)_insertionOrder;
- (id)_newImageName:(id)arg1;
- (void)_open:(id)arg1;
- (void)_open:(id)arg1 fromImage:(id)arg2 withName:(id)arg3;
- (id)_popUpButton;
- (void)_remove:(id)arg1;
- (BOOL)_removeOrRename:(id)arg1;
- (void)_rename:(id)arg1;
- (void)_restoreMode;
- (void)_saveMode;
- (void)_setCurrImageName:(id)arg1;
- (id)_shortNameFor:(id)arg1;
- (void)_switchImage:(id)arg1 andUpdateColor:(BOOL)arg2;
- (id)buttonToolTip;
- (void)copy:(id)arg1;
- (long long)currentMode;
- (void)dealloc;
- (id)initWithPickerMask:(unsigned long long)arg1 colorPanel:(id)arg2;
- (void)open:(id)arg1;
- (void)paste:(id)arg1;
- (BOOL)pasteItemUpdate:(id)arg1;
- (id)provideNewView:(BOOL)arg1;
- (void)remove:(id)arg1;
- (void)rename:(id)arg1;
- (BOOL)saveImageNamed:(id)arg1 andShowWarnings:(BOOL)arg2;
- (void)setColor:(id)arg1;
- (BOOL)supportsMode:(long long)arg1;
- (void)switchImage:(id)arg1;
- (id)validateRename;
- (BOOL)worksWhenModal;

@end
