/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface NSDocumentTitlebarPopoverViewController : NSViewController <NSRemoteViewDelegate> {
    id  advanceToRunPhaseWaiter;
    id  cleanupKVOBlock;
    NSDocument * document;
    id  invalidationHandler;
    BOOL  isPerformingOperation;
    id  mouseDownMonitor;
    NSError * nonModalError;
    id  operationWaiter;
    NSOperationQueue * queue;
}

@property (atomic, readwrite, copy) id invalidationHandler;
@property (atomic, readwrite, copy) id operationWaiter;
@property (atomic, readonly) BOOL shouldRetainExportedObject;

+ (Class)_remoteViewClass;
+ (Class)_sharedXPCListenerClass;
+ (void)warmup;

- (void)_didFinishOperation;
- (void)_enqueueOperationWithBlock:(id)arg1;
- (BOOL)_setupBridge;
- (void)_whenDocumentOperationCompletesPerformBlock:(id)arg1;
- (void)_willStartOperation;
- (void)dealloc;
- (id)initWithDocument:(id)arg1;
- (void)invalidate;
- (id)invalidationHandler;
- (void)loadView;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (id)operationWaiter;
- (void)prepareViewThenContinue:(id)arg1;
- (void)setInvalidationHandler:(id)arg1;
- (void)setOperationWaiter:(id)arg1;
- (void)viewDidAdvanceToRunPhase:(id)arg1;
- (void)viewDidInvalidate:(id)arg1;

@end
