/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface NSFileDragSource : NSObject

+ (unsigned long long)draggingSourceOperationMaskForLocal:(BOOL)arg1;

@end
