/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface NSFunctionRowActionTracker : NSObject {
    NSControl * _control;
    SEL  _originalAction;
    id  _originalTarget;
    NSGestureRecognizer * _recognizer;
    NSTouch * _touch;
    NSString * _uniqueIdentifier;
    NSMutableArray * _viewHierarchy;
}

@property (atomic, readwrite, retain) NSControl *control;
@property (atomic, readwrite) SEL originalAction;
@property (atomic, readwrite, retain) id originalTarget;
@property (atomic, readwrite, retain) NSGestureRecognizer *recognizer;
@property (atomic, readwrite, retain) NSTouch *touch;

+ (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_frameForElement:(id)arg1;
+ (id)_titleForElement:(id)arg1;

- (void)_log;
- (void)_ns_logAction_ns:(id)arg1;
- (id)control;
- (void)dealloc;
- (SEL)originalAction;
- (id)originalTarget;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)recognizer;
- (void)setControl:(id)arg1;
- (void)setOriginalAction:(SEL)arg1;
- (void)setOriginalTarget:(id)arg1;
- (void)setRecognizer:(id)arg1;
- (void)setTouch:(id)arg1;
- (id)touch;

@end
