/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface NSIBUserDefinedRuntimeAttributesConnector : NSObject {
    NSArray * keyPaths;
    id  object;
    NSArray * values;
}

- (void)dealloc;
- (id)destination;
- (void)encodeWithCoder:(id)arg1;
- (void)establishConnection;
- (id)initWithCoder:(id)arg1;
- (void)instantiateWithObjectInstantiator:(id)arg1;
- (id)keyPaths;
- (id)label;
- (id)object;
- (void)replaceObject:(id)arg1 withObject:(id)arg2;
- (void)setDestination:(id)arg1;
- (void)setKeyPaths:(id)arg1;
- (void)setLabel:(id)arg1;
- (void)setObject:(id)arg1;
- (void)setSource:(id)arg1;
- (void)setValues:(id)arg1;
- (id)source;
- (id)values;

@end
