/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface NSNavNodeTask : NSObject {
    NSNavNode * _node;
    NSNavProgressWindowController * _progressWindowController;
}

@property (atomic, readwrite, retain) NSNavNode *node;
@property (atomic, readonly, retain) NSNavProgressWindowController *progressWindowController;

+ (void)addTask:(id)arg1 forNode:(id)arg2;
+ (id)allTasksForNode:(id)arg1;
+ (void)removeAllTasksForNode:(id)arg1;
+ (void)removeTask:(id)arg1 forNode:(id)arg2;

- (id)_imageForOSType:(unsigned int)arg1;
- (void)cancel;
- (void)dealloc;
- (id)initWithNode:(id)arg1;
- (id)node;
- (id)progressWindowController;
- (void)setNode:(id)arg1;
- (BOOL)worksWhenModal;

@end
