/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface NSPersistentUIPreservedStateDirectory : NSObject {
    int  privateStateFD;
    NSArray * publicWindowDictionaries;
}

- (void)dealloc;
- (void)dispose;
- (id)initWithStateDirectory:(id)arg1;
- (BOOL)isValid;
- (BOOL)readRecordsIntoArray:(id)arg1 includeCarbonWindows:(BOOL)arg2 includeCocoaWindows:(BOOL)arg3;

@end
