/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface NSRGBColorValueFormatter : NSFormatter {
    NSNumberFormatter * _currentFormatter;
    NSRGBColorValueTransformer * _currentTransformer;
    long long  _entryMode;
}

@property (atomic, readonly) long long entryMode;

+ (id)formatterForEntryMode:(long long)arg1;

- (id)_currentFormatter;
- (id)_currentTransformer;
- (void)dealloc;
- (long long)entryMode;
- (BOOL)getObjectValue:(out id*)arg1 forString:(id)arg2 errorDescription:(out id*)arg3;
- (id)initWithEntryMode:(long long)arg1;
- (id)stringForObjectValue:(id)arg1;

@end
