/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface NSSavePanelNameFieldCell : NSTextFieldCell

// Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit

- (id)_textAttributes;

// Image: /Applications/Xcode.app/Contents/Developer/usr/lib/libMainThreadChecker.dylib

- (BOOL)wantsNotificationForMarkedText;

@end
