/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface NSStepper : NSControl <DebugHierarchyObject, NSAccessibilityStepper> {
    unsigned int  _reserved1;
    unsigned int  _reserved2;
    unsigned int  _reserved3;
    unsigned int  _reserved4;
}

@property (atomic, readwrite) BOOL autorepeat;
@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (atomic, readonly) unsigned long long hash;
@property (atomic, readwrite) double increment;
@property (atomic, readwrite) double maxValue;
@property (atomic, readwrite) double minValue;
@property (atomic, readonly) Class superclass;
@property (atomic, readwrite) BOOL valueWraps;

// Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit

+ (void)initialize;

- (BOOL)_contentHuggingDefault_isUsuallyFixedHeight;
- (BOOL)_contentHuggingDefault_isUsuallyFixedWidth;
- (BOOL)_shouldRerouteCellAPIs;

// Image: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Debugger/libViewDebuggerSupport.dylib

// NSStepper (DebugHierarchyAdditions)

- (id)debugHierarchyPropertyDescriptions;

// Image: /Applications/Xcode.app/Contents/Developer/usr/lib/libMainThreadChecker.dylib

- (BOOL)acceptsFirstMouse:(id)arg1;
- (id)accessibilityLabel;
- (BOOL)accessibilityPerformDecrement;
- (BOOL)accessibilityPerformIncrement;
- (id)accessibilityValue;
- (struct NSEdgeInsets { double x1; double x2; double x3; double x4; })alignmentRectInsets;
- (BOOL)autorepeat;
- (void)encodeWithCoder:(id)arg1;
- (double)increment;
- (id)initWithCoder:(id)arg1;
- (double)maxValue;
- (double)minValue;
- (void)moveDown:(id)arg1;
- (void)moveUp:(id)arg1;
- (id)ns_widgetType;
- (void)setAutorepeat:(BOOL)arg1;
- (void)setIncrement:(double)arg1;
- (void)setMaxValue:(double)arg1;
- (void)setMinValue:(double)arg1;
- (void)setValueWraps:(BOOL)arg1;
- (BOOL)valueWraps;

@end
