/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface NSTouchBarColorPickerSliderGrayscaleArtworkProvider : NSTouchBarColorPickerSliderArtworkProvider

- (id)accessibilityValueStringForValue:(double)arg1;
- (id)formattedValue:(double)arg1;
- (BOOL)isEqual:(id)arg1;
- (double)lightnessForValue:(double)arg1 baseColor:(id)arg2 horizontallyFlipped:(BOOL)arg3 allowedColorSpaces:(id)arg4;
- (id)sliderLabel;
- (void)updateRootTrackLayer:(id)arg1 color:(id)arg2 horizontallyFlipped:(BOOL)arg3 allowedColorSpaces:(id)arg4;
- (double)valueFromAccessibilityValueString:(id)arg1;

@end
