/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface NSTouchBarColorListPickerScrubberLayoutAttributes : NSScrubberLayoutAttributes {
    BOOL  _isLeftmostItem;
    BOOL  _isRightmostItem;
}

@property (atomic, readwrite) BOOL isLeftmostItem;
@property (atomic, readwrite) BOOL isRightmostItem;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isLeftmostItem;
- (BOOL)isRightmostItem;
- (void)setIsLeftmostItem:(BOOL)arg1;
- (void)setIsRightmostItem:(BOOL)arg1;

@end
