/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface NSTouchBarColorPickerSliderBrightnessArtworkProvider : NSTouchBarColorPickerSliderHSBArtworkProvider {
    double  _displayHue;
    double  _displaySaturation;
}

- (id)accessibilityValueStringForValue:(double)arg1;
- (id)formattedValue:(double)arg1;
- (id)initWithDisplayHue:(double)arg1 displaySaturation:(double)arg2;
- (BOOL)isEqual:(id)arg1;
- (double)lightnessForValue:(double)arg1 baseColor:(id)arg2 horizontallyFlipped:(BOOL)arg3 allowedColorSpaces:(id)arg4;
- (long long)representedHSBComponent;
- (id)sliderLabel;
- (void)updateRootTrackLayer:(id)arg1 color:(id)arg2 horizontallyFlipped:(BOOL)arg3 allowedColorSpaces:(id)arg4;
- (double)valueFromAccessibilityValueString:(id)arg1;

@end
