/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface NSTouchBarControlStripGrabberLayoutAttributes : NSCollectionViewLayoutAttributes {
    BOOL  _enabled;
    BOOL  _expanded;
}

@property (getter=isEnabled, atomic, readwrite) BOOL enabled;
@property (getter=isExpanded, atomic, readwrite) BOOL expanded;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (BOOL)isEnabled;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isExpanded;
- (void)setEnabled:(BOOL)arg1;
- (void)setExpanded:(BOOL)arg1;

@end
