/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Metal.framework/Versions/A/Metal
 */

@interface MTLCompileOptions : NSObject <NSCopying>

@property (nonatomic, readwrite) BOOL cubemapArrayEnabled;
@property (nonatomic, readwrite) BOOL debuggingEnabled;
@property (nonatomic, readwrite) BOOL denormsEnabled;
@property (nonatomic, readwrite) BOOL fastMathEnabled;
@property (nonatomic, readwrite) BOOL framebufferReadEnabled;
@property (nonatomic, readwrite) unsigned long long languageVersion;
@property (nonatomic, readwrite) BOOL nativeDoubleEnabled;
@property (nonatomic, readwrite, copy) NSDictionary *preprocessorMacros;

+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone { }*)arg1;

- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
