/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Metal.framework/Versions/A/Metal
 */

@interface MTLDepthStencilDescriptor : NSObject <NSCopying>

@property (nonatomic, readwrite, copy) MTLStencilDescriptor *backFaceStencil;
@property (nonatomic, readwrite) unsigned long long depthCompareFunction;
@property (atomic, readonly) const /* Warning: unhandled struct encoding: '{MTLDepthStencilDescriptorPrivate=@@Qc@}' */ struct MTLDepthStencilDescriptorPrivate { id x1; unsigned long long x2; BOOL x3; id x4; }*depthStencilPrivate;
@property (getter=isDepthWriteEnabled, nonatomic, readwrite) BOOL depthWriteEnabled;
@property (nonatomic, readwrite, copy) MTLStencilDescriptor *frontFaceStencil;
@property (nonatomic, readwrite, copy) NSString *label;

+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone { }*)arg1;

- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
