/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Metal.framework/Versions/A/Metal
 */

@interface MTLInferredInput : NSObject {
    BOOL  _baseInstanceUnused;
    unsigned long long  _bufferIndex;
    unsigned long long  _dataType;
    unsigned long long  _offset;
    unsigned long long  _stepFunction;
    unsigned long long  _stepRate;
    unsigned long long  _stride;
}

@property (atomic, readonly) BOOL baseInstanceUnused;
@property (atomic, readonly) unsigned long long bufferIndex;
@property (atomic, readonly) unsigned long long dataType;
@property (atomic, readonly) unsigned long long offset;
@property (atomic, readonly) unsigned long long stepFunction;
@property (atomic, readonly) unsigned long long stepRate;
@property (atomic, readonly) unsigned long long stride;

- (BOOL)baseInstanceUnused;
- (unsigned long long)bufferIndex;
- (unsigned long long)dataType;
- (id)description;
- (id)formattedDescription:(unsigned long long)arg1;
- (id)initWithDataType:(unsigned long long)arg1 offset:(unsigned long long)arg2 bufferIndex:(unsigned long long)arg3 stride:(unsigned long long)arg4 stepFunction:(unsigned long long)arg5 stepRate:(unsigned long long)arg6 baseInstanceUnused:(BOOL)arg7;
- (unsigned long long)offset;
- (unsigned long long)stepFunction;
- (unsigned long long)stepRate;
- (unsigned long long)stride;

@end
