/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Sharing.framework/Versions/A/Sharing
 */

@interface SFSiriClient : NSObject {
    NSObject<OS_dispatch_queue> * _dispatchQueue;
    id  _siriDialogHandler;
}

@property (nonatomic, readwrite, retain) NSObject<OS_dispatch_queue> *dispatchQueue;
@property (nonatomic, readwrite, copy) id siriDialogHandler;

- (void).cxx_destruct;
- (void)_activate;
- (void)_deviceSetupEnd;
- (void)_invalidate;
- (void)activate;
- (void)deviceSetupBegin;
- (void)deviceSetupEnd;
- (id)dispatchQueue;
- (id)init;
- (void)invalidate;
- (void)setDispatchQueue:(id)arg1;
- (void)setSiriDialogHandler:(id)arg1;
- (id)siriDialogHandler;
- (void)speakText:(id)arg1 completion:(id)arg2;
- (void)speakText:(id)arg1 rate:(double)arg2 completion:(id)arg3;
- (void)stopSpeaking;

@end
